const fs = require("fs");
const path = require("path");

const OUTPUT_DIR = path.join(process.cwd(), ".codex_tmp", "drc_man_troubleshooting_25k");
const OUTPUT_PATH = path.join(OUTPUT_DIR, "drc_man_troubleshooting_25k_faq.json");
const SUMMARY_PATH = path.join(OUTPUT_DIR, "drc_man_troubleshooting_25k_summary.json");
const MARKDOWN_PATH = path.join(OUTPUT_DIR, "drc_man_troubleshooting_25k_overview.md");
const SOURCE_SUMMARY = "DRC MAN 25K soguk oda ariza tespit bankasi";

const trQuestionTemplates = [
  (context, family) => `${context.trLabel} icin ${family.trSubject} neden olur`,
  (context, family) => `${context.trLabel} sisteminde ${family.trSubject} olursa usta once neyi kontrol eder`,
  (context, family) => `${context.trLabel} odasinda ${family.trSubject} varsa sorun hangi tarafta olabilir`,
  (context, family) => `${context.trLabel} kurulumunda ${family.trSubject} montaj hatasindan olabilir mi`,
  (context, family) => `${context.trLabel} uygulamasinda ${family.trSubject} tekrar ediyorsa koken ne olabilir`,
  (context, family) => `${context.trLabel} icin ${family.trSubject} durumunda hangi olcumler alinmali`,
  (context, family) => `${context.trLabel} sisteminde ${family.trSubject} varsa hava tarafi mi gaz devresi mi once incelenir`,
  (context, family) => `${context.trLabel} odasinda ${family.trSubject} oldugunda servis sirasi nasil olmali`,
  (context, family) => `${context.trLabel} uygulamasinda ${family.trSubject} icin en sik hata nedir`,
  (context, family) => `${context.trLabel} tesisatinda ${family.trSubject} kalici nasil cozulur`,
];

const deQuestionTemplates = [
  (context, family) => `warum kommt es dazu, dass ${family.deSubject} im ${context.deLabel}`,
  (context, family) => `was prueft ein meister zuerst, wenn ${family.deSubject} im ${context.deLabel}`,
  (context, family) => `auf welcher seite kann der fehler liegen, wenn ${family.deSubject} im ${context.deLabel}`,
  (context, family) => `kann ein montagefehler dazu fuehren, dass ${family.deSubject} im ${context.deLabel}`,
  (context, family) => `welche ursache ist typisch, wenn ${family.deSubject} im ${context.deLabel} immer wieder auftritt`,
  (context, family) => `welche messwerte nimmt man auf, wenn ${family.deSubject} im ${context.deLabel}`,
  (context, family) => `prueft man zuerst luftseite oder kaeltekreis, wenn ${family.deSubject} im ${context.deLabel}`,
  (context, family) => `wie sieht die service reihenfolge aus, wenn ${family.deSubject} im ${context.deLabel}`,
  (context, family) => `welcher typische fehler wird oft gemacht, wenn ${family.deSubject} im ${context.deLabel}`,
  (context, family) => `wie loest man es dauerhaft, wenn ${family.deSubject} im ${context.deLabel}`,
];

const faultFamilies = [
  {
    id: "room_not_cooling",
    trSubject: "oda yeterince sogutmuyor",
    deSubject: "der raum nicht ausreichend kuehlt",
    trCause: "yanlis kapasite secimi, kirli kondenser, buzlu evaporator veya gaz devresinin dengesiz calismasidir",
    deCause: "eine falsche Leistungswahl, ein verschmutzter Verfluessiger, ein vereister Verdampfer oder ein instabiler Kaeltekreis",
    trChecks: "kapi kullanimi, yukleme miktari, basma-emis degerleri, fan debisi ve serpantin yuzeyi birlikte kontrol edilir",
    deChecks: "Tuernutzung, Warenlast, Hoch- und Niederdruck, Ventilatorleistung und Registeroberflaeche gemeinsam geprueft werden",
    trWhy: "sogutma problemi cogu zaman tek parcadan degil, hava tarafi ile gaz devresinin beraber bozulmasindan cikar",
    deWhy: "Kuehlprobleme meist nicht von einem einzelnen Bauteil, sondern aus dem Zusammenspiel von Luftseite und Kaeltekreis entstehen",
    trMistake: "hemen gaz basmak ve kapasite ile hava akis kontrolunu atlamaktir",
    deMistake: "vorschnell Kaeltemittel nachzufuellen und Leistungs- sowie Luftfuehrungspruefung zu ueberspringen",
    keywords: ["sogutmuyor", "oda sicak", "room not cooling", "kuehlt nicht"],
    suggestions: ["kapasite secimi nasil yapilir", "yuksek basinc neden olur", "evaporator neden buz tutar"],
  },
  {
    id: "room_cools_slow",
    trSubject: "oda yavas soguyor",
    deSubject: "der raum langsam herunterkuehlt",
    trCause: "fazla urun yuklenmesi, kapinin sik acilmasi, yetersiz hava devri veya cihazin sinirda secilmesidir",
    deCause: "zu hohe Produktlast, haeufige Tueroeffnungen, unzureichende Luftumwaelzung oder eine grenzwertige Geraeteauswahl",
    trChecks: "urun giris sicakligi, gunluk yuk miktari, hava atis yonu ve odadaki istif duzeni incelenir",
    deChecks: "Wareneintrittstemperatur, Tageslast, Luftwurfrichtung und Stapelung im Raum geprueft werden",
    trWhy: "oda soguma hizi sadece cihaz gucuyle degil, iceri tasinan isi miktariyla belirlenir",
    deWhy: "die Abkuehlgeschwindigkeit nicht nur von der Geraeteleistung, sondern von der eingetragenen Waermemenge bestimmt wird",
    trMistake: "isletme yukunu hesaplamadan arizayi sadece cihaza baglamaktir",
    deMistake: "die Betriebslast nicht zu bewerten und den Fehler nur beim Geraet zu suchen",
    keywords: ["gec soguyor", "slow cooling", "langsam kuehlen"],
    suggestions: ["oda yuk hesabi nasil yapilir", "hava sirkulasyonu neden onemli", "muhafaza odasi ile sok oda farki nedir"],
  },
  {
    id: "temperature_unstable",
    trSubject: "oda sicakligi sabit kalmiyor",
    deSubject: "die raumtemperatur instabil bleibt",
    trCause: "sensor yerinin yanlis secilmesi, diferans ayarinin kotu olmasi, kapi trafigi veya kisa devre calismadir",
    deCause: "eine falsche Fuehlerposition, eine schlechte Hystereseeinstellung, Tuerspiel oder Kurzzyklusverhalten",
    trChecks: "sensor konumu, set-diferans ayari, kompresor start-stop sayisi ve fanin urune vurusu kontrol edilir",
    deChecks: "Fuehlerposition, Sollwert-Hysterese, Anzahl der Verdichterstarts und Luftwurf auf die Ware geprueft werden",
    trWhy: "regulator yanlis bilgi alirsa sistem gercek oda ihtiyacina gore degil, yanlis referansa gore davranir",
    deWhy: "die Regelung bei falscher Messinformation nicht dem realen Raumbedarf, sondern einem falschen Referenzpunkt folgt",
    trMistake: "sensor yerini gormeden termostati degistirmektir",
    deMistake: "den Regler zu tauschen, ohne die Fuehlerlage zu pruefen",
    keywords: ["sicaklik dalgalaniyor", "instabil", "temperature unstable"],
    suggestions: ["sensor nereye konur", "kisa devre calisma neden olur", "oda neden dengesiz sogur"],
  },
  {
    id: "product_freezing_in_plus_room",
    trSubject: "arti odada urun donuyor",
    deSubject: "produkt im plusraum anfriert",
    trCause: "sensorun yanlis yerde olmasi, hava atisinin urune direkt vurmasi veya diferans ayarinin asiri dar tutulmasidir",
    deCause: "eine falsche Fuehlerlage, direkter Luftwurf auf das Produkt oder eine zu enge Reglungsdifferenz",
    trChecks: "urun ustunde hava hizi, sensor mesafesi, set degeri ve fan yonu birlikte bakilir",
    deChecks: "Luftgeschwindigkeit am Produkt, Fuehlerabstand, Sollwert und Ventilatorrichtung zusammen geprueft werden",
    trWhy: "arti odada lokal soguk cepler urun cekirdegi yerine yuzeyi daha hizli dondurabilir",
    deWhy: "lokale Kaltzonen im Plusraum die Produktoberflaeche schneller anfrieren lassen als den Kern",
    trMistake: "sadece set degerini yukseltip hava yonunu ve sensor mantigini atlamaktir",
    deMistake: "nur den Sollwert anzuheben und Luftfuehrung sowie Fuehlerlogik zu ignorieren",
    keywords: ["urun donuyor", "freezing in plus room", "produkt friert an"],
    suggestions: ["sensor nereye konur", "hava akisi urune vurursa ne olur", "arti oda sicaklik araligi nedir"],
  },
  {
    id: "high_pressure_trip",
    trSubject: "yuksek basinc arizasi veriyor",
    deSubject: "eine hochdruck stoerung ausloest",
    trCause: "kirli kondenser, fan arizasi, sicak havanin geri donmesi, fazla gaz veya yuksek dis ortamdir",
    deCause: "ein verschmutzter Verfluessiger, Ventilatorstoerung, Rueckansaugung warmer Luft, Ueberfuellung oder hohe Umgebungstemperatur",
    trChecks: "kondenser serpantini, fan yonu, cihaz etrafindaki bosluk ve basma-subcool degerleri okunur",
    deChecks: "Verfluessigerregister, Ventilatorrichtung, Freiraeume um das Geraet sowie Hochdruck- und Subcoolingwerte geprueft werden",
    trWhy: "isi disari atilamazsa tum devre basma tarafinda zorlanir",
    deWhy: "der gesamte Kaeltekreis auf der Hochdruckseite belastet wird, wenn die Waerme nicht sauber abgefuehrt werden kann",
    trMistake: "sadece gaza bakip hava tarafini ihmal etmektir",
    deMistake: "nur auf das Kaeltemittel zu schauen und die Luftseite zu vernachlaessigen",
    keywords: ["yuksek basinc", "high pressure", "hochdruck"],
    suggestions: ["kondenser nereye konur", "subcool neden onemli", "fan neden donmuyor"],
  },
  {
    id: "low_pressure_trip",
    trSubject: "dusuk basinc arizasi veriyor",
    deSubject: "eine niederdruck stoerung ausloest",
    trCause: "gaz eksigi, genlesme valfinin ac beslemesi, evaporatorun buzlanmasi veya hava debisinin dusmesidir",
    deCause: "Kaeltemittelmangel, magere Einspritzung am Expansionsventil, Vereisung des Verdampfers oder zu wenig Luftmenge",
    trChecks: "superheat, sight glass, serpantin buzlanmasi, fanlar ve filter drier tikanikligi birlikte degerlendirilir",
    deChecks: "Superheat, Schauglas, Vereisung des Registers, Ventilatoren und eine moegliche Filtertrocknerblockade gemeinsam bewertet werden",
    trWhy: "emiste yeterli besleme olmazsa kompresor faydali sogutma yerine bos devreye dusmeye baslar",
    deWhy: "der Verdichter bei mangelnder Sauggasversorgung nicht mehr wirksam kuehlt, sondern leer laeuft",
    trMistake: "dusuk basinci gorur gormez direkt gaz eklemektir",
    deMistake: "bei Niederdruck sofort Kaeltemittel nachzufuellen",
    keywords: ["dusuk basinc", "low pressure", "niederdruck"],
    suggestions: ["gaz eksigi nasil anlasilir", "evaporator neden buz tutar", "genlesme valfi neden ac besler"],
  },
  {
    id: "evaporator_icing",
    trSubject: "evaporator buz tutuyor",
    deSubject: "der verdampfer vereist",
    trCause: "defrost yetersizligi, kapi kacaklari, dusuk hava debisi veya yanlis sensor mantigidir",
    deCause: "unzureichende Abtauung, Tuerrandundichtigkeiten, zu geringe Luftmenge oder falsche Fuehlerlogik",
    trChecks: "defrost zamanlari, rezistans cekisi, drenaj akisi, fan temizligi ve kapi contasi kontrol edilir",
    deChecks: "Abtauzeiten, Heizstrom, Ablauf, Ventilatorzustand und Tuerdichtung geprueft werden",
    trWhy: "evaporator buzlandiginda hava gecisi daralir ve sogutma kademeli olarak coker",
    deWhy: "bei vereistem Verdampfer der Luftdurchsatz sinkt und die Leistung schrittweise einbricht",
    trMistake: "buzu eritip kok sebebi aramadan sistemi tekrar devreye almaktir",
    deMistake: "nur abzutauen und die Grundursache nicht zu suchen",
    keywords: ["evaporator buz", "icing", "vereisung"],
    suggestions: ["defrost neden onemli", "kapi sizdirmazligi neden onemli", "fan hava akisi neden duser"],
  },
  {
    id: "defrost_not_working",
    trSubject: "defrost calismiyor",
    deSubject: "die abtauung nicht funktioniert",
    trCause: "rezistans arizasi, zaman ayari bozuklugu, defrost sonlandirma sensoru hatasi veya kontrol cikisi sorunudur",
    deCause: "Heizungsdefekt, falsche Zeiteinstellung, Fehler am Abtaufuehler oder ein Problem am Reglerausgang",
    trChecks: "defrost sirasinda enerji geliyor mu, rezistans akim cekiyor mu ve sonlandirma sensori dogru mu diye bakilir",
    deChecks: "waehrend der Abtauung Spannung anliegt, die Heizung Strom zieht und der Endfuehler plausibel arbeitet",
    trWhy: "defrost durursa serpantin dolar, hava akisi ve kapasite birlikte duser",
    deWhy: "ohne funktionierende Abtauung das Register zusetzt und Luftmenge wie Leistung zusammenbrechen",
    trMistake: "sadece sureyi uzatip rezistans ile sensoru olcmemektir",
    deMistake: "nur die Dauer zu verlaengern und Heizung sowie Fuehler nicht zu messen",
    keywords: ["defrost calismiyor", "abtauung", "abtaufehler"],
    suggestions: ["defrost sensoru nereye konur", "rezistans nasil kontrol edilir", "drenaj neden donar"],
  },
  {
    id: "drain_freezing",
    trSubject: "drenaj hatti donuyor",
    deSubject: "die kondensatleitung einfriert",
    trCause: "hatta egim eksikligi, rezistans olmamasi, soguk bolgeden korumasiz gecis veya tikanikliktir",
    deCause: "fehlendes Gefaelle, fehlende Begleitheizung, ungeschuetzte Fuehrung durch kalte Zonen oder eine Verstopfung",
    trChecks: "hat guzergahi, egim, rezistans devamligi ve suyun nerede biriktigi kontrol edilir",
    deChecks: "Leitungsweg, Gefaelle, Heizbandfunktion und Staustellen des Wassers geprueft werden",
    trWhy: "negatif veya sulu ortamda en kucuk su birikimi hizla buza donebilir",
    deWhy: "kleine Wasseransammlungen in kalten oder feuchten Bereichen sehr schnell zu Eis werden koennen",
    trMistake: "sadece tava rezistansina bakip hatin devamini unutmaktir",
    deMistake: "nur die Wannenheizung zu pruefen und den restlichen Leitungsweg zu vergessen",
    keywords: ["drenaj donuyor", "drain freezing", "ablauf friert ein"],
    suggestions: ["drenaj egimi neden onemli", "negatif depoda hat nasil korunur", "defrost suyu neden geri tasar"],
  },
  {
    id: "door_leak",
    trSubject: "kapi hava kaciriyor",
    deSubject: "die tuer luft zieht",
    trCause: "conta asinmasi, kasa ayarsizligi, esik problemi veya kapi kapama kuvvetinin dusmesidir",
    deCause: "verschlissene Dichtung, verzogene Zarge, Schwellenproblem oder zu geringe Schliesskraft",
    trChecks: "conta basisi, kapi ayari, kasanin kareligi ve terleme izleri kontrol edilir",
    deChecks: "Dichtungsdruck, Tuereinstellung, Rechtwinkligkeit der Zarge und Schwitzwasserspuren geprueft werden",
    trWhy: "kapi kacagi oda yukunu ve nem yukunu ayni anda buyutur",
    deWhy: "Tuerundichtigkeiten gleichzeitig Waerme- und Feuchteeintrag erhoehen",
    trMistake: "sadece kapiyi sert kapatmaya calisip kasayi ayarsiz birakmaktir",
    deMistake: "nur das Schliessen zu erzwingen und die Zarge nicht sauber auszurichten",
    keywords: ["kapi kacak", "door leak", "tuer undicht"],
    suggestions: ["kapi rezistansi neden gerekir", "conta ne zaman degisir", "kapi trafigi nasil yonetilir"],
  },
  {
    id: "panel_sweating",
    trSubject: "panel yuzeyinde terleme oluyor",
    deSubject: "die paneeloberflaeche schwitzt",
    trCause: "isi koprusu, eksik izolasyon, kapi kacaklari veya ortam neminin yuksek olmasidir",
    deCause: "Waermebruecken, fehlende Daemmung, Tuerrandundichtigkeiten oder hohe Umgebungsfeuchte",
    trChecks: "terleme noktasi, panel birlesimleri, silikon-sizdirmazlik ve dis ortam kosullari incelenir",
    deChecks: "Schwitzwasserstelle, Paneelstosse, Silikonabdichtung und Umgebungsbedingungen untersucht werden",
    trWhy: "yuzey sicakligi ciy noktasinin altina inince su yogusur",
    deWhy: "Feuchtigkeit kondensiert, wenn die Oberflaechentemperatur unter den Taupunkt faellt",
    trMistake: "yalniz boya veya silikonla ustunu kapatip isi koprusunu cozmeye calismaktir",
    deMistake: "nur optisch abzudichten, ohne die eigentliche Waermebruecke zu beseitigen",
    keywords: ["panel terleme", "condensation panel", "paneel schwitzt"],
    suggestions: ["ciy noktasi nedir", "panel birlesiminde neye dikkat edilir", "kapi kacagi neden terleme yapar"],
  },
  {
    id: "floor_icing",
    trSubject: "zemin buzlaniyor",
    deSubject: "der boden vereist",
    trCause: "zemin izolasyon eksigi, kapi trafigiyle su tasinmasi, drenaj sorunu veya dusuk yuzey sicakligidir",
    deCause: "fehlende Bodendaemmung, eingeschlepptes Wasser durch Tuerspiel, Ablaufprobleme oder zu niedrige Oberflaechentemperatur",
    trChecks: "zemin paneli, su birikimi, esik alani ve rezistans ihtiyaci birlikte degerlendirilir",
    deChecks: "Bodenaufbau, Wasseransammlung, Schwellenbereich und ein moeglicher Heizbedarf gemeinsam bewertet werden",
    trWhy: "su zeminde kalirsa ve yuzey soguksa buzlanma hizla yayilir",
    deWhy: "stehenbleibendes Wasser auf kalten Flaechen sehr schnell zu grossflaechiger Vereisung fuehrt",
    trMistake: "yalniz temizlikle cozum arayip zemindeki isi ve su yonetimini atlamaktir",
    deMistake: "nur zu reinigen und das Zusammenspiel aus Waerme und Wasser nicht zu betrachten",
    keywords: ["zemin buz", "floor icing", "boden vereist"],
    suggestions: ["zemin izolasyonu neden onemli", "esik tasarimi nasil olmali", "drenaj neden donar"],
  },
  {
    id: "fan_not_running",
    trSubject: "fan donmuyor",
    deSubject: "der ventilator nicht laeuft",
    trCause: "motor arizasi, kapasitor problemi, besleme eksigi veya buz-sikismadir",
    deCause: "Motorschaden, Kondensatorproblem, fehlende Versorgung oder Blockade durch Eis",
    trChecks: "besleme varligi, fanin serbest donusu, kapasitor degeri ve sargi durumu kontrol edilir",
    deChecks: "Spannung, freie Drehbarkeit, Kondensatorwert und Wicklungszustand geprueft werden",
    trWhy: "fan olmazsa serpantin isiyi aktaramaz ve tum sistem dengesi bozulur",
    deWhy: "ohne Ventilator der Waermeuebergang zusammenbricht und die gesamte Anlage aus dem Gleichgewicht geraet",
    trMistake: "motora suclama yapip besleme veya buz kilidini atlamaktir",
    deMistake: "nur den Motor zu beschuldigen und Versorgung oder Eisblockade zu uebersehen",
    keywords: ["fan calismiyor", "fan donmuyor", "ventilator steht"],
    suggestions: ["kapasitor nasil kontrol edilir", "evaporator neden buz tutar", "fan yonu neden onemli"],
  },
  {
    id: "weak_airflow",
    trSubject: "hava akisi yetersiz",
    deSubject: "der luftstrom zu schwach ist",
    trCause: "kirli serpantin, fan kanat kirlenmesi, istifin hava yolunu kapatmasi veya yanlis fan yonudur",
    deCause: "verschmutztes Register, verdreckte Ventilatorfluegel, blockierte Luftwege durch Stapelung oder falsche Laufrichtung",
    trChecks: "hava atis yolu, istif mesafesi, fan cekisi ve serpantin onundeki bosluklar kontrol edilir",
    deChecks: "Luftwege, Stapelabstaende, Ventilatorleistung und Freiraeume vor dem Register geprueft werden",
    trWhy: "hava debisi duserse serpantin soguk olsa bile oda isiyi alamaz",
    deWhy: "bei zu wenig Luftmenge der Raum die Kaelte nicht uebernehmen kann, selbst wenn das Register kalt ist",
    trMistake: "gaz tarafina odaklanip hava tarafindaki fiziksel engelleri gormemektir",
    deMistake: "sich nur auf den Kaeltekreis zu konzentrieren und die mechanischen Luftblockaden zu uebersehen",
    keywords: ["hava akisi zayif", "weak airflow", "schwacher luftstrom"],
    suggestions: ["istif mesafesi ne olmali", "fan yonu neden onemli", "serpantin temizligi nasil yapilir"],
  },
  {
    id: "compressor_not_starting",
    trSubject: "kompresor calismiyor",
    deSubject: "der verdichter nicht startet",
    trCause: "enerji eksigi, kontaktor-termik sorunu, basinc emniyeti, faz koruma veya kontrol emri eksigidir",
    deCause: "fehlende Versorgung, Schuetz- oder Motorschutzproblem, Drucksicherheit, Phasenueberwachung oder fehlender Reglerbefehl",
    trChecks: "fazlar, kontaktor cekmesi, termik durumu, presostatlar ve kontrol karti cikisi sirayla kontrol edilir",
    deChecks: "Phasen, Schuetzanzug, Motorschutzstatus, Druckschalter und Reglerausgang der Reihe nach geprueft werden",
    trWhy: "kompresorun durmasi mekanik kadar elektriksel koruma mantigindan da kaynaklanabilir",
    deWhy: "ein stillstehender Verdichter genauso oft aus Schutzlogik wie aus mechanischen Gruenden stillsteht",
    trMistake: "kompresoru dogrudan bozuk ilan edip kumanda zincirini olcmemektir",
    deMistake: "den Verdichter vorschnell als defekt zu bewerten und die Steuerkette nicht zu messen",
    keywords: ["kompresor calismiyor", "compressor not starting", "verdichter startet nicht"],
    suggestions: ["faz sirasi neden onemli", "termik neden atar", "presostat neden acilir"],
  },
  {
    id: "compressor_overload",
    trSubject: "kompresor termige dusuyor",
    deSubject: "der verdichter auf motorschutz geht",
    trCause: "yuksek akim, kotu sogutma, yuksek basinc, dusuk voltaj veya mekanik zorlanmadir",
    deCause: "hohe Stromaufnahme, schlechte Kuehlung, Hochdruck, Unterspannung oder mechanische Ueberlastung",
    trChecks: "akim olculur, fanlar ve kondenser temizligi bakilir, basinclar okunur ve voltaj dusumu kontrol edilir",
    deChecks: "Strom gemessen, Ventilatoren und Verfluessiger geprueft, Druckwerte gelesen und Spannungsabfall kontrolliert werden",
    trWhy: "termik sadece elektrik degil, kompresor zorlanmasinin da alarmidir",
    deWhy: "der Motorschutz nicht nur ein Elektrikthema, sondern ein Warnsignal fuer Verdichterueberlastung ist",
    trMistake: "termigi buyutmek veya sadece resetleyip tekrar denemektir",
    deMistake: "den Schutz groesser auszulegen oder nur zu resetten und neu zu starten",
    keywords: ["termik atiyor", "overload", "motorschutz"],
    suggestions: ["voltaj dusuk olursa ne olur", "yuksek basinc neden olur", "kondenser temizligi neden onemli"],
  },
  {
    id: "compressor_noise",
    trSubject: "kompresor anormal ses yapiyor",
    deSubject: "der verdichter ungewoehnliche geraeusche macht",
    trCause: "sivi donusu, mekanik asinma, vibrasyon iletimi veya montaj gevsekligidir",
    deCause: "Fluessigkeitsschlag, mechanischer Verschleiss, Vibrationsuebertragung oder lockere Montage",
    trChecks: "sesin baslangic ani, emis hatti durumu, titreSim takozlari ve boru temas noktalari incelenir",
    deChecks: "Zeitpunkt des Geraeusches, Zustand der Saugleitung, Schwingungsdaempfer und Rohrkontaktstellen geprueft werden",
    trWhy: "ses tipi kompresorun hangi kosulda zorlandigini anlatir",
    deWhy: "die Art des Geraeusches verraten kann, unter welcher Belastung der Verdichter steht",
    trMistake: "yalniz sesi dinleyip basinc ve superheat verisi almamaktir",
    deMistake: "nur auf das Geraeusch zu hoeren und keine Druck- oder Superheatwerte aufzunehmen",
    keywords: ["kompresor ses", "compressor noise", "verdichter geraeusch"],
    suggestions: ["sivi vurmasi nasil anlasilir", "vibrasyon nasil kesilir", "superheat neden olculur"],
  },
  {
    id: "liquid_return",
    trSubject: "kompresore sivi donuyor",
    deSubject: "fluessigkeit zum verdichter zurueckkehrt",
    trCause: "dusuk superheat, yanlis genlesme valfi ayari, fan problemi veya yuk dususudur",
    deCause: "niedriger Superheat, falsche Expansionsventileinstellung, Ventilatorproblem oder zu geringe Last",
    trChecks: "superheat, emis hatti sicakligi, valf ampulu konumu ve fan davranisi kontrol edilir",
    deChecks: "Superheat, Saugleitungstemperatur, Lage des Ventilfuehlers und Ventilatorverhalten geprueft werden",
    trWhy: "kompresor gaz sikistirmak icin tasarlanir; sivi donusu ic parcalara zarar verir",
    deWhy: "ein Verdichter fuer Gasverdichtung ausgelegt ist und Fluessigkeitsrueckkehr die Innenteile schaedigt",
    trMistake: "yalniz yag veya ses semptomuna bakip superheat olcmemektir",
    deMistake: "nur auf Oel oder Geraeusch zu schauen und keinen Superheat zu messen",
    keywords: ["sivi donusu", "floodback", "fluessigkeit rueckkehr"],
    suggestions: ["superheat nedir", "genlesme valfi neden avlanir", "fan gecikmesi ne ise yarar"],
  },
  {
    id: "oil_return",
    trSubject: "yag donusu zayif",
    deSubject: "die oelrueckfuehrung schwach ist",
    trCause: "yanlis boru capi, dusuk gaz hizi, kotu boru egimi veya tuzak eksikligidir",
    deCause: "falscher Rohrdurchmesser, zu geringe Gasgeschwindigkeit, schlechter Leitungsverlauf oder fehlende Oelfallen",
    trChecks: "suction hatti capi, dikey cikislar, oel tuzagi ve yuk kosullari birlikte incelenir",
    deChecks: "Saugleitungsdurchmesser, Steigleitungen, Oelfallen und Lastbedingungen gemeinsam geprueft werden",
    trWhy: "yag kompresore geri donmezse yaglama bozulur ve omur hizla duser",
    deWhy: "ohne saubere Oelrueckfuehrung die Schmierung leidet und die Lebensdauer schnell sinkt",
    trMistake: "sadece yag ekleyip boru geometrisini gozden kacirmaktir",
    deMistake: "nur Oel nachzufuellen und die Rohrgeometrie nicht zu bewerten",
    keywords: ["yag donusu", "oil return", "oelrueckfuehrung"],
    suggestions: ["oel tuzagi ne zaman gerekir", "boru capi nasil secilir", "uzun hatlarda neye dikkat edilir"],
  },
  {
    id: "refrigerant_shortage",
    trSubject: "gaz eksikligi var",
    deSubject: "kaeltemittelmangel besteht",
    trCause: "kacak, eksik sarj, servis sonrasi hatali dolum veya uzun sureli mikro sizintidir",
    deCause: "Leckage, Unterfuellung, fehlerhafte Fuellung nach Service oder eine langandauernde Mikroundichtigkeit",
    trChecks: "superheat, subcool, sight glass, birlesim noktalarinda iz ve kacak testi birlikte yapilir",
    deChecks: "Superheat, Subcooling, Schauglas, Oelspuren an Verbindungen und eine Leckpruefung gemeinsam durchgefuehrt werden",
    trWhy: "gaz azaldiginda evaporator tam beslenmez, kapasite ve kompresor sogutmasi bozulur",
    deWhy: "bei Kaeltemittelmangel der Verdampfer nicht mehr voll versorgt wird und Leistung wie Verdichterkuehlung leiden",
    trMistake: "kacak kaynagini bulmadan yalniz gaz basmaktir",
    deMistake: "nur nachzufuellen, ohne die Leckstelle zu finden",
    keywords: ["gaz eksigi", "refrigerant shortage", "kaeltemittelmangel"],
    suggestions: ["kacak testinde ne kullanilir", "superheat ve subcool birlikte nasil yorumlanir", "sight glass kopuklugu ne anlatir"],
  },
  {
    id: "refrigerant_overcharge",
    trSubject: "fazla gaz var",
    deSubject: "zu viel kaeltemittel im system ist",
    trCause: "asiri sarj, tartimsiz dolum veya subcool mantiginin yanlis yorumlanmasidir",
    deCause: "Ueberfuellung, Fuellung ohne Waage oder falsch interpretierte Subcoolinglogik",
    trChecks: "subcool, receiver dolulugu, basma basinci ve kondenser kullanilan alani degerlendirilir",
    deChecks: "Subcooling, Fuellstand im Receiver, Hochdruck und die aktive Verfluessigerflaeche bewertet werden",
    trWhy: "fazla gaz kondenseri doldurur, basinclari ve kompresor yukunu artirir",
    deWhy: "zu viel Kaeltemittel den Verfluessiger flutet und dadurch Druecke wie Verdichterlast erhoeht",
    trMistake: "tek basina basinca bakip subcool ve sarj metodunu sorgulamamaktir",
    deMistake: "nur auf den Druck zu schauen und Subcooling sowie Fuellmethode nicht zu hinterfragen",
    keywords: ["fazla gaz", "overcharge", "ueberfuellung"],
    suggestions: ["subcool neden onemli", "receiver dolulugu nasil yorumlanir", "yuksek basinc neden olur"],
  },
  {
    id: "filter_drier_blockage",
    trSubject: "filter drier tikaniyor",
    deSubject: "der filtertrockner verstopft",
    trCause: "nem, kir, kaynak artigi veya sistemdeki yanik kalintilaridir",
    deCause: "Feuchtigkeit, Schmutz, Loetrueckstaende oder Verbrennungsreste im System",
    trChecks: "giris-cikis sicaklik farki, basinc dusumu ve sistemin gecmisi birlikte incelenir",
    deChecks: "Ein- und Austrittstemperatur, Druckabfall und Systemhistorie gemeinsam untersucht werden",
    trWhy: "tikali drier akisi bogar ve genlesme organina yeterli sivi gitmesini engeller",
    deWhy: "ein verstopfter Filtertrockner den Durchfluss abwuergt und das Expansionsorgan nicht mehr sauber versorgt",
    trMistake: "drier degistirip sistem temizligini ve vakumu ihmal etmektir",
    deMistake: "nur den Filter zu tauschen und Systemsauberkeit sowie Vakuum zu vernachlaessigen",
    keywords: ["filter drier tikali", "filter blockage", "filtertrockner verstopft"],
    suggestions: ["vakum neden onemli", "nem sisteme nasil zarar verir", "kaynakta azot neden kullanilir"],
  },
  {
    id: "expansion_valve_misfeed",
    trSubject: "genlesme valfi yanlis besliyor",
    deSubject: "das expansionsventil falsch einspritzt",
    trCause: "ampul konumu hatasi, ayar bozuklugu, equalizer sorunu veya valf secim uyumsuzlugudur",
    deCause: "falsche Fuehlerlage, fehlerhafte Einstellung, Equalizerproblem oder eine unpassende Ventilauswahl",
    trChecks: "superheat, ampul sargisi, equalizer baglantisi ve valf kapasitesi kontrol edilir",
    deChecks: "Superheat, Fuehlerbefestigung, Equalizeranschluss und Ventilkapazitaet geprueft werden",
    trWhy: "yanlis besleme evaporatori ya ac birakir ya da siviyla doldurur",
    deWhy: "eine falsche Einspritzung den Verdampfer entweder aushungert oder mit Fluessigkeit ueberschwemmt",
    trMistake: "yalniz vidaya mudahale edip ampul ve equalizer konumunu gormemektir",
    deMistake: "nur an der Einstellschraube zu drehen und Fuehler sowie Equalizerlage nicht zu pruefen",
    keywords: ["genlesme valfi", "txv", "expansionsventil"],
    suggestions: ["superheat nasil ayarlanir", "ampul nereye baglanir", "equalizer ne ise yarar"],
  },
  {
    id: "sensor_wrong_position",
    trSubject: "sensor yeri yanlis",
    deSubject: "der fuehler falsch positioniert ist",
    trCause: "montaj kolayligina gore yerlestirme, hava atisina yakinlik veya urun yukunden kopuk okumadir",
    deCause: "eine nach Montagebequemlichkeit gewaehlte Position, Naehe zum Luftwurf oder Messung fern vom Produktkern",
    trChecks: "sensorun hava akisiyla iliskisi, urune mesafesi ve duvar-serpantin yakinligi kontrol edilir",
    deChecks: "Bezug des Fuehlers zum Luftstrom, Abstand zur Ware und Naehe zu Wand oder Register geprueft werden",
    trWhy: "olcum noktasi yanlissa dogru cihaz bile yanlis karar verir",
    deWhy: "selbst ein guter Regler falsche Entscheidungen trifft, wenn der Messpunkt falsch ist",
    trMistake: "kontrol arizasini sensor geometrisinden ayirmamaktir",
    deMistake: "Reglerfehler und Fuehlergeometrie nicht voneinander zu trennen",
    keywords: ["sensor yanlis yerde", "probe position", "fuehler falsch"],
    suggestions: ["sensor nereye konur", "hava atisi urune vurursa ne olur", "set ve diferans nasil secilir"],
  },
  {
    id: "control_settings_wrong",
    trSubject: "kontrol ayarlari yanlis",
    deSubject: "die reglerwerte falsch eingestellt sind",
    trCause: "set, diferans, defrost araligi, fan gecikmesi veya alarm limitlerinin uygunsuz olmasidir",
    deCause: "ungeeignete Sollwerte, Hysterese, Abtauintervalle, Ventilatorverzoegerung oder Alarmlimits",
    trChecks: "tum parametreler isletme ihtiyaciyla karsilastirilir ve son degisiklik kaydi sorgulanir",
    deChecks: "saemtliche Parameter mit dem Betriebsbedarf verglichen und letzte Aenderungen nachvollzogen werden",
    trWhy: "yanlis parametreler saglam sistemi bile arizali gibi gosterebilir",
    deWhy: "falsche Parameter selbst eine intakte Anlage wie eine Stoerung wirken lassen koennen",
    trMistake: "ne yaptigini kaydetmeden parametre karistirmaktir",
    deMistake: "Parameter ohne Dokumentation zu veraendern",
    keywords: ["ayar yanlis", "controller settings", "regler falsch eingestellt"],
    suggestions: ["defrost araligi nasil secilir", "fan delay ne ise yarar", "alarm limiti nasil belirlenir"],
  },
];

const contexts = [
  {
    id: "vegetable_plus_room",
    trLabel: "sebze muhafaza odasi",
    deLabel: "Gemuese-Kuehlraum",
    trNote: "sebze odalarinda yuksek nem, kasa istifi ve sik kapi hareketi evaporator yukunu hizla buyutur",
    deNote: "in Gemueseraeumen erhoehen hohe Feuchte, Kistenstapelung und haeufige Tueroeffnungen die Verdampferlast schnell",
    trRisk: "bu odalarda hava dagilimi ve defrost duzeni bozulursa urun tazeligi hemen etkilenir",
    deRisk: "in solchen Raeumen wirken sich Stoerungen bei Luftverteilung und Abtauung sehr schnell auf die Frische aus",
    keywords: ["sebze", "gemuese", "plus oda"],
    suggestions: ["sebze odasinda nem nasil yonetilir", "kasa istifi hava akisina nasil etki eder"],
  },
  {
    id: "fruit_room",
    trLabel: "meyve depolama odasi",
    deLabel: "Obst-Kuehlraum",
    trNote: "meyve odalarinda yuksek urun solunumu ve kapidan gelen nem yuku dengeyi bozar",
    deNote: "in Obstraeumen stoeren hohe Produktatmung und Feuchteeintrag ueber die Tuer das Gleichgewicht",
    trRisk: "sicaklik dalgalanmasi meyvede raf omru kaybini hizlandirir",
    deRisk: "Temperaturschwankungen verkuerzen bei Obst sehr schnell die Lagerfaehigkeit",
    keywords: ["meyve", "obst", "fruit room"],
    suggestions: ["meyve odasinda sicaklik neden sabit olmali", "kapi acilisi kaliteyi nasil etkiler"],
  },
  {
    id: "dairy_room",
    trLabel: "sut urunleri odasi",
    deLabel: "Milchprodukte-Kuehlraum",
    trNote: "sut urunlerinde hijyen, stabil sicaklik ve yogun stok devri birlikte yonetilmelidir",
    deNote: "bei Milchprodukten muessen Hygiene, stabile Temperatur und hoher Warenumschlag gemeinsam beherrscht werden",
    trRisk: "kisa sureli sapmalar bile urun guvenligini ve denetim riskini artirir",
    deRisk: "selbst kurze Abweichungen erhoehen Produktsicherheits- und Auditrisiken",
    keywords: ["sut urunleri", "milchprodukte", "dairy room"],
    suggestions: ["sut urunlerinde alarm limiti nasil secilir", "hijyen icin hangi bakim rutini gerekir"],
  },
  {
    id: "meat_room",
    trLabel: "et muhafaza odasi",
    deLabel: "Fleisch-Kuehlraum",
    trNote: "et odalarinda yuksek nem, yuzey korumasi ve duzenli hava dagilimi beraber dusunulmelidir",
    deNote: "in Fleischraeumen muessen hohe Feuchte, Oberflaechenschutz und gleichmaessige Luftverteilung zusammen gedacht werden",
    trRisk: "yanlis hava hizi et yuzeyinde kuruma ve agirlik kaybi yaratir",
    deRisk: "falsche Luftgeschwindigkeiten fuehren an Fleisch zu Austrocknung und Gewichtsverlust",
    keywords: ["et", "fleisch", "meat room"],
    suggestions: ["et odasinda hava hizi neden kritiktir", "nem ayari nasil korunur"],
  },
  {
    id: "fish_room",
    trLabel: "balik odasi",
    deLabel: "Fisch-Kuehlraum",
    trNote: "balik odalarinda agresif nem ve koku yukleri ekipmana daha hizli etki eder",
    deNote: "in Fischraeumen belasten aggressive Feuchte und Gerueche die Technik deutlich schneller",
    trRisk: "hijyen ve drenaj sorunu cok daha cabuk teknik arizaya donusebilir",
    deRisk: "Hygiene- und Ablaufprobleme koennen sich wesentlich schneller in technische Stoerungen verwandeln",
    keywords: ["balik", "fisch", "fish room"],
    suggestions: ["balik odasinda drenaj neden daha kritiktir", "yikama sonrasi ne kontrol edilir"],
  },
  {
    id: "beverage_room",
    trLabel: "icecek depolama odasi",
    deLabel: "Getraenke-Kuehlraum",
    trNote: "icecek odalarinda yogun sirkulasyon ve agir urun yukleri sebebiyle kapi trafigi artar",
    deNote: "in Getraenkeraeumen steigen wegen hoher Umschlaghaeufigkeit und schwerer Lasten die Tuerspiele stark an",
    trRisk: "sik acilis ve stok kaydirma hava dagilimini kolayca bozar",
    deRisk: "haeufiges Oeffnen und Umstapeln stoeren die Luftverteilung schnell",
    keywords: ["icecek", "getraenke", "beverage room"],
    suggestions: ["agir istif hava akisina nasil etki eder", "kapi trafigi nasil azaltilir"],
  },
  {
    id: "flower_room",
    trLabel: "cicek odasi",
    deLabel: "Blumen-Kuehlraum",
    trNote: "cicek odalarinda hassas sicaklik ve dusuk kurutucu hava davranisi istenir",
    deNote: "in Blumenraeumen werden sehr stabile Temperaturen und eine schonende Luftfuehrung erwartet",
    trRisk: "sert hava akisi veya dalgalanma urun gorunumunu hizla bozar",
    deRisk: "harter Luftstrom oder Temperaturschwankung verschlechtert die Optik sehr schnell",
    keywords: ["cicek", "blumen", "flower room"],
    suggestions: ["cicek odasinda hava yonu nasil olmali", "hassas urunlerde sensor nereye konur"],
  },
  {
    id: "bakery_room",
    trLabel: "pastane ve unlu mamul odasi",
    deLabel: "Backwaren-Kuehlraum",
    trNote: "unlu mamullerde nem ve kapi trafigi birlikte calisir, urun yuklemeleri gun icinde degisken olur",
    deNote: "bei Backwaren wirken Feuchte und Tuerspiel gemeinsam, die Beladung aendert sich ueber den Tag stark",
    trRisk: "yanlis ayarlar urunde kuruma ya da yogusma yaratabilir",
    deRisk: "falsche Einstellungen koennen Austrocknung oder Kondensation am Produkt verursachen",
    keywords: ["pastane", "unlu mamul", "backwaren"],
    suggestions: ["urun kurumasini ne arttirir", "gun icinde degisen yukte ayar nasil yapilir"],
  },
  {
    id: "restaurant_prep_room",
    trLabel: "restoran hazirlik odasi",
    deLabel: "Restaurant-Vorbereitungsraum",
    trNote: "mutfak yogunlugunda kapi acma sayisi ve ani yuklemeler cok yuksektir",
    deNote: "im Kuechenbetrieb sind Tueroeffnungen und ploetzliche Lastspruenge sehr haeufig",
    trRisk: "isletme disiplini zayifsa cihaz sorunsuz olsa bile alarm siklasir",
    deRisk: "bei schwacher Betriebsdisziplin haeufen sich Alarme, selbst wenn die Technik intakt ist",
    keywords: ["restoran", "mutfak", "restaurant room"],
    suggestions: ["mutfak odasinda kapi trafigi nasil yonetilir", "ani yuklerde hangi ayarlar kritik"],
  },
  {
    id: "supermarket_backroom",
    trLabel: "market arka depo odasi",
    deLabel: "Supermarkt-Hinterlager",
    trNote: "market depolarinda sevkiyat yogunlugu ve kisa sureli kapak acmalari ardisik olur",
    deNote: "im Supermarkt-Hinterlager folgen Warenbewegungen und kurze Tueroeffnungen direkt aufeinander",
    trRisk: "operasyon temposu hava dengesini kolayca bozar",
    deRisk: "das operative Tempo kann die Luftbilanz sehr schnell stoeren",
    keywords: ["market depo", "supermarkt", "backroom"],
    suggestions: ["sevkiyat saatlerinde sistem nasil korunur", "kisa ama sik kapi acilisi ne yapar"],
  },
  {
    id: "hotel_kitchen_room",
    trLabel: "otel mutfak soguk odasi",
    deLabel: "Hotelkueche-Kuehlraum",
    trNote: "otel mutfaklarinda vardiya duzeni ve duzensiz kullanim pikleri gorulur",
    deNote: "in Hotelkuechen treten schichtbedingte und unregelmaessige Nutzungsspitzen auf",
    trRisk: "gece-gunduz farklari parametre secimini zorlastirir",
    deRisk: "Tag-Nacht-Unterschiede erschweren die saubere Parametrierung",
    keywords: ["otel mutfak", "hotelkueche", "hotel room"],
    suggestions: ["gunluk kullanima gore ayar nasil optimize edilir", "vardiya degisiminde hangi sorunlar gorulur"],
  },
  {
    id: "pharma_room",
    trLabel: "ilac muhafaza odasi",
    deLabel: "Pharma-Kuehlraum",
    trNote: "ilac odalarinda izlenebilirlik, alarm dogrulugu ve dar sicaklik bandi esastir",
    deNote: "in Pharmaraeumen sind Rueckverfolgbarkeit, Alarmgenauigkeit und enge Temperaturfenster entscheidend",
    trRisk: "kucuk sapma bile kalite kaydina ve uyum sorununa donusebilir",
    deRisk: "kleinste Abweichungen koennen zu Qualitaets- und Complianceproblemen fuehren",
    keywords: ["ilac", "pharma", "pharma room"],
    suggestions: ["alarm kayitlari nasil takip edilir", "yedek sensor gerekir mi"],
  },
  {
    id: "laboratory_room",
    trLabel: "laboratuvar soguk odasi",
    deLabel: "Labor-Kuehlraum",
    trNote: "laboratuvar odalarinda yukler duzensiz olabilir ama olcum guvenirligi cok yuksektir",
    deNote: "in Laborraeumen koennen Lasten schwanken, waehrend die Messzuverlaessigkeit extrem hoch sein muss",
    trRisk: "sensor ve alarm dogrulugu burada sistemin kendisi kadar kritiktir",
    deRisk: "Fuehler- und Alarmgenauigkeit sind hier fast so kritisch wie das Kaeltesystem selbst",
    keywords: ["laboratuvar", "labor", "lab cold room"],
    suggestions: ["sensorde kalibrasyon neden onemli", "olcum sapmasi nasil tespit edilir"],
  },
  {
    id: "frozen_food_room",
    trLabel: "donmus urun deposu",
    deLabel: "Tiefkuehlraum",
    trNote: "negatif depolarda buzlanma, kapi rezistansi ve drenaj korumasi hayati onemdedir",
    deNote: "in Tiefkuehlraeumen sind Vereisung, Tuerheizung und Ablaufschutz absolut entscheidend",
    trRisk: "kucuk bir sizinti bile hizla buyuk buzlanmaya donusebilir",
    deRisk: "selbst kleine Leckagen koennen sehr schnell zu massiver Vereisung fuehren",
    keywords: ["donmus urun", "frozen food", "tiefkuehlraum"],
    suggestions: ["negatif depoda defrost nasil secilir", "kapi rezistansi ne ise yarar"],
  },
  {
    id: "shock_room",
    trLabel: "soklama odasi",
    deLabel: "Schockfroster-Raum",
    trNote: "soklama odalari kisa surede cok yuksek isi cekmek zorundadir",
    deNote: "Schockfroster muessen in kurzer Zeit sehr hohe Waermelasten ziehen",
    trRisk: "yanlis kapasite ya da hava dagilimi hemen performans acigina donusur",
    deRisk: "falsche Leistung oder Luftverteilung wird sofort als Performanceproblem sichtbar",
    keywords: ["sok oda", "shock room", "schockfroster"],
    suggestions: ["soklama ile muhafaza farki nedir", "yuksek yukte hangi olcumler onemli"],
  },
  {
    id: "mini_split_room",
    trLabel: "kucuk split soguk oda",
    deLabel: "kleiner Split-Kuehlraum",
    trNote: "kucuk split sistemlerde boru hatasi ve kapasite toleransi daha dar hissedilir",
    deNote: "bei kleinen Splitanlagen fallen Rohrfehler und knappe Leistungsreserven staerker ins Gewicht",
    trRisk: "kucuk kurulum hatasi bile buyuk performans kaybina yol acabilir",
    deRisk: "selbst kleine Montagefehler koennen grosse Leistungsverluste erzeugen",
    keywords: ["split oda", "split kuehlraum", "mini split"],
    suggestions: ["split sistemde boru capi neden onemli", "kucuk odada sensor nereye konur"],
  },
  {
    id: "monoblock_room",
    trLabel: "monoblok soguk oda",
    deLabel: "Monoblock-Kuehlraum",
    trNote: "monoblok cihazlarda hava tarafi ve kondenzasyon kosullari ayni govdede toplanir",
    deNote: "bei Monoblocksystemen liegen Luftseite und Kondensationsbedingungen im selben Geraet zusammen",
    trRisk: "yanlis yerlesim cihazin kendi sicak havasini tekrar emmesine neden olabilir",
    deRisk: "eine schlechte Aufstellung kann Rueckansaugung der eigenen warmen Luft ausloesen",
    keywords: ["monoblok", "monoblock", "kompakt sistem"],
    suggestions: ["monoblok cihaz nereye konur", "geri donen sicak hava ne yapar"],
  },
  {
    id: "remote_condenser_room",
    trLabel: "uzak kondenserli soguk oda",
    deLabel: "Kuehlraum mit Fernverfluessiger",
    trNote: "uzak kondenserde boru uzunlugu, yag donusu ve cevre kosullari beraber degerlendirilmelidir",
    deNote: "bei Fernverfluessigern muessen Rohrlaenge, Oelrueckfuehrung und Umgebungsbedingungen zusammen bewertet werden",
    trRisk: "hat tasarimi zayifsa cihaz atolyede iyi ama sahada kotu calisir",
    deRisk: "bei schwacher Leitungsplanung laeuft die Anlage im Test gut, vor Ort aber schlecht",
    keywords: ["uzak kondenser", "fernverfluessiger", "remote condenser"],
    suggestions: ["uzun emis hattinda neye bakilir", "yag donusu nasil korunur"],
  },
  {
    id: "multi_evaporator_room",
    trLabel: "cok evaporatorlu oda",
    deLabel: "Mehrverdampfer-Raum",
    trNote: "coklu evaporatorlerde dagilim dengesi, valf ayarlari ve sensor referansi zordur",
    deNote: "bei Mehrverdampfersystemen sind Verteilung, Ventileinstellungen und Fuehlerbezug anspruchsvoll",
    trRisk: "bir evaporatorun bozuk davranisi tum odada yalanci semptom yaratabilir",
    deRisk: "ein fehlerhaftes Verhalten eines Verdampfers kann im ganzen Raum irrefuehrende Symptome erzeugen",
    keywords: ["cok evaporator", "mehrverdampfer", "multi evaporator"],
    suggestions: ["cok evaporatorlu sistemde denge nasil kurulur", "her coil icin ayri olcum gerekir mi"],
  },
  {
    id: "single_evaporator_room",
    trLabel: "tek evaporatorlu oda",
    deLabel: "Einzelverdampfer-Raum",
    trNote: "tek evaporatorlu odada tum hava dagilimi tek noktaya baglidir",
    deNote: "im Einzelverdampfer-Raum haengt die gesamte Luftverteilung an einem einzigen Punkt",
    trRisk: "yerlesim veya istif hatasi performansi hemen dusurur",
    deRisk: "Aufstellungs- oder Stapelfehler wirken sich sofort auf die Leistung aus",
    keywords: ["tek evaporator", "einzelverdampfer", "single evaporator"],
    suggestions: ["tek coil ile oda yerlesimi nasil yapilir", "hava atisi nereye bakmali"],
  },
  {
    id: "high_traffic_door_room",
    trLabel: "yuksek kapi trafikli oda",
    deLabel: "Raum mit hohem Tuerspiel",
    trNote: "yuksek kapi trafiginde isi ve nem yukunun buyuk bolumu operasyon kaynaklidir",
    deNote: "bei hohem Tuerspiel stammt ein grosser Teil von Waerme- und Feuchtelast aus dem Betrieb",
    trRisk: "cihaz sorunsuz olsa bile kullanimin kendisi alarm ve buzlanma dogurabilir",
    deRisk: "selbst intakte Technik kann durch die Nutzung Alarme und Vereisung erzeugen",
    keywords: ["kapi trafigi", "door traffic", "tuerspiel"],
    suggestions: ["hava perdesi gerekir mi", "kapi aliskanligi sistemi nasil bozar"],
  },
  {
    id: "sliding_door_room",
    trLabel: "surgu kapili oda",
    deLabel: "Kuehlraum mit Schiebetuer",
    trNote: "surgu kapilarda ray, conta ve kapanma son ayari kritik rol oynar",
    deNote: "bei Schiebetueren spielen Schiene, Dichtung und die Endlage eine kritische Rolle",
    trRisk: "mekanik ayar bozulursa kacak fark edilmeden buyur",
    deRisk: "bei mechanischer Verstellung kann Undichtigkeit lange unbemerkt wachsen",
    keywords: ["surgu kapi", "schiebetuer", "sliding door"],
    suggestions: ["surgu kapida hangi ayarlar kontrol edilir", "ray bozuklugu ne yapar"],
  },
  {
    id: "hinged_door_room",
    trLabel: "menteseli kapili oda",
    deLabel: "Kuehlraum mit Drehtuer",
    trNote: "menteseli kapilarda yay, menteSe ve esik basisi birlikte calisir",
    deNote: "bei Drehtueren wirken Schliesser, Scharniere und Schwellenandruck zusammen",
    trRisk: "kapanma kuvveti dustugunde kacak ve buzlanma hizla artar",
    deRisk: "nimmt die Schliesskraft ab, steigen Leckage und Vereisung schnell an",
    keywords: ["menteseli kapi", "drehtuer", "hinged door"],
    suggestions: ["kapi kapanma kuvveti nasil ayarlanir", "conta basisi nasil kontrol edilir"],
  },
  {
    id: "insulated_floor_room",
    trLabel: "izole zeminli oda",
    deLabel: "Kuehlraum mit isoliertem Boden",
    trNote: "iyi izole zemin genel performansi korur ama lokal su birikimi yine risk yaratabilir",
    deNote: "ein gut isolierter Boden schuetzt die Gesamtperformance, lokale Wasseransammlungen bleiben aber kritisch",
    trRisk: "zemin saglam olsa bile drenaj hatasi buzlanma dogurabilir",
    deRisk: "auch bei gutem Boden kann ein Ablaufproblem Vereisung erzeugen",
    keywords: ["izole zemin", "isolierter boden", "insulated floor"],
    suggestions: ["zemin rezistansi ne zaman gerekir", "su birikimi nasil onlenir"],
  },
  {
    id: "non_insulated_floor_room",
    trLabel: "izolesiz zeminli oda",
    deLabel: "Kuehlraum ohne Bodendaemmung",
    trNote: "izolesiz zeminlerde isi koprusu ve donma problemleri daha kolay gorulur",
    deNote: "bei fehlender Bodendaemmung treten Waermebruecken und Frostprobleme schneller auf",
    trRisk: "zemin kaynakli kayiplar genel sogutma verimini dusurur",
    deRisk: "bodenbedingte Verluste verschlechtern die gesamte Kuehleffizienz",
    keywords: ["izolesiz zemin", "ohne bodendaemmung", "boden problemi"],
    suggestions: ["zemin izolasyonu neden gerekir", "zeminden gelen isi yukune nasil bakilir"],
  },
  {
    id: "high_ceiling_room",
    trLabel: "yuksek tavanli oda",
    deLabel: "Kuehlraum mit hoher Decke",
    trNote: "yuksek tavanda hava tabakalanmasi ve olculen sicaklik farklari artar",
    deNote: "bei hohen Decken nehmen Luftschichtung und Temperaturunterschiede zu",
    trRisk: "yanlis sensor veya fan yerlesimi asagi-yukari farki buyutur",
    deRisk: "falsche Fuehler- oder Ventilatorplatzierung vergroessert die Unterschiede zwischen oben und unten",
    keywords: ["yuksek tavan", "hohe decke", "high ceiling"],
    suggestions: ["yuksek odada sensor nereye konur", "hava tabakalanmasi nasil azaltilir"],
  },
  {
    id: "low_ceiling_room",
    trLabel: "alcak tavanli oda",
    deLabel: "Kuehlraum mit niedriger Decke",
    trNote: "alcak tavanli odalarda hava devresi kisa oldugu icin lokal vurma riskleri artar",
    deNote: "bei niedrigen Decken steigt wegen kurzer Luftwege das Risiko lokaler Anblasung",
    trRisk: "urun donmasi veya sensor sapmasi daha cabuk gorulebilir",
    deRisk: "Produktanfrieren oder Fuehlerverfaelschung treten schneller auf",
    keywords: ["alcak tavan", "niedrige decke", "low ceiling"],
    suggestions: ["hava atisi urune vurmamasi icin ne yapilir", "fan hizi nasil secilir"],
  },
  {
    id: "loading_dock_room",
    trLabel: "sevkiyat baglantili oda",
    deLabel: "Kuehlraum am Verladebereich",
    trNote: "sevkiyat baglantili odada kapi kullanim pikleri ve dis ortam etkisi cok yuksektir",
    deNote: "im verladenahen Kuehlraum sind Tuerspitzen und Umgebungseinfluesse sehr hoch",
    trRisk: "kisa surede fazla nem ve isi tasinabilir",
    deRisk: "in kurzer Zeit koennen grosse Mengen an Waerme und Feuchte eingetragen werden",
    keywords: ["sevkiyat", "verladebereich", "loading dock"],
    suggestions: ["sevkiyat saatlerinde hangi alarmlar normal degildir", "hava perdesi gerekir mi"],
  },
  {
    id: "dusty_condenser_area",
    trLabel: "tozlu kondenser ortami",
    deLabel: "staubige Verfluessiger-Umgebung",
    trNote: "tozlu bolgelerde kondenser kirlenmesi standarttan cok daha hizlidir",
    deNote: "in staubiger Umgebung verschmutzen Verfluessiger deutlich schneller als normal",
    trRisk: "bakim periyodu uzarsa basinclar ve enerji tuketimi hizla artar",
    deRisk: "bei zu langen Wartungsintervallen steigen Druecke und Energieverbrauch schnell an",
    keywords: ["tozlu ortam", "dusty condenser", "staubig"],
    suggestions: ["bakim periyodu nasil siklastirilir", "kondenser temizligi nasil yapilir"],
  },
  {
    id: "rooftop_condenser",
    trLabel: "cati ustu kondenserli sistem",
    deLabel: "Anlage mit Dachverfluessiger",
    trNote: "cati ustunde gunes, ruzgar ve servis erisimi birlikte sorun yaratabilir",
    deNote: "auf dem Dach koennen Sonne, Wind und erschwerte Erreichbarkeit gemeinsam Probleme erzeugen",
    trRisk: "yaz ve kis kosullari arasindaki farklar cok sert yasanir",
    deRisk: "die Unterschiede zwischen Sommer- und Winterbetrieb sind besonders stark",
    keywords: ["cati ustu", "dachverfluessiger", "rooftop condenser"],
    suggestions: ["gunes etkisi kondenzasyonu nasil bozar", "kis calismasinda ne degisir"],
  },
  {
    id: "basement_installation",
    trLabel: "bodrum kurulumlu sistem",
    deLabel: "im Keller installierte Anlage",
    trNote: "bodrumda hava sirkulasyonu zayif ve servis alani sinirli olabilir",
    deNote: "im Keller kann die Luftzirkulation schwach und der Servicezugang begrenzt sein",
    trRisk: "sicak hava tahliyesi kotuyse basinclar beklenmedik sekilde yukselir",
    deRisk: "bei schlechter Warmluftabfuhr steigen Druecke unerwartet an",
    keywords: ["bodrum kurulum", "keller", "basement installation"],
    suggestions: ["kapali mahalde kondenser nasil yerlestirilir", "hava geri donusu nasil anlasilir"],
  },
  {
    id: "outdoor_condenser_in_sun",
    trLabel: "gunes altindaki dis unite sistemi",
    deLabel: "Anlage mit sonnenseitigem Aussengeraet",
    trNote: "dogrudan gunes alan unitede yogun saatlerde basinclar zirveye cikabilir",
    deNote: "bei direkter Sonneneinstrahlung koennen die Druecke in Spitzenzeiten stark ansteigen",
    trRisk: "sadece oglen saatlerinde gorulen arizalar kullaniciyi sasirtir",
    deRisk: "nur mittags auftretende Stoerungen fuehren oft in die Irre",
    keywords: ["gunes", "sun exposure", "aussengeraet sonne"],
    suggestions: ["sicak havada neden daha cok alarm olur", "gunes golgelemesi gerekir mi"],
  },
  {
    id: "outdoor_condenser_in_winter",
    trLabel: "kis kosullarinda calisan dis unite sistemi",
    deLabel: "Aussengeraet im Winterbetrieb",
    trNote: "kis dusuk ambient kosullarinda basinclar ve valf davranisi tamamen degisebilir",
    deNote: "bei niedrigem Winterambient aendern sich Druecke und Ventilverhalten deutlich",
    trRisk: "head pressure kontrolu yoksa besleme dengesizlesir",
    deRisk: "ohne Head-Pressure-Regelung wird die Einspeisung instabil",
    keywords: ["kis calisma", "winterbetrieb", "low ambient"],
    suggestions: ["head pressure kontrolu neden gerekir", "kis sartlarinda fan kontrolu nasil olur"],
  },
  {
    id: "long_pipe_run",
    trLabel: "uzun boru hatli sistem",
    deLabel: "Anlage mit langer Rohrstrecke",
    trNote: "uzun boru hatlarinda yag donusu, basinc kaybi ve sarj miktari hassastir",
    deNote: "bei langen Rohrstrecken sind Oelrueckfuehrung, Druckverlust und Fuellmenge besonders sensibel",
    trRisk: "tezgahta iyi gorunen sistem sahada dengesiz davranabilir",
    deRisk: "eine auf dem Papier gute Anlage kann vor Ort instabil reagieren",
    keywords: ["uzun hat", "lange rohrstrecke", "long pipe run"],
    suggestions: ["uzun hatta sarj nasil hesaplanir", "oel tuzagi ne zaman gerekir"],
  },
  {
    id: "short_pipe_run",
    trLabel: "kisa boru hatli sistem",
    deLabel: "Anlage mit kurzer Rohrstrecke",
    trNote: "kisa hatlarda bile yanlis cap ya da kotu montaj davranisi sorun yaratabilir",
    deNote: "selbst bei kurzen Leitungen koennen falscher Durchmesser oder schlechte Montage Probleme verursachen",
    trRisk: "usta bazen hat kisa diye boru disiplinini gereksiz gorur",
    deRisk: "oft wird Rohrdisziplin vernachlaessigt, nur weil die Leitung kurz ist",
    keywords: ["kisa hat", "kurze rohrstrecke", "short pipe run"],
    suggestions: ["kisa hatta da superheat neden onemli", "boru capi neye gore secilir"],
  },
  {
    id: "after_power_cut",
    trLabel: "elektrik kesintisi sonrasi sistem",
    deLabel: "Anlage nach Stromausfall",
    trNote: "elektrik kesintisinden sonra basinclar esitleme, alarm hafizasi ve gecikmeler birlikte okunmalidir",
    deNote: "nach Stromausfall muessen Druckausgleich, Alarmhistorie und Wiederanlaufverzoegerungen gemeinsam betrachtet werden",
    trRisk: "enerji geldikten hemen sonraki semptomlar kok sebebi maskeleyebilir",
    deRisk: "Symptome direkt nach dem Wiedereinschalten koennen die eigentliche Ursache verdecken",
    keywords: ["elektrik kesintisi", "stromausfall", "after power cut"],
    suggestions: ["yeniden devreye almada ne kontrol edilir", "kisa devre calisma nasil onlenir"],
  },
  {
    id: "after_maintenance",
    trLabel: "bakim sonrasi sistem",
    deLabel: "Anlage nach Wartung",
    trNote: "bakimdan sonra soket, parametre ve servis vanasi kontrolleri unutulursa yeni hata dogar",
    deNote: "nach Wartung entstehen neue Fehler, wenn Stecker, Parameter und Serviceventile nicht sauber kontrolliert werden",
    trRisk: "sistem arizali degilken bakim kaynakli insan hatasi ortaya cikabilir",
    deRisk: "es kann eher ein servicebedingter Bedienfehler als ein echter Anlagendefekt vorliegen",
    keywords: ["bakim sonrasi", "nach wartung", "after maintenance"],
    suggestions: ["bakim sonrasi checklist ne olmali", "servis vanasi acik mi nasil anlasilir"],
  },
  {
    id: "after_gas_charge",
    trLabel: "gaz sarji sonrasi sistem",
    deLabel: "Anlage nach Kaeltemittelfuellung",
    trNote: "sarj sonrasi sistem davranisi ancak basinclar ve superheat-subcool birlikte okunursa anlamlidir",
    deNote: "nach einer Fuellung ist das Verhalten nur aussagekraeftig, wenn Druecke sowie Superheat und Subcool gemeinsam gelesen werden",
    trRisk: "yanlis yorumlanan sarj sonrasi veri yeni hatali mudahaleye yol acar",
    deRisk: "falsch interpretierte Messwerte nach der Fuellung fuehren zu weiteren Fehlgriffen",
    keywords: ["sarj sonrasi", "nach fuellung", "after gas charge"],
    suggestions: ["sarj dogru nasil dogrulanir", "superheat ve subcool beraber nasil okunur"],
  },
  {
    id: "after_defrost_service",
    trLabel: "defrost mudahalesi sonrasi sistem",
    deLabel: "Anlage nach Abtau-Service",
    trNote: "defrost uzerinde calisma yapildiktan sonra rezistans, sensor ve zaman mantigi birlikte dogrulanmalidir",
    deNote: "nach Arbeiten an der Abtauung muessen Heizung, Fuehler und Zeitlogik gemeinsam verifiziert werden",
    trRisk: "tek bir parametre duzelse bile senkron bozuk kalabilir",
    deRisk: "selbst wenn ein Einzelwert stimmt, kann die Gesamtabfolge noch falsch sein",
    keywords: ["defrost servis", "abtau service", "after defrost service"],
    suggestions: ["defrost testi nasil yapilir", "sonlandirma sensori nasil kontrol edilir"],
  },
  {
    id: "humid_region",
    trLabel: "nemli bolgedeki soguk oda",
    deLabel: "Kuehlraum in feuchter Region",
    trNote: "yuksek cevre nemi kapilar, panel birlesimleri ve defrost yukunu buyutur",
    deNote: "hohe Umgebungsfeuchte erhoeht die Belastung auf Tueren, Paneelstosse und Abtauung",
    trRisk: "normal gorunen kacaklar bu kosulda hizla buyuk semptom verir",
    deRisk: "kleine Leckagen werden unter diesen Bedingungen sehr schnell zu grossen Symptomen",
    keywords: ["nemli bolge", "humid region", "hohe feuchte"],
    suggestions: ["ciy noktasi neden onemli", "nemli iklimde kapi nasil korunur"],
  },
  {
    id: "dry_region",
    trLabel: "kuru iklimdeki soguk oda",
    deLabel: "Kuehlraum in trockener Region",
    trNote: "kuru iklimlerde nemden cok urun kurumasi ve hava vurusu problemi one cikar",
    deNote: "in trockenen Regionen stehen eher Produktaustrocknung und Luftwurfprobleme im Vordergrund",
    trRisk: "sicaklik dogru olsa bile kalite kaybi sik gorulebilir",
    deRisk: "auch bei korrekter Temperatur kann die Produktqualitaet leiden",
    keywords: ["kuru iklim", "dry region", "trockene region"],
    suggestions: ["urun kurumasini ne azaltir", "hava hizi neden kritik olur"],
  },
  {
    id: "washdown_room",
    trLabel: "sik yikanan oda",
    deLabel: "haeufig gewaschener Kuehlraum",
    trNote: "sik yikanan odalarda su girisi, korozyon ve drenaj yukleri dikkat ister",
    deNote: "in haeufig gewaschenen Raeumen muessen Wassereintritt, Korrosion und Ablaufbelastung stark beachtet werden",
    trRisk: "yanlis yikama rutini elektrik ve fan arizasini tetikler",
    deRisk: "falsche Reinigungsroutinen loesen schnell Elektro- und Ventilatorprobleme aus",
    keywords: ["sik yikama", "washdown", "haeufige reinigung"],
    suggestions: ["yikama sonrasi ilk kontrol ne olmali", "su girisi hangi arizalari yapar"],
  },
  {
    id: "summer_peak_room",
    trLabel: "yaz pik yukundeki sistem",
    deLabel: "Anlage unter Sommer-Spitzenlast",
    trNote: "yaz piklerinde normalde gizli kalan kapasite ve hava tarafi zayifliklari ortaya cikar",
    deNote: "unter Sommer-Spitzenlast werden versteckte Leistungs- und Luftseitenschwaechen sichtbar",
    trRisk: "kis testinde sorunsuz olan sistem yazin alarm verebilir",
    deRisk: "eine im Winter unauffaellige Anlage kann im Sommer stoeren",
    keywords: ["yaz piki", "sommerlast", "summer peak"],
    suggestions: ["sicak havada basinclar nasil yorumlanir", "yaz oncesi hangi bakim yapilir"],
  },
  {
    id: "winter_low_load_room",
    trLabel: "kis dusuk yukteki sistem",
    deLabel: "Anlage unter Winter-Teillast",
    trNote: "dusuk yukte head pressure, valf beslemesi ve kisa devre calisma on plana cikar",
    deNote: "unter Winter-Teillast ruecken Head-Pressure, Ventilversorgung und Kurzzyklus in den Vordergrund",
    trRisk: "normal yukte gozukmeyen besleme sorunlari burada belirginlesir",
    deRisk: "Versorgungsprobleme, die bei Normallast verborgen bleiben, werden hier deutlich sichtbar",
    keywords: ["kis dusuk yuk", "winter low load", "teillast"],
    suggestions: ["head pressure duserse ne olur", "kisa devre calisma neden olur"],
  },
  {
    id: "r290_compact_system",
    trLabel: "R290 kompakt sistem",
    deLabel: "R290-Kompaktanlage",
    trNote: "R290 sistemlerde sarj miktari, guvenlik ve kompakt hava yolu daha hassastir",
    deNote: "bei R290-Anlagen sind Fuellmenge, Sicherheit und kompakte Luftfuehrung besonders sensibel",
    trRisk: "yanlis servis aliskanligi performans ve guvenlik riski dogurur",
    deRisk: "falsche Servicegewohnheiten fuehren zu Leistungs- und Sicherheitsrisiken",
    keywords: ["r290", "propan", "kompakt sistem"],
    suggestions: ["R290 sistemde nelere dikkat edilir", "kucuk sarj degisimi neden onemli"],
  },
  {
    id: "r404a_legacy_system",
    trLabel: "R404A eski nesil sistem",
    deLabel: "aeltere R404A-Anlage",
    trNote: "eski sistemlerde kir, yipranma ve gecmis servis mudahaleleri bugunku semptomu etkiler",
    deNote: "bei aelteren Anlagen beeinflussen Verschmutzung, Verschleiss und fruehere Serviceeingriffe das heutige Fehlerbild",
    trRisk: "tek ariza yerine biriken kucuk bozukluklar birlikte calisir",
    deRisk: "oft wirkt nicht ein Fehler allein, sondern mehrere kleine Schwaechen zusammen",
    keywords: ["r404a", "legacy", "eski sistem"],
    suggestions: ["eski sistemde hangi parcaya once bakilir", "servis gecmisi neden onemli"],
  },
  {
    id: "r448a_retrofit_system",
    trLabel: "R448A retrofit sistem",
    deLabel: "R448A-Retrofitanlage",
    trNote: "retrofit sistemlerde valf ayari, etiketleme ve yeni calisma noktalari dogru okunmalidir",
    deNote: "bei Retrofitanlagen muessen Ventileinstellung, Kennzeichnung und neue Betriebspunkte sauber gelesen werden",
    trRisk: "eski gaz mantigiyla yeni gazi yorumlamak yanlis teshise goturur",
    deRisk: "das neue Kaeltemittel mit alter Denkweise zu bewerten fuehrt schnell zu Fehlinterpretationen",
    keywords: ["r448a", "retrofit", "umru degisen gaz"],
    suggestions: ["retrofit sonrasi hangi olcumler gerekir", "PT tablosu neden degisir"],
  },
  {
    id: "electronic_controller_room",
    trLabel: "elektronik kontrollu oda",
    deLabel: "elektronisch geregelter Kuehlraum",
    trNote: "elektronik panellerde parametre, sensor ve alarm hafizasi teshiste birlikte okunur",
    deNote: "bei elektronischer Regelung muessen Parameter, Fuehler und Alarmhistorie gemeinsam gelesen werden",
    trRisk: "yalniz ekrandaki hataya bakmak eksik tanidir",
    deRisk: "nur auf die Displaymeldung zu schauen, fuehrt oft zu unvollstaendiger Diagnose",
    keywords: ["elektronik kontrol", "controller", "elektronische regelung"],
    suggestions: ["alarm hafizasi nasil okunur", "parametre degisikligi nasil takip edilir"],
  },
  {
    id: "mechanical_thermostat_room",
    trLabel: "mekanik termostatli oda",
    deLabel: "Kuehlraum mit mechanischem Thermostat",
    trNote: "mekanik kontrolde sensor yerine kapiler ve kontak davranisi daha cok onem kazanir",
    deNote: "bei mechanischer Regelung stehen Kapillarverlauf und Kontaktverhalten staerker im Fokus",
    trRisk: "kullanim farklari elektronik sistem kadar net kayit birakmaz",
    deRisk: "Nutzungsunterschiede hinterlassen hier weniger klare Daten als in elektronischen Anlagen",
    keywords: ["mekanik termostat", "mechanischer thermostat", "mechanical control"],
    suggestions: ["mekanik termostat nasil test edilir", "kapiler hasari nasil anlasilir"],
  },
  {
    id: "container_cold_room",
    trLabel: "konteyner tip soguk oda",
    deLabel: "Container-Kuehlraum",
    trNote: "konteyner yapisinda gunes, tasinma titresimi ve sinirli hava hacmi etkisi buyuktur",
    deNote: "bei Containerloesungen wirken Sonneneinstrahlung, Transportvibration und begrenztes Luftvolumen stark",
    trRisk: "yer degisimi ve dis ortam etkisi klasik odalara gore daha cok degisir",
    deRisk: "Standortwechsel und Umgebungsbedingungen variieren staerker als bei festen Raeumen",
    keywords: ["konteyner", "container", "mobil oda"],
    suggestions: ["tasinabilir odada hangi kontroller siklasir", "titreSim borulari nasil etkiler"],
  },
];

function ensureArraySize(name, values, expected) {
  if (values.length !== expected) {
    throw new Error(`${name} expected ${expected} entries, got ${values.length}`);
  }
}

function buildAnswerTr(context, family) {
  return `${context.trLabel} icin ${family.trSubject} goruldugunde usta once semptomu isletme senaryosundan ayirir. Bu senaryoda tipik kok nedenler ${family.trCause}. ${context.trNote}. Ilk teshiste ${family.trChecks}. Bunun teknik sebebi ${family.trWhy}; ${context.trRisk}. En sik hata ${family.trMistake}. Saglam ariza tespiti once gozlem, sonra olcum, sonra ayar veya parca kararidir.`;
}

function buildAnswerDe(context, family) {
  return `Wenn im ${context.deLabel} ${family.deSubject}, trennt ein Meister zuerst das Symptom sauber vom Betriebsszenario. Typische Grundursachen sind ${family.deCause}. ${context.deNote}. In der Erstdiagnose sollten ${family.deChecks}. Der technische Hintergrund ist, dass ${family.deWhy}; ${context.deRisk}. Ein haeufiger Fehler ist ${family.deMistake}. Saubere Fehlersuche bedeutet erst beobachten, dann messen und erst danach ueber Einstellung oder Bauteiltausch entscheiden.`;
}

function uniq(values) {
  return [...new Set(values.filter(Boolean))];
}

function buildEntry(context, family, index) {
  return {
    id: `drc25k_${String(index + 1).padStart(4, "0")}_${context.id}_${family.id}`,
    context_id: context.id,
    family_id: family.id,
    source_summary: SOURCE_SUMMARY,
    tr_subject: `${context.trLabel} icin ${family.trSubject}`,
    de_subject: `${context.deLabel}: ${family.deSubject}`,
    keywords: uniq([
      ...context.keywords,
      ...family.keywords,
      context.trLabel,
      context.deLabel,
      family.trSubject,
      family.deSubject,
    ]),
    tr_questions: trQuestionTemplates.map((template) => template(context, family)),
    de_questions: deQuestionTemplates.map((template) => template(context, family)),
    tr_answer: buildAnswerTr(context, family),
    de_answer: buildAnswerDe(context, family),
    suggestions: uniq([...family.suggestions, ...context.suggestions]).slice(0, 4),
  };
}

function buildSummary(entries) {
  const byContext = {};
  const byFamily = {};

  entries.forEach((entry) => {
    byContext[entry.context_id] = (byContext[entry.context_id] || 0) + 1;
    byFamily[entry.family_id] = (byFamily[entry.family_id] || 0) + 1;
  });

  return {
    sourceSummary: SOURCE_SUMMARY,
    outputFile: OUTPUT_PATH,
    totalEntries: entries.length,
    totalFamilies: faultFamilies.length,
    totalContexts: contexts.length,
    questionsPerEntry: 20,
    totalQuestionCount: entries.reduce(
      (sum, entry) => sum + entry.tr_questions.length + entry.de_questions.length,
      0
    ),
    breakdown: {
      byContext,
      byFamily,
    },
  };
}

function writeMarkdown(entries, summary) {
  const lines = [
    "# DRC MAN 25K Ariza Tespit Bankasi",
    "",
    `Toplam konu karti: ${summary.totalEntries}`,
    `Toplam soru: ${summary.totalQuestionCount}`,
    `Kontekst sayisi: ${summary.totalContexts}`,
    `Ariza ailesi sayisi: ${summary.totalFamilies}`,
    "",
    "## Ornek kartlar",
    "",
  ];

  entries.slice(0, 20).forEach((entry, index) => {
    lines.push(`### ${index + 1}. ${entry.tr_subject}`);
    lines.push("");
    lines.push(`- DE konu: ${entry.de_subject}`);
    lines.push(`- Ornek TR soru: ${entry.tr_questions[0]}`);
    lines.push(`- Ornek DE soru: ${entry.de_questions[0]}`);
    lines.push(`- Oneriler: ${entry.suggestions.join(", ")}`);
    lines.push("");
  });

  fs.writeFileSync(MARKDOWN_PATH, `${lines.join("\n")}\n`, "utf8");
}

function main() {
  ensureArraySize("faultFamilies", faultFamilies, 25);
  ensureArraySize("contexts", contexts, 50);

  const entries = [];
  contexts.forEach((context) => {
    faultFamilies.forEach((family) => {
      entries.push(buildEntry(context, family, entries.length));
    });
  });

  const totalQuestionCount = entries.reduce(
    (sum, entry) => sum + entry.tr_questions.length + entry.de_questions.length,
    0
  );

  if (entries.length !== 1250) {
    throw new Error(`Expected 1250 entries, got ${entries.length}`);
  }

  if (totalQuestionCount !== 25000) {
    throw new Error(`Expected 25000 questions, got ${totalQuestionCount}`);
  }

  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  fs.writeFileSync(OUTPUT_PATH, JSON.stringify(entries, null, 2), "utf8");

  const summary = buildSummary(entries);
  fs.writeFileSync(SUMMARY_PATH, JSON.stringify(summary, null, 2), "utf8");
  writeMarkdown(entries, summary);

  console.log(
    JSON.stringify(
      {
        outputFile: OUTPUT_PATH,
        summaryFile: SUMMARY_PATH,
        markdownFile: MARKDOWN_PATH,
        totalEntries: entries.length,
        totalQuestionCount,
      },
      null,
      2
    )
  );
}

main();
