const fs = require("fs");
const path = require("path");

const OUTPUT = path.join(__dirname, "drc_man_troubleshooting_faq.json");
const SOURCE_SUMMARY = "DRC MAN soguk oda ariza ustasi egitimi";

const trTemplates = [
  (s) => `${s} neden olur`,
  (s) => `${s} olursa neye bakilir`,
  (s) => `${s} varsa sorun nerede olabilir`,
  (s) => `${s} durumunda usta once ne kontrol eder`,
  (s) => `${s} arizasinda nasil teshis yapilir`,
  (s) => `${s} sorunu nasil cozulur`,
  (s) => `${s} neden tekrar eder`,
  (s) => `${s} oldugunda hangi parcaya bakilir`,
  (s) => `${s} oldugunda montaj hatasi olabilir mi`,
  (s) => `${s} gorulurse servis sirasi ne olur`,
];

const deTemplates = [
  (s) => `warum tritt ${s} auf`,
  (s) => `worauf schaut man wenn ${s} auftritt`,
  (s) => `wo kann der fehler liegen wenn ${s} da ist`,
  (s) => `was prueft ein meister zuerst wenn ${s} auftritt`,
  (s) => `wie diagnostiziert man ${s}`,
  (s) => `wie loest man ${s}`,
  (s) => `warum kommt ${s} immer wieder`,
  (s) => `welches bauteil prueft man bei ${s}`,
  (s) => `kann montagefehler ${s} verursachen`,
  (s) => `wie ist die service reihenfolge bei ${s}`,
];

function buildAnswerTr(topic) {
  return `${topic.trSubject} durumunda usta once semptomu dogru okur, sonra sebebi daraltir. En yaygin nedenler ${topic.causeTr}. Ilk kontrolde ${topic.checkTr}. Bunun sebebi ${topic.whyTr}. En sik hata ise ${topic.mistakeTr}. Usta mantigi parca degistirmekten once olayi olcu, gozlem ve is akisiyla dogrulamaktir.`;
}

function buildAnswerDe(topic) {
  return `Wenn ${topic.deSubject} auftritt, liest ein Meister zuerst das Symptom sauber und grenzt dann die Ursache ein. Die haeufigsten Gruende sind ${topic.causeDe}. Bei der Erstpruefung werden ${topic.checkDe}. Der technische Hintergrund ist ${topic.whyDe}. Ein sehr haeufiger Fehler besteht darin, dass ${topic.mistakeDe}. Meisterliches Arbeiten bedeutet hier, nicht sofort Teile zu tauschen, sondern Messwerte, Beobachtung und Ablauf logisch zusammenzufuehren.`;
}

function buildEntry(topic) {
  return {
    id: topic.id,
    source_summary: SOURCE_SUMMARY,
    tr_subject: topic.trSubject,
    de_subject: topic.deSubject,
    keywords: topic.keywords,
    tr_questions: trTemplates.map((template) => template(topic.trSubject)),
    de_questions: deTemplates.map((template) => template(topic.deSubject)),
    tr_answer: buildAnswerTr(topic),
    de_answer: buildAnswerDe(topic),
    suggestions: topic.suggestions,
  };
}

const allTopics = [
  {
    id: "problem_room_not_cooling",
    trSubject: "oda yeterince sogutmuyor",
    deSubject: "der raum nicht ausreichend kuehlt",
    keywords: ["sogutmuyor", "oda sicak", "room not cooling", "kuehlt nicht"],
    causeTr: "yanlis kapasite secimi, kirli kondenser, buzlu evaporator, gaz eksigi veya hava sirkulasyonunun bozulmasidir",
    causeDe: "falsche Leistungswahl, verschmutzter Verfluessiger, vereister Verdampfer, Kaeltemittelmangel oder gestoerte Luftzirkulation",
    checkTr: "kapi kapanisi, oda yuk durumu, basma-emis degerleri, fan donusu ve serpantinlerin durumu sirayla incelenir",
    checkDe: "Tuerzustand, Lastsituation, Hoch- und Niederdruck, Ventilatorlauf und Zustand der Register der Reihe nach geprueft",
    whyTr: "sogutma problemi cogu zaman tek parcadan degil, hava tarafi ve gaz devresinin birlikte bozulmasindan cikar",
    whyDe: "Kuehlprobleme meist nicht von einem einzigen Bauteil kommen, sondern aus einer Kombination von Luftseite und Kaeltekreis entstehen",
    mistakeTr: "hemen gaz basmak veya kontrolsuz parca degistirmek sorunu buyutebilir",
    mistakeDe: "sofort Kaeltemittel nachzufuellen oder blind Teile zu tauschen das Problem vergroessern kann",
    suggestions: ["yuksek basinc neden olur", "evaporator neden buz tutar", "kapasite secimi nasil yapilir"],
  },
  {
    id: "problem_room_cools_slow",
    trSubject: "oda gec soguyor",
    deSubject: "der raum spaet herunterkuehlt",
    keywords: ["gec soguyor", "slow cooling", "langsam kuehlen"],
    causeTr: "urun yukunun fazla olmasi, kapinin sik acilmasi, hava devrinin yetersiz kalmasi veya cihazin sinirda secilmesidir",
    causeDe: "zu hohe Warenlast, haeufige Tueroeffnungen, zu schwache Luftumwaelzung oder eine grenzwertige Geraeteauswahl",
    checkTr: "urun giris sicakligi, gunluk mal yukleme miktari, fan hava atisi ve oda icindeki istif duzeni kontrol edilir",
    checkDe: "Eintrittstemperatur der Ware, taeglicher Wareneintrag, Luftwurf der Ventilatoren und die Stapelung im Raum geprueft",
    whyTr: "oda sicakligi sadece cihaz gucuyle degil, iceriye tasinan isiyle de belirlenir",
    whyDe: "die Raumabkuehlung nicht nur von der Geraeteleistung, sondern auch von der eingetragenen Waerme bestimmt wird",
    mistakeTr: "kapi trafigi ve yukleme aliskanligini hesaba katmadan arizayi cihaza baglamaktir",
    mistakeDe: "man Tueroeffnungen und Beladegewohnheiten ignoriert und den Fehler nur beim Geraet sucht",
    suggestions: ["soguk oda yuk hesabi nasil yapilir", "hava sirkulasyonu neden onemli", "muhafaza odasi ile sok oda farki nedir"],
  },
  {
    id: "problem_temperature_unstable",
    trSubject: "oda sicakligi sabit kalmiyor",
    deSubject: "die raumtemperatur instabil ist",
    keywords: ["sicaklik dalgalaniyor", "instabil", "temperature unstable"],
    causeTr: "sensor yerinin yanlis olmasi, on-off farkinin kotu ayarlanmasi, kapi trafigi veya kisa devre calismanin olusmasidir",
    causeDe: "falsch gesetzter Fuehler, schlecht eingestellte Regelhysterese, Tuerspiel oder Kurzzyklusverhalten",
    checkTr: "sensor konumu, set ve diferans ayari, fanin urune vurusu ve kompresorun start-stop sayisi kontrol edilir",
    checkDe: "Fuehlerposition, Sollwert und Differenz, Luftanblasung auf die Ware und Anzahl der Verdichterstarts geprueft",
    whyTr: "kontrol elemani yanlis bilgi gorurse sistem gercek oda ihtiyacina gore degil, yanlis referansa gore calisir",
    whyDe: "die Regelung bei falscher Messinformation nicht nach dem realen Raum, sondern nach einem falschen Bezugspunkt arbeitet",
    mistakeTr: "hemen termostati degistirip sensor yerini ve kullanim senaryosunu atlamaktir",
    mistakeDe: "man sofort den Regler tauscht und Fuehlerposition sowie Nutzungsszenario uebersieht",
    suggestions: ["sensor nereye konur", "kisa devre calisma neden olur", "oda neden dengesiz sogur"],
  },
  {
    id: "problem_compressor_not_starting",
    trSubject: "kompresor calismiyor",
    deSubject: "der verdichter nicht startet",
    keywords: ["kompresor calismiyor", "compressor not starting", "verdichter startet nicht"],
    causeTr: "enerji eksigi, kontaktor-termik problemi, basinç emniyeti, faz koruma veya kontrol emrinin gelmemesidir",
    causeDe: "Spannungsproblem, Schuetz- oder Motorschutzfehler, Drucksicherheit, Phasenueberwachung oder fehlende Regelanforderung",
    checkTr: "faz varligi, kontaktor cekmesi, termik atik mi, basinç switchleri acik mi ve kontrol karti cikisi var mi diye bakilir",
    checkDe: "Phasenversorgung, Schuetzfunktion, Motorschutzstatus, Druckschalter und Reglerausgang geprueft",
    whyTr: "kompresorun calismamasi mekanik ariza kadar elektriksel koruma kaynakli da olabilir",
    whyDe: "ein stillstehender Verdichter genauso oft von elektrischer Schutzlogik wie von mechanischen Ursachen kommen kann",
    mistakeTr: "kompresoru arizali sanip once motoru suclamaktir",
    mistakeDe: "man den Verdichter vorschnell als defekt einstuft und zuerst den Motor verdaechtigt",
    suggestions: ["faz sirasi neden onemli", "termik neden atar", "basinc switch neden acilir"],
  },
  {
    id: "problem_compressor_trips_thermal",
    trSubject: "kompresor termige dusuyor",
    deSubject: "der verdichter auf motorschutz geht",
    keywords: ["termik atiyor", "overload", "motorschutz"],
    causeTr: "yuksek akim, zayif sogutma, yuksek basinc, dusuk voltaj veya mekanik zorlanmadir",
    causeDe: "hohe Stromaufnahme, schlechte Kuehlung, Hochdruck, Unterspannung oder mechanische Ueberlastung",
    checkTr: "akim olculur, fanlar ve kondenser temizligi bakilir, basinc degerleri okunur ve voltaj dusumu kontrol edilir",
    checkDe: "Strom wird gemessen, Verfluessiger und Ventilatoren werden geprueft, Druckwerte gelesen und Spannungsabfall kontrolliert",
    whyTr: "termik sadece elektrik sorunu degil, kompresorun zorlandigini gosteren koruma tepkisidir",
    whyDe: "der Motorschutz nicht nur ein Elektrikproblem, sondern ein Hinweis auf Ueberlastung des Verdichters ist",
    mistakeTr: "termigi buyutmek veya resetleyip sebebi aramadan tekrar calistirmaktir",
    mistakeDe: "den Schutz groesser auszulegen oder nur zu resetten, ohne die Ursache zu suchen",
    suggestions: ["yuksek basinc neden olur", "voltaj dusuk olursa ne olur", "kondenser temizligi neden onemli"],
  },
  {
    id: "problem_high_pressure",
    trSubject: "yuksek basinc arizasi olusuyor",
    deSubject: "eine hochdruck stoerung auftritt",
    keywords: ["yuksek basinc", "high pressure", "hochdruck"],
    causeTr: "kirli kondenser, fan arizasi, hava sirkulasyonunun geri donmesi, fazla gaz veya cevre sicakliginin asiri yuksek olmasidir",
    causeDe: "verschmutzter Verfluessiger, Ventilatorstoerung, Rueckansaugung warmer Luft, Ueberfuellung oder sehr hohe Umgebungstemperatur",
    checkTr: "kondenser serpantini, fan yonu, cihaz etrafi bosluklari ve subcool-basinç birlikte kontrol edilir",
    checkDe: "Verfluessigerregister, Ventilatorlaufrichtung, Freiraeume um das Geraet sowie Subcooling und Druck gemeinsam geprueft",
    whyTr: "kondenser isi disariya atamazsa tum sistem basma tarafinda zorlanir",
    whyDe: "der gesamte Kaeltekreis auf der Hochdruckseite belastet wird, wenn der Verfluessiger die Waerme nicht abgeben kann",
    mistakeTr: "sadece gazdan suphelenip hava tarafini ihmal etmektir",
    mistakeDe: "man nur an Kaeltemittel denkt und die Luftseite vernachlaessigt",
    suggestions: ["kondenser nereye konur", "subcool neden onemli", "fan neden donmuyor"],
  },
  {
    id: "problem_low_pressure",
    trSubject: "dusuk basinc arizasi olusuyor",
    deSubject: "eine niederdruck stoerung auftritt",
    keywords: ["dusuk basinc", "low pressure", "niederdruck"],
    causeTr: "gaz eksigi, genlesme valfinin ac beslemesi, evaporatorun buzla kapanmasi veya hava akisinin dusmesidir",
    causeDe: "Kaeltemittelmangel, magere Einspritzung am Expansionsventil, vereister Verdampfer oder zu geringe Luftmenge",
    checkTr: "superheat, sight glass, serpantin buzlanmasi, fanlar ve filtre-drier tikanikligi birlikte degerlendirilir",
    checkDe: "Superheat, Schauglas, Vereisung des Verdampfers, Ventilatoren und ein moeglicher Filtertrocknerengpass gemeinsam bewertet werden",
    whyTr: "emiş tarafi yeterli beslenmezse kompresor sogutma yerine daha cok bos devre cekmeye baslar",
    whyDe: "der Verdichter bei ungenuegender Versorgung auf der Saugseite eher leer laeuft als wirksam zu kuehlen",
    mistakeTr: "dusuk basinç gordu diye direkt gaz eklemektir",
    mistakeDe: "bei Niederdruck sofort Kaeltemittel nachzufuellen",
    suggestions: ["genlesme valfi yanlis ayarlanirsa ne olur", "evaporator neden buz tutar", "gaz eksigi nasil anlasilir"],
  },
  {
    id: "problem_evaporator_icing",
    trSubject: "evaporator buz tutuyor",
    deSubject: "der verdampfer vereist",
    keywords: ["evaporator buz", "icing", "vereisung"],
    causeTr: "defrost yetersizligi, kapi kacaklari, dusuk hava debisi veya sensor ayar bozuklugudur",
    causeDe: "unzureichende Abtauung, Luftleckagen an der Tuer, zu geringer Luftvolumenstrom oder fehlerhafte Fuehlerlogik",
    checkTr: "defrost zamani, rezistans calismasi, drenaj, fan temizligi ve kapi contasi ayni anda incelenir",
    checkDe: "Abtauzeiten, Heizfunktion, Ablauf, Ventilatorzustand und Tuerdichtung zusammen geprueft werden",
    whyTr: "evaporator buzlandiginda hava gecisi daralir ve sogutma giderek daha da kotulesir",
    whyDe: "eine Vereisung den Luftdurchsatz stark reduziert und die Kaelteleistung dadurch immer weiter sinkt",
    mistakeTr: "sadece buzu eritip kok nedenini aramadan sistemi tekrar calistirmaktir",
    mistakeDe: "nur das Eis abzutauen und die Grundursache nicht zu suchen",
    suggestions: ["defrost neden onemli", "kapi sizdirmazligi neden onemli", "fan hava akisi neden duser"],
  },
  {
    id: "problem_condenser_dirty",
    trSubject: "kondenser cok kirleniyor",
    deSubject: "der verfluessiger stark verschmutzt",
    keywords: ["kondenser kirli", "dirty condenser", "verschmutzter verfluessiger"],
    causeTr: "tozlu ortam, yagli hava, yetersiz filtreleme veya yanlis cihaz yerlesimidir",
    causeDe: "staubige Umgebung, fettige Luft, fehlende Vorfilterung oder eine unguenstige Aufstellung",
    checkTr: "serpantin gozlemi, fan cekisi, cihaz cevresi ve temizlik periyodu sorgulanir",
    checkDe: "Registerzustand, Ventilatorwirkung, Geraeteumfeld und Wartungsintervall kontrolliert werden",
    whyTr: "kirli kondenser isi atamaz ve yuksek basinç ile yuksek enerji tuketimi olusturur",
    whyDe: "ein verschmutzter Verfluessiger Waerme nicht abgeben kann und dadurch Hochdruck sowie hohen Stromverbrauch erzeugt",
    mistakeTr: "sadece su tutup temizlik yaptigini sanmak ama kanat aralarini acmamakdir",
    mistakeDe: "nur oberflaechlich abzuspuelen, ohne die Lamellen wirklich zu reinigen",
    suggestions: ["yuksek basinc neden olur", "periyodik bakimda ne kontrol edilir", "kondenser nereye konur"],
  },
  {
    id: "problem_fan_not_running",
    trSubject: "fan donmuyor",
    deSubject: "der ventilator nicht laeuft",
    keywords: ["fan calismiyor", "fan donmuyor", "ventilator steht"],
    causeTr: "motor arizasi, kapasitör sorunu, elektrik beslemesi veya buz-sikismanin olmasidir",
    causeDe: "Motorschaden, Kondensatorproblem, Spannungsversorgung oder Blockierung durch Eis",
    checkTr: "besleme var mi, fan serbest donuyor mu, kapasitör degeri ve motor sargisi saglam mi diye bakilir",
    checkDe: "Spannung, freie Drehbarkeit, Kondensatorwert und Motorwicklung geprueft werden",
    whyTr: "fan olmazsa serpantin isi transfer edemez ve butun sistem dengesi bozulur",
    whyDe: "ohne Ventilator der Waermeuebergang am Register zusammenbricht und die gesamte Anlage aus dem Gleichgewicht kommt",
    mistakeTr: "motora suclama yapip besleme veya buz kilidini atlamaktir",
    mistakeDe: "vorschnell den Motor zu verurteilen und Versorgung oder Eisblockade zu uebersehen",
    suggestions: ["evaporator neden buz tutar", "yanlis fan yonu ne yapar", "elektrik panosunda ne kontrol edilir"],
  },
  {
    id: "problem_wrong_fan_direction",
    trSubject: "fan yonu yanlis",
    deSubject: "die ventilatorlaufrichtung falsch ist",
    keywords: ["fan yonu", "airflow wrong", "falsche laufrichtung"],
    causeTr: "yanlis baglanti, uc faz yon hatasi veya montaj sonrasi kontrol eksikligidir",
    causeDe: "falscher Anschluss, Phasenfolgenfehler oder fehlende Endkontrolle nach der Montage",
    checkTr: "hava atis yonu gozlenir, kanat cekis-atma karakteri ve faz sirasi kontrol edilir",
    checkDe: "Luftwurf, Saugrichtung der Schaufeln und die Phasenfolge geprueft werden",
    whyTr: "yanlis yonlu fan sogutma yapmak yerine hava devrini ters etkileyebilir",
    whyDe: "ein falsch laufender Ventilator statt zu kuehlen die Luftfuehrung massiv verschlechtern kann",
    mistakeTr: "fan donuyor diye yon kontrolunu atlamaktir",
    mistakeDe: "anzunehmen, dass alles richtig ist, nur weil der Ventilator dreht",
    suggestions: ["evaporator nereye konur", "faz sirasi neden onemli", "hava sirkulasyonu neden onemli"],
  },
  {
    id: "problem_defrost_not_working",
    trSubject: "defrost calismiyor",
    deSubject: "die abtauung nicht funktioniert",
    keywords: ["defrost calismiyor", "abtauung", "abtaufehler"],
    causeTr: "rezistans arizasi, zaman ayari bozuklugu, sensor hatasi veya kontrol karti cikis sorunudur",
    causeDe: "Heizungsdefekt, falsche Zeiteinstellung, Fuehlerfehler oder ein Problem am Reglerausgang",
    checkTr: "defrostta enerji geliyor mu, rezistans cekiyor mu, sonlandirma sensoru dogru mu diye bakilir",
    checkDe: "waehrend der Abtauung Spannung anliegt, die Heizung Strom zieht und der Endfuehler plausibel arbeitet",
    whyTr: "defrost calismazsa serpantin dolarak hem hava akisini hem kapasiteyi oldurur",
    whyDe: "ohne funktionierende Abtauung der Verdampfer zusetzt und dadurch Luftmenge wie Leistung zusammenbrechen",
    mistakeTr: "sadece zaman arttirip rezistans ve sensoru dogrulamamaktir",
    mistakeDe: "nur die Abtauzeit zu verlaengern, ohne Heizung und Fuehler zu pruefen",
    suggestions: ["evaporator neden buz tutar", "drenaj neden donar", "defrost sensoru nereye konur"],
  },
  {
    id: "problem_drain_freezing",
    trSubject: "drenaj hatti donuyor",
    deSubject: "die kondensatleitung einfriert",
    keywords: ["drenaj donuyor", "drain freezing", "ablauf friert ein"],
    causeTr: "hatta egim eksikligi, boru rezistansi olmamasi, soguk bolgeden korumasiz gecis veya tikanikliktir",
    causeDe: "fehlendes Gefaelle, keine Begleitheizung, ungeschuetzte Fuehrung durch kalte Bereiche oder eine Verstopfung",
    checkTr: "hat guzergh, egim, rezistans devamligi ve suyun nerede bekledigi kontrol edilir",
    checkDe: "Leitungsweg, Gefaelle, Funktion der Begleitheizung und Wasserstaupunkte geprueft werden",
    whyTr: "drenajdaki en kucuk su birikimi negatifte hizla buza doner ve sorunu buyutur",
    whyDe: "schon kleine Wasseransammlungen im Ablauf bei Minusgraden schnell zu Eis werden und das Problem vergroessern",
    mistakeTr: "yalniz tava rezistansina bakip hatin dis tarafini unutmaktir",
    mistakeDe: "nur die Wannenheizung zu pruefen und den weiteren Leitungsweg zu ignorieren",
    suggestions: ["defrost neden onemli", "negatif depo kurulumunda ne onemli", "su neden fanlara tasar"],
  },
  {
    id: "problem_door_leak",
    trSubject: "kapi hava kaciriyor",
    deSubject: "die tuer luft zieht",
    keywords: ["kapi kaciriyor", "kapi kacak", "kacak yapiyor", "kapi sizdiriyor", "door leak", "tuer undicht"],
    causeTr: "conta asinmasi, kasa ayarsizligi, esik bozuklugu veya kapinin sert kapanmamasidir",
    causeDe: "verschlissene Dichtung, verzogene Zarge, Schwellenproblem oder ungenuegende Schliessung",
    checkTr: "conta basisi, kapi ayari, kasanin kareligi ve terleme izleri kontrol edilir",
    checkDe: "Dichtungsdruck, Tuereinstellung, Rechtwinkligkeit der Zarge und Spuren von Schwitzwasser geprueft werden",
    whyTr: "hava kacagi nem tasir ve bu nem buz, terleme ve enerji kaybi olarak geri doner",
    whyDe: "Luftleckagen Feuchtigkeit eintragen, die dann als Eis, Kondensat und Energieverlust zurueckkommen",
    mistakeTr: "yalniz contayi degistirip kasa ayarini ihmal etmektir",
    mistakeDe: "nur die Dichtung zu tauschen und die Zargeneinstellung zu ignorieren",
    suggestions: ["kapi sizdirmazligi neden onemli", "evaporator neden buz tutar", "panel neden terler"],
  },
  {
    id: "problem_panel_sweating",
    trSubject: "panel terliyor",
    deSubject: "die paneele schwitzen",
    keywords: ["panel terleme", "sweating panel", "paneel schwitzt"],
    causeTr: "izolasyon zayifligi, soguk koprusu, conta veya silikon eksigi ve ortam neminin yuksek olmasidir",
    causeDe: "schwache Isolierung, Waermebruecken, fehlende Abdichtung oder hohe Raumluftfeuchte",
    checkTr: "terleme noktasi lokal mi genel mi, birlesim yerleri ve metal kopruler var mi diye incelenir",
    checkDe: "geprueft wird, ob das Schwitzen lokal oder flaechig ist und ob Fugen oder Metallbruecken beteiligt sind",
    whyTr: "yuzey sicakligi cayir noktasinin altina indiginde panel disinda yogusma baslar",
    whyDe: "Kondensation beginnt, sobald die Oberflaechentemperatur unter den Taupunkt faellt",
    mistakeTr: "sadece cihaz ayarina bakip panel detayini atlamaktir",
    mistakeDe: "nur an der Geraeteeinstellung zu drehen und die baulichen Details zu uebersehen",
    suggestions: ["panel kalinligi nasil secilir", "soguk koprusu nasil onlenir", "kapi hava kaciriyor neden olur"],
  },
  {
    id: "problem_floor_icing",
    trSubject: "zemin buz yapiyor",
    deSubject: "der boden vereist",
    keywords: ["zemin buz", "floor icing", "boden vereist"],
    causeTr: "taban izolasyonunun zayifligi, drenaj problemi, kapi acikligi veya negatifte yerden soguk koprusu olusmasidir",
    causeDe: "schwache Bodendaemmung, Ablaufproblem, Tuerspalt oder Waermebruecken im Minusbereich",
    checkTr: "buzun nerede olustugu, su kaynagi, taban detayi ve esik bolgesi birlikte incelenir",
    checkDe: "Ort der Vereisung, Wasserquelle, Bodendetail und Schwellenbereich gemeinsam betrachtet werden",
    whyTr: "zemindeki buz cogu zaman yalniz soguktan degil, suyun yanlis yerde donmasindan kaynaklanir",
    whyDe: "Eis am Boden oft nicht nur durch Kaelte entsteht, sondern durch Wasser an der falschen Stelle einfriert",
    mistakeTr: "buzu temizleyip suyun nereden geldigini bulmamaktir",
    mistakeDe: "nur das Eis zu entfernen und die Wasserquelle nicht zu suchen",
    suggestions: ["drenaj hatti donuyor", "negatif depo kurulumunda ne onemli", "kapi rezistansi ne zaman gerekir"],
  },
  {
    id: "problem_door_traffic",
    trSubject: "kapi cok acilip kapaniyor diye oda bozuluyor",
    deSubject: "haeufige tueroeffnungen den raum stoeren",
    keywords: ["kapi trafigi", "door traffic", "sik acilma"],
    causeTr: "operasyon akisinin yanlisligi, hava perdesi olmamasi veya bekleme alaninin plansizligidir",
    causeDe: "falscher Betriebsablauf, fehlender Luftvorhang oder unklare Vorbereitungszone",
    checkTr: "kapi kullanim aliskanligi, acik kalma suresi ve urun yukleme yolu analiz edilir",
    checkDe: "Tuernutzung, Offenhaltezeit und Warenfluss im Betrieb analysiert werden",
    whyTr: "kapi acilisinda içeriye giren sicak ve nemli hava cihazin gorevinden daha buyuk yuk yaratabilir",
    whyDe: "bei jeder Tueroeffnung warme und feuchte Luft eindringt und oft mehr Last erzeugt als die Anlage abarbeiten kann",
    mistakeTr: "problemi sadece cihaz zayif diye yorumlamaktir",
    mistakeDe: "das Problem nur als zu schwache Anlage zu deuten",
    suggestions: ["oda gec soguyor neden olur", "kapi sizdirmazligi neden onemli", "yuk hesabi nasil yapilir"],
  },
  {
    id: "problem_airflow_blocked_by_loading",
    trSubject: "urun istifi hava akisini kapatiyor",
    deSubject: "die ware den luftstrom blockiert",
    keywords: ["istif", "airflow blocked", "luftstrom blockiert"],
    causeTr: "kasalarin evaporator altina dayanmasi, duvar diplerinin kapatilmasi veya raflar arasi bosluk birakilmamasidir",
    causeDe: "Kisten unter dem Verdampfer, zugestellte Wandbereiche oder fehlende Luftabstaende zwischen Regalen",
    checkTr: "urun dizilimi, fan onleri, hava donus yollari ve tavan altindaki bosluk gozlenir",
    checkDe: "Warenanordnung, Bereiche vor den Ventilatoren, Rueckluftwege und Freiraeume unter der Decke geprueft werden",
    whyTr: "hava donemezse oda bir yerde soguk, diger yerde sicak kalir",
    whyDe: "ohne freien Luftumlauf Temperaturtaschen entstehen und der Raum lokal ungleichmaessig kuehlt",
    mistakeTr: "cihaz calisiyor diye istif disiplinini onemsiz sanmaktir",
    mistakeDe: "anzunehmen, dass Lagerdisziplin unwichtig ist, solange das Geraet laeuft",
    suggestions: ["hava sirkulasyonu neden onemli", "oda neden dengesiz sogur", "musteri urunu nasil istiflemeli"],
  },
  {
    id: "problem_sensor_wrong_place",
    trSubject: "sensor yeri yanlis oldugu icin sistem sapitiyor",
    deSubject: "die falsche fuehler position die regelung stoert",
    keywords: ["sensor yeri", "wrong sensor place", "fuehler falsch"],
    causeTr: "sondanin hava vurulan noktaya, kapi bolgesine veya urunu temsil etmeyen yere konmasidir",
    causeDe: "der Fuehler im Luftstrahl, im Tuerbereich oder an einer nicht repraesentativen Stelle sitzt",
    checkTr: "sensorun tam yeri, montaj sekli ve ekrandaki sicaklik ile gercek oda sicakligi karsilastirilir",
    checkDe: "exakte Fuehlerposition, Montageart und Vergleich zwischen Anzeige und realer Raumtemperatur gemacht werden",
    whyTr: "yanlis yerdeki sensor duzgun sistemi bile dengesiz gosterebilir",
    whyDe: "ein falsch platzierter Fuehler selbst ein gesundes System unruhig regeln lassen kann",
    mistakeTr: "kontroloru degistirip sensor mantigini sorgulamamaktir",
    mistakeDe: "den Regler zu tauschen, ohne die Messlogik zu hinterfragen",
    suggestions: ["sensor nereye konur", "sicaklik neden sabit kalmiyor", "defrost sensoru neden onemli"],
  },
  {
    id: "problem_expansion_valve_wrong",
    trSubject: "genlesme valfi ayari bozuk",
    deSubject: "das expansionsventil falsch eingestellt ist",
    keywords: ["txv", "tev", "genlesme valfi", "expansionsventil"],
    causeTr: "yanlis superheat, valf boyutunun uygun olmamasi veya ampul baglantisinin sagliksiz olmasidir",
    causeDe: "falscher Superheat, ungeeignete Ventilgroesse oder eine schlechte Fuehlerbefestigung",
    checkTr: "superheat olculur, valf tipi dogrulanir, ampul yeri ve hat izolasyonu incelenir",
    checkDe: "Superheat gemessen, Ventiltyp verifiziert sowie Fuehlerposition und Leitungsdaemmung geprueft werden",
    whyTr: "evaporatorun dogru beslenmesi sogutmanin kalbi gibidir",
    whyDe: "die richtige Befuellung des Verdampfers das Herz der Kuehlleistung ist",
    mistakeTr: "sistemde diger sorunlari elemeden valfe rastgele mudahale etmektir",
    mistakeDe: "am Ventil blind zu drehen, ohne zuerst die restliche Anlage zu pruefen",
    suggestions: ["superheat nasil dusunulur", "dusuk basinc neden olur", "subcool neden onemli"],
  },
  {
    id: "problem_refrigerant_shortage",
    trSubject: "gaz eksikligi var",
    deSubject: "kaeltemittelmangel vorliegt",
    keywords: ["gaz eksigi", "refrigerant shortage", "kaeltemittelmangel"],
    causeTr: "kacak, servis sonrasi eksik sarj veya uzun vadeli sizdirma problemidir",
    causeDe: "Leckage, unvollstaendige Fuellung nach Service oder schleichender Kaeltemittelverlust",
    checkTr: "subcool, sight glass, basinc degerleri ve kacak ihtimali birlikte degerlendirilir",
    checkDe: "Subcooling, Schauglas, Druckwerte und die Moeglichkeit einer Leckage gemeinsam bewertet werden",
    whyTr: "eksik gaz sadece kapasite dusurmez, kompresor sogutmasini ve yag dolasimini da etkileyebilir",
    whyDe: "Kaeltemittelmangel nicht nur Leistung kostet, sondern auch Verdichterkuehlung und Oelumlauf beeinflussen kann",
    mistakeTr: "kacagi bulmadan gaz ekleyip isi bitmis sanmaktir",
    mistakeDe: "ohne Lecksuche einfach nachzufuellen und den Fall als erledigt zu sehen",
    suggestions: ["vakum neden yapilir", "dusuk basinc neden olur", "sight glass kabarcigi ne anlatir"],
  },
  {
    id: "problem_refrigerant_overcharge",
    trSubject: "sistemde fazla gaz var",
    deSubject: "die anlage ueberfuellt ist",
    keywords: ["fazla gaz", "overcharge", "ueberfuellung"],
    causeTr: "kontrolsuz sarj, manometreyi yanlis yorumlama veya kondenser problemi varken fazla gaz sanisidir",
    causeDe: "unkontrollierte Fuellung, falsche Interpretation der Messwerte oder eine Fehlannahme bei Luftseitenproblemen",
    checkTr: "subcool, basma basinci, kondenser hava tarafi ve sistem etiketi birlikte okunur",
    checkDe: "Subcooling, Hochdruck, Luftseite des Verfluessigers und die Sollfuellung gemeinsam betrachtet werden",
    whyTr: "fazla gaz sistemin likit tarafta birikmesine ve basincin gereksiz yukselmesine neden olabilir",
    whyDe: "eine Ueberfuellung zu Fluessigkeitsstau im System und unnoetig hohem Hochdruck fuehren kann",
    mistakeTr: "yuksek basinci gorup otomatik olarak fazla gaz demektir diye dusunmektir",
    mistakeDe: "bei Hochdruck sofort von Ueberfuellung auszugehen",
    suggestions: ["yuksek basinc neden olur", "subcool neden onemli", "kondenser neden kirlenir"],
  },
  {
    id: "problem_filter_drier_blocked",
    trSubject: "filter drier tikali",
    deSubject: "der filtertrockner verstopft ist",
    keywords: ["filter drier", "tikanik", "verstopfter filter"],
    causeTr: "sistem ici pislik, lehimde azot kullanilmamasi veya nem tasinmasidir",
    causeDe: "Schmutz im System, fehlender Stickstoff beim Loeten oder eingetragene Feuchtigkeit",
    checkTr: "filter oncesi-sonrasi sicaklik farki, likit hattinda basinc davranisi ve sight glass izlenir",
    checkDe: "Temperaturdifferenz vor und nach dem Trockner, Verhalten der Fluessigkeitsleitung und Schauglas beobachtet werden",
    whyTr: "tikanik bir filter drier, sivi hattini bogarak genlesme valfine yeterli beslemeyi vermez",
    whyDe: "ein verstopfter Filtertrockner die Fluessigkeitsseite abbremst und das Expansionsventil nicht sauber versorgt",
    mistakeTr: "valfi suclayip likit hattindaki daralmayi atlamaktir",
    mistakeDe: "das Ventil zu verdaechtigen und den Engpass in der Fluessigkeitsleitung zu uebersehen",
    suggestions: ["vakum ve azot testi nasil yapilir", "dusuk basinc neden olur", "subcool neden onemli"],
  },
  {
    id: "problem_oil_return",
    trSubject: "yag donusu bozuk",
    deSubject: "der oelruecklauf schlecht ist",
    keywords: ["yag donusu", "oil return", "oelruecklauf"],
    causeTr: "yanlis boru capi, kot farki, yatay hat egimi veya dusuk gaz hizi olabilir",
    causeDe: "falscher Rohrdurchmesser, Hoehenunterschied, fehlendes Gefaelle oder zu geringe Gasgeschwindigkeit",
    checkTr: "emiş hattinin geometri si, kompresor calisma karakteri ve kompresor tarafindaki yag davranisi incelenir",
    checkDe: "Geometrie der Saugleitung, Betriebsverhalten und Oelzustand am Verdichter untersucht werden",
    whyTr: "kompresor yagi sistemde dolasir ama geri donmesi icin hat tasarimi dogru olmali",
    whyDe: "das Verdichteroel zwar umlaeuft, aber nur bei richtiger Leitungsfuehrung sicher zurueckkehrt",
    mistakeTr: "yag sorununu sadece yag ekleyerek cozmeye calismaktir",
    mistakeDe: "ein Oelproblem nur durch Nachfuellen loesen zu wollen",
    suggestions: ["bakir borulama nasil yapilir", "kompresor neden isiniyor", "superheat neden onemli"],
  },
  {
    id: "problem_short_cycle",
    trSubject: "kompresor kisa devre calisiyor",
    deSubject: "der verdichter im kurzzyklus laeuft",
    keywords: ["kisa devre", "short cycle", "takten"],
    causeTr: "fazla kapasite, hatali sensor yeri, dar diferans ayari veya dusuk yuk seviyesidir",
    causeDe: "zu hohe Leistung, falscher Fuehlerplatz, zu kleine Hysterese oder sehr geringe Last",
    checkTr: "dur-kalk suresi, set-diferans, oda yuk durumu ve kapasite secimi birlikte okunur",
    checkDe: "Taktzeiten, Sollwert-Differenz, Lastsituation und Leistungswahl gemeinsam bewertet werden",
    whyTr: "sik start-stop hem enerji kaybina hem kompresor omrunun kisalmasina yol acar",
    whyDe: "haeufige Start-Stopp-Zyklen sowohl Energie kosten als auch die Lebensdauer des Verdichters verkuerzen",
    mistakeTr: "sik calismayi sogutma iyi diye yorumlamaktir",
    mistakeDe: "haeufiges Takten als Zeichen guter Leistung zu missverstehen",
    suggestions: ["kapasite secimi nasil yapilir", "sensor yeri neden onemli", "sicaklik neden sabit kalmiyor"],
  },
  {
    id: "problem_compressor_noise",
    trSubject: "kompresor sesli calisiyor",
    deSubject: "der verdichter laut laeuft",
    keywords: ["kompresor sesli", "noise", "verdichter laut"],
    causeTr: "sivi donusu, gevsek montaj, vibrasyon, yatak yorgunlugu veya yuksek basinç kaynakli zorlanmadir",
    causeDe: "Fluessigkeitsruecklauf, lockere Montage, Vibration, Lagerverschleiss oder Belastung durch hohe Druecke",
    checkTr: "sesin tipi, boru vuruntusu, ayak takozlari ve basinc degerleri birlikte dinlenir ve olculur",
    checkDe: "Geraeuschcharakter, Rohrschwingung, Gummilager und Druckwerte zusammen beurteilt werden",
    whyTr: "ses cogu zaman kompresorun ne sekilde zorlandigini anlatan erken belirtidir",
    whyDe: "Geraeusche oft ein fruehes Zeichen dafuer sind, wie der Verdichter belastet wird",
    mistakeTr: "normal olmayan sesi zamana birakmaktir",
    mistakeDe: "ungewoehnliche Geraeusche einfach laufen zu lassen",
    suggestions: ["sivi donusu neden olur", "yuksek basinc neden olur", "montaj titreşimi nasil kesilir"],
  },
  {
    id: "problem_liquid_slugging",
    trSubject: "kompresore sivi donuyor",
    deSubject: "fluessigkeit zum verdichter zurueckkommt",
    keywords: ["sivi donusu", "slugging", "fluessigkeitsruecklauf"],
    causeTr: "asiri dusuk superheat, yanlis valf ayari, yuksek yuk degisimi veya defrost sonrasi kontrolsuz geri donustur",
    causeDe: "zu niedriger Superheat, falsche Ventileinstellung, starke Lastspruenge oder unkontrollierter Ruecklauf nach der Abtauung",
    checkTr: "superheat, evaporator davranisi, kompresor sesi ve yag kopurmesi belirtileri incelenir",
    checkDe: "Superheat, Verdampferverhalten, Verdichtergeraeusch und Schaumbildung im Oel beobachtet werden",
    whyTr: "kompresor gaz cekmek icin tasarlanmistir; sivi vurmasi mekanik hasara gider",
    whyDe: "ein Verdichter fuer Gas und nicht fuer Fluessigkeit gebaut ist, sodass Fluessigkeitsschlaege mechanische Schaeden verursachen",
    mistakeTr: "kompresorun sesini gormezden gelip valfe bakmamaktir",
    mistakeDe: "das ungewoehnliche Verdichterverhalten zu ignorieren und das Einspritzverhalten nicht zu pruefen",
    suggestions: ["expansion valve ayari neden onemli", "superheat nasil dusunulur", "kompresor neden sesli calisir"],
  },
  {
    id: "problem_high_discharge_temp",
    trSubject: "kompresor basma sicakligi cok yuksek",
    deSubject: "die druckgastemperatur zu hoch ist",
    keywords: ["basma sicakligi", "discharge temp", "druckgastemperatur"],
    causeTr: "dusuk emiş, yuksek superheat, zayif sogutma veya asiri yukten kaynaklanabilir",
    causeDe: "niedrige Sauggasbedingungen, hoher Superheat, schlechte Kuehlung oder Ueberlastung",
    checkTr: "superheat, kondenser sogutmasi, emiş hattinin izolasyonu ve kompresor akimi kontrol edilir",
    checkDe: "Superheat, Verfluessigerkuehlung, Daemmung der Saugleitung und Verdichterstrom geprueft werden",
    whyTr: "asiri basma sicakligi yag yapisini bozar ve motor omrunu kisaltir",
    whyDe: "zu hohe Druckgastemperaturen das Oel schaedigen und die Motorlebensdauer verkuerzen",
    mistakeTr: "sicakligi normal sayip sadece odanin sogukluguna bakmaktir",
    mistakeDe: "die Temperatur zu ignorieren, nur weil der Raum noch irgendwie kuehlt",
    suggestions: ["yag donusu neden onemli", "superheat neden yukselir", "kondenser neden kirlenir"],
  },
  {
    id: "problem_crankcase_heater",
    trSubject: "krankcase isiticisi calismiyor",
    deSubject: "die oelsumpfheizung nicht funktioniert",
    keywords: ["crankcase heater", "sump heater", "oelsumpfheizung"],
    causeTr: "rezistans arizasi, besleme eksigi veya uzun stoplarda gaz migrasyonudur",
    causeDe: "defekte Heizung, fehlende Versorgung oder Kaeltemittelmigration in Stillstandszeiten",
    checkTr: "isitici direnci, enerji varligi ve uzun durus sonrasi kompresor davranisi izlenir",
    checkDe: "Widerstand der Heizung, Spannungsversorgung und Verdichterverhalten nach laengerem Stillstand geprueft werden",
    whyTr: "isitici olmazsa gaz kartere coker ve ilk kalkista yagi kopurtur",
    whyDe: "ohne Sumpfheizung Kaeltemittel in den Oelraum wandern und beim Start starke Schaumbildung verursachen kann",
    mistakeTr: "sorunu sadece soguk havaya baglayip isitici devresini olcmemektir",
    mistakeDe: "das Problem nur dem kalten Wetter zuzuschreiben, ohne den Heizkreis zu messen",
    suggestions: ["kompresore sivi donuyor neden olur", "uzun stop sonrasi ariza neden baslar", "elektrik panosunda ne kontrol edilir"],
  },
  {
    id: "problem_phase_sequence",
    trSubject: "faz sirasi yanlis",
    deSubject: "die phasenfolge falsch ist",
    keywords: ["faz sirasi", "phase sequence", "phasenfolge"],
    causeTr: "uc faz baglantisinin ters gelmesi veya pano sonrasi saha baglantisinda fazlarin karismasidir",
    causeDe: "vertauschte drei Phasen an der Einspeisung oder nachtraeglich vertauschte Feldverdrahtung",
    checkTr: "faz koruma rolesi, kompresor sesi, akim davranisi ve donus yonu kontrol edilir",
    checkDe: "Phasenwaechter, Verdichtergeraeusch, Stromverhalten und Drehrichtung geprueft werden",
    whyTr: "scroll ve bazi fan motorlari yanlis faz sirasinda saglikli calismaz",
    whyDe: "Scrollverdichter und bestimmte Motoren bei falscher Phasenfolge nicht korrekt arbeiten",
    mistakeTr: "enerji var diye faz kalitesini yeterli sanmaktir",
    mistakeDe: "anzunehmen, dass vorhandene Spannung automatisch richtige Phasenfolge bedeutet",
    suggestions: ["kompresor neden calismiyor", "fan yonu neden onemli", "faz koruma rolesi ne ise yarar"],
  },
  {
    id: "problem_voltage_drop",
    trSubject: "voltaj dusuk geliyor",
    deSubject: "unterspannung anliegt",
    keywords: ["voltaj dusuk", "under voltage", "unterspannung"],
    causeTr: "uzun hat, zayif kablo kesiti, gevsek klemens veya sebeke sorunu olabilir",
    causeDe: "lange Leitung, zu kleiner Kabelquerschnitt, lose Klemmen oder Netzproblem",
    checkTr: "bos ve yuk altinda gerilim, kablo kesiti ve pano baglantilari olculur",
    checkDe: "Spannung im Leerlauf und unter Last, Kabelquerschnitt und Schaltschrankklemmen gemessen werden",
    whyTr: "dusuk voltaj kompresorun akimini arttirip zorlanmasina neden olabilir",
    whyDe: "Unterspannung den Verdichterstrom erhoehen und die Maschine belasten kann",
    mistakeTr: "yalniz cihaz icini kontrol edip besleme hattini unutmaktir",
    mistakeDe: "nur das Geraet selbst zu pruefen und die Zuleitung zu vergessen",
    suggestions: ["kompresor termige neden duser", "gevsek klemens ne yapar", "faz sirasi neden onemli"],
  },
  {
    id: "problem_loose_terminal",
    trSubject: "gevsek klemens arizasi var",
    deSubject: "lose klemmen stoerungen verursachen",
    keywords: ["gevsek klemens", "loose terminal", "lockere klemme"],
    causeTr: "zamanla isinma, vibrasyon veya ilk montajda zayif sikma yapilmis olmasidir",
    causeDe: "Waerme, Vibrationen oder unzureichend angezogene Anschluesse bei der Erstmontage",
    checkTr: "iz yanigi, renk degisimi, isitma izi ve klemens sikiligi gozden gecirilir",
    checkDe: "Verfaerbung, Schmorstellen, Hitzezeichen und Klemmsitz kontrolliert werden",
    whyTr: "gevsek baglanti yuk altinda gerilim dusurur ve ariza yaratir",
    whyDe: "lose Verbindungen unter Last Spannungsabfall und Stoerungen verursachen",
    mistakeTr: "baglantilar saglam gorunuyor diye tornavida kontrolunu ihmal etmektir",
    mistakeDe: "die Schraubkontrolle zu ueberspringen, weil die Verdrahtung optisch gut aussieht",
    suggestions: ["voltaj dusuk gelirse ne olur", "kompresor neden durur", "bakim listesinde neler olmali"],
  },
  {
    id: "problem_bad_condenser_location",
    trSubject: "kondenser yeri yanlis secilmis",
    deSubject: "der verfluessiger falsch platziert ist",
    keywords: ["kondenser yeri", "bad condenser location", "verfluessiger aufstellung"],
    causeTr: "sicak havanin geri emilmesi, dar alan, gunes yukunun fazla olmasi veya servis boslugunun olmamasidir",
    causeDe: "Rueckansaugung heisser Luft, enger Aufstellraum, starke Sonneneinstrahlung oder fehlender Wartungsfreiraum",
    checkTr: "hava cikis yonu, cihaz etrafi mesafe, gunes ve ruzgar etkisi birlikte incelenir",
    checkDe: "Luftausblasrichtung, Abstaende, Sonnenlage und Windeinfluss gemeinsam geprueft werden",
    whyTr: "kotu yerlesim cihaz saglam olsa da yuksek basinç ve verimsizlik yaratir",
    whyDe: "eine schlechte Aufstellung selbst bei gesunder Technik Hochdruck und Ineffizienz erzeugen kann",
    mistakeTr: "yalniz kapasiteye bakip cihazin nerede nefes alacagini dusunmemektir",
    mistakeDe: "nur auf die Leistung zu schauen und nicht darauf, wie das Geraet atmen kann",
    suggestions: ["yuksek basinc neden olur", "kondenser nereye konur", "periyodik bakimda ne kontrol edilir"],
  },
  {
    id: "problem_bad_evaporator_location",
    trSubject: "evaporator yeri yanlis secilmis",
    deSubject: "der verdampfer falsch positioniert ist",
    keywords: ["evaporator yeri", "bad evaporator location", "verdampfer position"],
    causeTr: "hava atisinin urune direkt vurmasi, olu nokta birakmasi veya kapidan gelen sicak havayla catismasidir",
    causeDe: "direkte Anblasung auf die Ware, Totzonen im Raum oder Konflikt mit warmer Luft aus der Tuerzone",
    checkTr: "hava deseni, raf ustu-alti farki ve urunde kuruma belirtileri gozlenir",
    checkDe: "Luftbild, Temperaturunterschiede im Regal und Trocknungsspuren an der Ware beobachtet werden",
    whyTr: "yanlis evaporator yeri kapasite var olsa bile odayi homojen sogutamaz",
    whyDe: "eine falsche Verdampferposition trotz ausreichender Leistung keine gleichmaessige Kuehlung erzeugen kann",
    mistakeTr: "sadece montaj kolayligina gore yer secmektir",
    mistakeDe: "den Platz nur nach Montagebequemlichkeit zu waehlen",
    suggestions: ["evaporator nereye konur", "hava sirkulasyonu neden onemli", "urun neden kurur"],
  },
  {
    id: "problem_low_humidity_drying",
    trSubject: "urun kuruyor cunku nem dusuk",
    deSubject: "die ware austrocknet weil die feuchte zu niedrig ist",
    keywords: ["kurutuyor", "low humidity", "austrocknung"],
    causeTr: "sert hava vurusu, dusuk evaporasyon karakteri, asiri fan etkisi veya urune uygun olmayan oda ayaridir",
    causeDe: "harte Luftanblasung, unguenstige Verdampfung, zu starke Ventilatoren oder eine ungeeignete Raumeinstellung",
    checkTr: "hava hizi, urun ustu etki, evaporator secimi ve urun cinsi birlikte degerlendirilir",
    checkDe: "Luftgeschwindigkeit, Einfluss auf die Ware, Verdampferauswahl und Produkttyp gemeinsam betrachtet werden",
    whyTr: "bazı urunlerde kalite kaybi sicakliktan once hava ve nem karakteriyle baslar",
    whyDe: "bei manchen Produkten der Qualitaetsverlust frueher ueber Luftfuehrung und Feuchte als ueber Temperatur beginnt",
    mistakeTr: "urun kurumasini yalniz sogukluga baglamaktir",
    mistakeDe: "Austrocknung ausschliesslich als Temperaturproblem zu betrachten",
    suggestions: ["sebze meyve odasi nasil planlanir", "evaporator nereye konur", "hava hizi neden onemli"],
  },
  {
    id: "problem_high_humidity_condensation",
    trSubject: "oda icinde asiri nem ve yogusma var",
    deSubject: "zu viel feuchte und kondensat im raum sind",
    keywords: ["yogusma", "nem yuksek", "condensation", "kondensat"],
    causeTr: "kapi kacagi, yogun yikama, urunun sicak girmesi veya zayif hava dagilimidir",
    causeDe: "Tuerleckage, starke Nassreinigung, warm eingelagerte Ware oder schlechte Luftverteilung",
    checkTr: "kapi, panel birlesimleri, urun giris duzeni ve fan karakteri birlikte bakilir",
    checkDe: "Tuer, Paneelfugen, Wareneintrag und Ventilatorcharakteristik zusammen bewertet werden",
    whyTr: "fazla nem hem buzlanma hem hijyen hem de enerji tuketim sorunlarini beraber getirir",
    whyDe: "zu hohe Feuchte gleichzeitig Vereisung, Hygieneprobleme und Energieverlust erzeugt",
    mistakeTr: "yalnizca suyu silip kaynagi durdurmamaktir",
    mistakeDe: "nur das Wasser zu entfernen, ohne die Quelle zu beseitigen",
    suggestions: ["kapi hava kaciriyor neden olur", "panel neden terler", "defrost neden yetersiz kalir"],
  },
  {
    id: "problem_door_heater_failure",
    trSubject: "kapi rezistansi calismiyor",
    deSubject: "die tuerheizung nicht funktioniert",
    keywords: ["kapi rezistansi", "door heater", "tuerheizung"],
    causeTr: "rezistans kopugu, besleme eksigi veya termik koruma devresidir",
    causeDe: "Heizungsunterbrechung, fehlende Versorgung oder eine Schutzabschaltung",
    checkTr: "rezistans devamligi, enerji gelisi ve esik-kasa bolgesindeki donma izleri kontrol edilir",
    checkDe: "Heizungsdurchgang, Spannungsversorgung und Frostspuren an Zarge und Schwelle geprueft werden",
    whyTr: "negatif odada kapi cevresi isitilmezse buz, kapanma bozuklugu ve hava kacagi olusur",
    whyDe: "im Tiefkuehlraum ohne Heizung an Tuer und Schwelle Eis, schlechte Schliessung und Luftleckagen entstehen",
    mistakeTr: "kapinin sertlesmesini sadece contaya baglamaktir",
    mistakeDe: "die schwergängige Tuer nur der Dichtung anzulasten",
    suggestions: ["negatif depo kurulumunda ne onemli", "kapi sizdirmazligi neden onemli", "zemin neden buz yapar"],
  },
  {
    id: "problem_defrost_heater_failure",
    trSubject: "defrost rezistansi bozuk",
    deSubject: "die abtauheizung defekt ist",
    keywords: ["defrost rezistansi", "abtauheizung", "heater failure"],
    causeTr: "rezistans yanigi, klemens kopuklugu veya cikis rolesi problemidir",
    causeDe: "defekte Heizung, Leitungsunterbrechung oder ein Problem am Schaltausgang",
    checkTr: "rezistans direnci olculur, defrost aninda akim var mi bakilir ve sonlandirma sensoru dogrulanir",
    checkDe: "Widerstand der Heizung, Stromaufnahme waehrend der Abtauung und der Endfuehler kontrolliert werden",
    whyTr: "isitici acmazsa serpantin birikimli buzla giderek nefesini kaybeder",
    whyDe: "ohne funktionierende Heizung der Verdampfer mit wachsendem Eis seine Luftleistung verliert",
    mistakeTr: "defrost suresini buyuterek rezistans arizasini gizlemeye calismaktir",
    mistakeDe: "durch laengere Abtauzeiten einen echten Heizungsfehler kaschieren zu wollen",
    suggestions: ["defrost neden calismiyor", "evaporator neden buz tutar", "sensor yeri neden onemli"],
  },
  {
    id: "problem_solenoid_valve",
    trSubject: "solenoid valf sorunlu",
    deSubject: "das magnetventil probleme macht",
    keywords: ["solenoid", "magnet valf", "magnetventil"],
    causeTr: "bobin arizasi, kirlenme, mekanik takilma veya elektrik komutunun gelmemesidir",
    causeDe: "Spulendefekt, Verschmutzung, mechanisches Klemmen oder fehlendes elektrisches Signal",
    checkTr: "bobin enerjisi, klik sesi, valf acma kapama davranisi ve hat basinci izlenir",
    checkDe: "Spulenspannung, Schaltgeraeusch, Oeffnungs-/Schliessverhalten und Leitungsdruck beobachtet werden",
    whyTr: "solenoid valf akisin zamanlamasini bozar ve sistemin sekansini etkiler",
    whyDe: "das Magnetventil die zeitliche Freigabe des Kreislaufs steuert und damit den Ablauf der Anlage beeinflusst",
    mistakeTr: "bobini degistirip govdeyi veya kirlenmeyi kontrol etmemektir",
    mistakeDe: "nur die Spule zu tauschen und die Mechanik bzw. Verschmutzung nicht zu pruefen",
    suggestions: ["dusuk basinc neden olur", "kontrol panosunda ne kontrol edilir", "filter drier neden tikanir"],
  },
  {
    id: "problem_sight_glass_bubbles",
    trSubject: "sight glass kabarcik gosteriyor",
    deSubject: "das schauglas blasen zeigt",
    keywords: ["sight glass", "kabarcik", "schauglas blasen"],
    causeTr: "gaz eksigi, subcool yetersizligi veya likit hattinda daralma olabilir",
    causeDe: "Kaeltemittelmangel, unzureichendes Subcooling oder ein Engpass in der Fluessigkeitsleitung",
    checkTr: "subcool, filter drier, kondenser hava tarafi ve toplam sarj mantigi birlikte degerlendirilir",
    checkDe: "Subcooling, Filtertrockner, Luftseite des Verfluessigers und Gesamtsystemfuellung zusammen bewertet werden",
    whyTr: "sight glass tek basina karar verdirmez ama likit hattinin kararliligi hakkinda ipucu verir",
    whyDe: "das Schauglas allein keine Diagnose ersetzt, aber viel ueber die Stabilitaet der Fluessigkeitsseite verraet",
    mistakeTr: "kabarcik gordu diye dogrudan gaz basmaktir",
    mistakeDe: "bei Blasen sofort Kaeltemittel nachzufuellen",
    suggestions: ["gaz eksikligi nasil anlasilir", "subcool neden onemli", "filter drier neden tikanir"],
  },
  {
    id: "problem_pressure_switch_trip",
    trSubject: "basinc switch sistemi durduruyor",
    deSubject: "der druckschalter die anlage abschaltet",
    keywords: ["pressure switch", "basinc switch", "druckschalter"],
    causeTr: "gercek yuksek/dusuk basinç, ayar bozuklugu veya switch arizasidir",
    causeDe: "tatsaechlich falscher Druck, schlechte Einstellung oder ein defekter Schalter",
    checkTr: "gercek manometre degeri ile switch davranisi karsilastirilir ve mekanik/elektrik taraf ayrilir",
    checkDe: "reale Druckwerte mit dem Verhalten des Schalters verglichen und Mechanik wie Elektrik getrennt bewertet werden",
    whyTr: "switch sonuc degil koruma tepkisidir; asil nedeni bulmak gerekir",
    whyDe: "der Druckschalter meist nicht die Ursache, sondern die Schutzreaktion auf ein anderes Problem ist",
    mistakeTr: "switch by-pass edip sistemi zorla calistirmaktir",
    mistakeDe: "den Schalter zu ueberbruecken und die Anlage zwangsweise weiterlaufen zu lassen",
    suggestions: ["yuksek basinc neden olur", "dusuk basinc neden olur", "gucuk koruma elemanlari ne ise yarar"],
  },
  {
    id: "problem_control_settings",
    trSubject: "kontrolor ayarlari yanlis",
    deSubject: "die regler parameter falsch sind",
    keywords: ["kontrolor", "ayar", "parameter", "controller settings"],
    causeTr: "yanlis set degeri, diferans, defrost zamani, fan gecikmesi veya sensor tipi secimidir",
    causeDe: "falscher Sollwert, Hysterese, Abtauzeit, Ventilatorverzoegerung oder Sensortyp",
    checkTr: "tum temel parametreler uygulama tipine gore tekrar okunur ve kurulu saha ile karsilastirilir",
    checkDe: "die Grundparameter mit dem realen Einsatzfall und der installierten Anlage abgeglichen werden",
    whyTr: "iyi cihaz bile yanlis parametreyle kotu calisir",
    whyDe: "selbst gute Hardware mit falschen Parametern schlecht arbeitet",
    mistakeTr: "fabrika ayariyla birakip uygulamaya gore optimize etmemektir",
    mistakeDe: "die Werkseinstellung zu belassen, ohne auf den echten Einsatzfall anzupassen",
    suggestions: ["sensor yeri neden onemli", "defrost neden onemli", "devreye alma sirasinda ne kontrol edilir"],
  },
  {
    id: "problem_sensor_calibration",
    trSubject: "sensor kalibrasyonu kaymis",
    deSubject: "die fuehler kalibrierung abweicht",
    keywords: ["sensor kalibrasyon", "calibration drift", "fuehler abweichung"],
    causeTr: "yaslanma, nem etkisi, kablo hasari veya dusuk kalite sensor davranisi olabilir",
    causeDe: "Alterung, Feuchtigkeit, Leitungsproblem oder ein schlechter Fuehler",
    checkTr: "referans termometreyle karsilastirma yapilir ve fark kararlimi izlenir",
    checkDe: "mit einem Referenzthermometer verglichen und die Abweichung ueber die Zeit beobachtet wird",
    whyTr: "kucuk sensor hatasi bile kritik urunlerde ciddi kalite farki yaratabilir",
    whyDe: "selbst kleine Messabweichungen bei sensibler Ware grosse Qualitaetsfolgen haben koennen",
    mistakeTr: "ekran degerini mutlak dogru kabul etmektir",
    mistakeDe: "den angezeigten Wert als absolute Wahrheit zu nehmen",
    suggestions: ["sensor nereye konur", "sicaklik neden sabit kalmiyor", "kontrolor ayarlari neden bozulur"],
  },
  {
    id: "problem_bad_smell_hygiene",
    trSubject: "odada koku ve hijyen sorunu var",
    deSubject: "geruch und hygieneprobleme im raum auftreten",
    keywords: ["koku", "hijyen", "smell", "hygiene"],
    causeTr: "drenaj kirliligi, su birikimi, panel birlesimlerinde kir tutulmasi veya bozuk urun yonetimidir",
    causeDe: "verschmutzte Ablaufe, Wasserstau, Schmutznester in Fugen oder schlechte Warenhygiene",
    checkTr: "drenaj, panel kose detaylari, tava suyu ve urun sirkulasyonu birlikte kontrol edilir",
    checkDe: "Ablauf, Eckdetails der Paneele, Wasser in Wannen und Warenhygiene gemeinsam betrachtet werden",
    whyTr: "hijyen problemi zamanla sadece koku degil urun guvenligi ve cihaz omru sorunu yaratir",
    whyDe: "Hygieneprobleme spaeter nicht nur Geruch, sondern Produkt- und Anlagenprobleme verursachen",
    mistakeTr: "yalniz spreyle koku bastirip sebepleri temizlememektir",
    mistakeDe: "Geruch nur zu ueberdecken statt die Ursachen zu reinigen",
    suggestions: ["drenaj neden onemli", "et deposunda hijyen nasil korunur", "bakimda neler kontrol edilir"],
  },
  {
    id: "problem_water_ingress_after_wash",
    trSubject: "yikama sonrasi ariza cikiyor",
    deSubject: "nach der reinigung stoerungen entstehen",
    keywords: ["yikama sonrasi", "water ingress", "nach reinigung"],
    causeTr: "elektrik panosu, fan motoru, sensor soketi veya kontrol kutusuna su almasidir",
    causeDe: "Wasser in Schaltschrank, Ventilatormotor, Fuehlerstecker oder Reglerkasten",
    checkTr: "hangi yikama sonrasi oldugu, suyun temas ettigi ekipman ve izolasyon durumu sorgulanir",
    checkDe: "welche Reinigung vorausging, welche Bauteile Wasser abbekommen haben und wie deren Schutz aufgebaut ist",
    whyTr: "su izolasyonu zayif ekipmanda gecikmeli ariza ve oksidasyon baslatir",
    whyDe: "Wasser in schwach geschuetzten Bauteilen spaete Stoerungen und Oxidation ausloest",
    mistakeTr: "yikama prosedurunu teknik ekipmandan bagimsiz dusunmektir",
    mistakeDe: "Reinigung ohne Ruecksicht auf die technische Schutzklasse zu planen",
    suggestions: ["sut urunleri odasinda nelere dikkat edilir", "elektrik panosunda ne kontrol edilir", "korozyon nasil onlenir"],
  },
  {
    id: "problem_hot_product_loading",
    trSubject: "urun cok sicak giriyor",
    deSubject: "die ware zu warm eingebracht wird",
    keywords: ["urun sicak", "hot product", "warme ware"],
    causeTr: "proses sonrasi yeterli on sogutma yapilmamasi veya odanin kapasitesinin yukleme ritmine uygun olmamasidir",
    causeDe: "fehlende Vorkuehlung nach dem Prozess oder eine Leistung, die nicht zum Beladerhythmus passt",
    checkTr: "urun giris sicakligi, gunluk parti buyuklugu ve oda hedefleme suresi karsilastirilir",
    checkDe: "Eintrittstemperatur der Ware, Chargengroesse und gewuenschte Abkuehlzeit verglichen werden",
    whyTr: "soguk oda bazen muhafaza icindir; prosesten cikan sicak urunu sok mantigiyla alamayabilir",
    whyDe: "ein Kuehlraum oft fuer Lagerung gedacht ist und nicht automatisch heisse Ware wie ein Schockraum uebernehmen kann",
    mistakeTr: "urun prosesi degismeden cihazdan mucize beklemektir",
    mistakeDe: "ohne Aenderung des Prozesses Wunder von der Anlage zu erwarten",
    suggestions: ["sok oda ile muhafaza odasi farki nedir", "oda gec soguyor neden olur", "kapasite secimi nasil yapilir"],
  },
  {
    id: "problem_oversized_system",
    trSubject: "cihaz fazla buyuk secilmis",
    deSubject: "das aggregat zu gross ausgelegt ist",
    keywords: ["fazla buyuk cihaz", "oversized", "zu gross"],
    causeTr: "emniyet payinin abartilmasi veya yalniz metrekup uzerinden kaba secim yapilmasidir",
    causeDe: "uebertriebene Reserve oder eine zu grobe Auswahl nur nach Kubikmetern",
    checkTr: "start-stop sayisi, nem davranisi, urun kuruma belirtileri ve gercek yuk seviyesi izlenir",
    checkDe: "Taktzeiten, Feuchteverhalten, Austrocknung der Ware und reale Last beobachtet werden",
    whyTr: "asiri buyuk cihaz oda ihtiyacindan once kendi hizli stop-start davranisiyla sorun uretir",
    whyDe: "eine zu grosse Anlage durch schnelles Takten und schlechtes Feuchteverhalten eigene Probleme erzeugt",
    mistakeTr: "buyuk cihaz her zaman daha iyidir diye dusunmektir",
    mistakeDe: "zu glauben, dass groesser automatisch besser ist",
    suggestions: ["kompresor kisa devre neden calisir", "kapasite secimi nasil yapilir", "urun neden kurur"],
  },
  {
    id: "problem_undersized_system",
    trSubject: "cihaz kucuk secilmis",
    deSubject: "das aggregat zu klein ausgelegt ist",
    keywords: ["kucuk cihaz", "undersized", "zu klein"],
    causeTr: "yuk hesabinin eksik alinmasi, kapı trafiginin veya mal girisinin hesaba katilmamasidir",
    causeDe: "unvollstaendige Lastberechnung, nicht beruecksichtigte Tueroeffnungen oder Wareneintraege",
    checkTr: "oda hedef sicakligi, gunluk yuk ve cihazin calisma yuzdesi birlikte analiz edilir",
    checkDe: "Solltemperatur, taegliche Last und Einschaltdauer der Anlage gemeinsam analysiert werden",
    whyTr: "kucuk cihaz neredeyse durmadan calissa bile pik yukte yetismeyebilir",
    whyDe: "eine zu kleine Anlage selbst bei Dauerlauf Spitzenlasten nicht abarbeiten kann",
    mistakeTr: "o an sogutuyor diye secimi dogru sanmaktir",
    mistakeDe: "die Auslegung als richtig zu betrachten, nur weil der Raum momentan irgendwie kalt ist",
    suggestions: ["yuk hesabi nasil yapilir", "oda gec soguyor neden olur", "kapi trafigi nasil etkiler"],
  },
  {
    id: "problem_no_maintenance",
    trSubject: "bakim yapilmadigi icin ariza tekrar ediyor",
    deSubject: "mangelnde wartung zu wiederkehrenden stoerungen fuehrt",
    keywords: ["bakim yapilmiyor", "no maintenance", "wartung fehlt"],
    causeTr: "kirlenme, gevseme, ayar kaymasi ve kucuk problemlerin buyuyerek birikmesidir",
    causeDe: "Verschmutzung, Lockerung, Einstellabweichung und das Aufwachsen kleiner Probleme",
    checkTr: "eski servis kaydi, temizlik duzeni ve olcumlerin onceki durumuyla bugunku hali karsilastirilir",
    checkDe: "alte Serviceberichte, Reinigungsroutine und fruehere Messwerte mit dem aktuellen Zustand verglichen werden",
    whyTr: "soguk oda arizasi cogu zaman bir gunde degil, birikimli sekilde olusur",
    whyDe: "Stoerungen im Kuehlraum oft nicht ploetzlich, sondern durch schleichende Verschlechterung entstehen",
    mistakeTr: "bakimi masraf sanip sadece ariza ciktiginda mudahale etmektir",
    mistakeDe: "Wartung nur als Kostenpunkt zu sehen und erst bei Ausfall zu reagieren",
    suggestions: ["periyodik bakimda ne kontrol edilir", "kondenser neden kirlenir", "gevsek klemens ne yapar"],
  },
  {
    id: "problem_product_top_bottom_diff",
    trSubject: "ust raf alt raf sicakligi farkli",
    deSubject: "obere und untere regalebene unterschiedliche temperatur haben",
    keywords: ["ust raf alt raf", "top bottom temp", "temperaturschichtung"],
    causeTr: "hava dagiliminin yetersizligi, fan yerlesimi veya urun istifinin hava yolunu bozmasidir",
    causeDe: "schlechte Luftverteilung, unguenstige Ventilatoranordnung oder blockierte Luftwege durch Lagergut",
    checkTr: "farkli noktalardan sicaklik okunur, hava cikis-donus yolu ve istif yapisi incelenir",
    checkDe: "Temperaturen an mehreren Punkten gemessen sowie Luftwege und Warenanordnung untersucht werden",
    whyTr: "oda tek deger gosterse bile urun seviyelerinde farkli mikro alanlar olusabilir",
    whyDe: "auch bei einer einzigen Anzeigen-Temperatur im Raum unterschiedliche Mikroklimata an der Ware entstehen koennen",
    mistakeTr: "yalniz kontrolor ekranina bakip odayi homojen sanmaktir",
    mistakeDe: "nur der Anzeige am Regler zu vertrauen und Homogenitaet anzunehmen",
    suggestions: ["evaporator nereye konur", "hava sirkulasyonu neden onemli", "urun istifi hava akisini nasil bozar"],
  },
  {
    id: "problem_ice_after_defrost",
    trSubject: "defrosttan sonra yine hizli buz yapiyor",
    deSubject: "nach der abtauung schnell wieder eis entsteht",
    keywords: ["defrosttan sonra buz", "ice after defrost", "vereist schnell wieder"],
    causeTr: "kapi kacaklari, fan gecikmesi hatasi, suyun tam akmamasi veya yuksek nem yukudur",
    causeDe: "Tuerleckagen, falsche Ventilatorverzoegerung, unvollstaendiger Wasserablauf oder hohe Feuchtelast",
    checkTr: "defrost bitim sekli, fan gecikmesi, drenaj ve kapi kacagi ayni tabloda okunur",
    checkDe: "Abtauende, Ventilatorverzoegerung, Ablauf und Tuerleckagen als Gesamtbild bewertet werden",
    whyTr: "defrost tek basina buz sorununu cozmeyebilir; nem kaynagi devam ediyorsa buz geri gelir",
    whyDe: "Abtauung allein das Eisproblem nicht loest, wenn die Feuchtequelle bestehen bleibt",
    mistakeTr: "yalniz abtau sayisini artirmaktir",
    mistakeDe: "nur die Zahl der Abtauungen zu erhoehen",
    suggestions: ["kapi hava kaciriyor neden olur", "drenaj hatti neden donar", "defrost neden onemli"],
  },
  {
    id: "problem_alarm_but_room_ok",
    trSubject: "alarm veriyor ama oda bazen normal gorunuyor",
    deSubject: "alarm ausloest obwohl der raum zeitweise normal wirkt",
    keywords: ["alarm var", "intermittent fault", "alarm obwohl normal"],
    causeTr: "kesik kesik sensor hatasi, gevsek baglanti, gecici basinç sorunu veya kullanima bagli yuk dalgalanmasidir",
    causeDe: "sporadischer Fuehlerfehler, lose Verbindung, kurzzeitiges Druckproblem oder nutzungsbedingte Lastspruenge",
    checkTr: "alarm kayit saatiyle o andaki kullanim, kapi acilisi ve ekipman durumu karsilastirilir",
    checkDe: "Alarmzeit mit Nutzung, Tueroeffnung und Anlagenzustand abgeglichen wird",
    whyTr: "ariza anlik olabilir; siz baktiginizda normale donmus olabilir",
    whyDe: "manche Stoerungen nur kurz auftreten und bei Ankunft schon wieder verschwunden sein koennen",
    mistakeTr: "alarm silip kayit saatini ve tekrar desenini incelememektir",
    mistakeDe: "den Alarm nur zu quittieren, ohne Uhrzeit und Wiederholmuster auszuwerten",
    suggestions: ["sensor kalibrasyonu nasil bozulur", "gevsek klemens ne yapar", "ariza teshisine nereden baslanir"],
  },
  {
    id: "problem_pressure_equalization",
    trSubject: "sistem durup kalkarken zorlanıyor",
    deSubject: "die anlage beim stop und start schwer anlaeuft",
    keywords: ["zor kalkiyor", "hard start", "schwerer start"],
    causeTr: "basinc esitlenmemesi, kontaktor-kondansator sorunu veya kompresorun yuklu kalkmasidir",
    causeDe: "fehlender Druckausgleich, Schuetz-/Kondensatorproblem oder ein belasteter Verdichterstart",
    checkTr: "durus sonrasi basinc dengesi, start komponentleri ve solenoid kapanma davranisi incelenir",
    checkDe: "Druckausgleich nach dem Stopp, Startkomponenten und das Schliessverhalten des Magnetventils geprueft werden",
    whyTr: "kompresor basinc altinda kalkarsa normalden cok daha fazla zorlanir",
    whyDe: "ein Verdichter unter Drucklast deutlich schwerer anlaeuft als unter normalen Bedingungen",
    mistakeTr: "motoru suclayip devre sekansini okumamaktir",
    mistakeDe: "den Motor zu beschuldigen, ohne die Startsequenz zu analysieren",
    suggestions: ["kompresor neden calismiyor", "solenoid valf sorunluysa ne olur", "kompresor termige neden duser"],
  },
  {
    id: "problem_hot_gas_valve_or_line",
    trSubject: "sicak gaz hattinda anormallik var",
    deSubject: "an der heissgasleitung eine unregelmaessigkeit ist",
    keywords: ["sicak gaz", "heissgas", "hot gas line"],
    causeTr: "yuksek basinc, dusuk emiş, valf ayari veya kompresor zorlanmasi olabilir",
    causeDe: "Hochdruck, schlechte Saugbedingungen, Ventileinstellung oder Verdichterueberlastung",
    checkTr: "basma sicakligi, superheat, kondenser hava tarafi ve emiş hattinin hali birlikte okunur",
    checkDe: "Druckgastemperatur, Superheat, Verfluessigerluft und Saugleitungszustand gemeinsam bewertet werden",
    whyTr: "sicak gaz hatti kompresorun ne kadar zorlandigini gosteren kritik bolgedir",
    whyDe: "die Heissgasleitung ein sehr guter Indikator fuer die Belastung des Verdichters ist",
    mistakeTr: "yalniz basinç bakip sicaklik tarafini ihmal etmektir",
    mistakeDe: "nur Druecke zu beachten und die Temperaturseite zu vernachlaessigen",
    suggestions: ["basma sicakligi neden yukselir", "superheat nasil dusunulur", "kondenser neden kirlenir"],
  },
  {
    id: "problem_product_freezing_in_plus_room",
    trSubject: "arti odada urun donuyor",
    deSubject: "ware im plusraum einfriert",
    keywords: ["arti odada donuyor", "product freezing", "ware friert ein"],
    causeTr: "hava urune direkt vuruyor, sensor yeri yanlis veya cihaz kapasitesi oda karakterine gore sert calisiyordur",
    causeDe: "direkter Luftstrahl, falsche Fuehlerposition oder ein fuer den Plusraum zu aggressives Betriebsverhalten",
    checkTr: "urunun oldugu nokta, fan vurusu, sensor yeri ve gece-gunduz sicaklik farki kontrol edilir",
    checkDe: "Position der Ware, Luftanblasung, Fuehlerplatz und Temperaturverlauf ueber Tag und Nacht geprueft werden",
    whyTr: "oda ortalaması arti olsa bile lokal hava akisi urunu donma noktasina indirebilir",
    whyDe: "die Luft lokal deutlich kaelter sein kann als der durchschnittliche Raumwert",
    mistakeTr: "ekrana bakip urunun neden dondugunu anlamaya calismaktir",
    mistakeDe: "nur auf die Anzeige zu schauen und nicht auf die reale Position der Ware",
    suggestions: ["sensor nereye konur", "evaporator yeri neden onemli", "hava hizi urunu neden etkiler"],
  },
  {
    id: "problem_product_not_reaching_safe_temp",
    trSubject: "urun guvenli sicakliga inmiyor",
    deSubject: "die ware nicht auf sichere temperatur kommt",
    keywords: ["guvenli sicaklik", "safe temperature", "zieltemperatur nicht erreicht"],
    causeTr: "yanlis oda tipi, yetersiz kapasite, fazla yuk veya urun merkezine uygun olmayan hava karakteridir",
    causeDe: "falscher Raumtyp, zu geringe Leistung, Ueberlast oder ungeeignete Luftcharakteristik fuer die Kernabkuehlung",
    checkTr: "urun merkez sicakligi, parti buyuklugu, sure beklentisi ve cihaz secimi birlikte degerlendirilir",
    checkDe: "Kerntemperatur, Chargengroesse, Zeitvorgabe und Geraeteauslegung gemeinsam bewertet werden",
    whyTr: "merkez soguma ile oda hava sicakligi ayni sey degildir",
    whyDe: "Kernabkuehlung und Lufttemperatur im Raum nicht dasselbe sind",
    mistakeTr: "hava soguksa urun de soguktur diye varsaymaktir",
    mistakeDe: "davon auszugehen, dass kalte Raumluft automatisch kalte Produktkerne bedeutet",
    suggestions: ["sok oda ile muhafaza odasi farki nedir", "kapasite secimi nasil yapilir", "hava sirkulasyonu neden onemli"],
  },
  {
    id: "problem_condensing_unit_vibration",
    trSubject: "dis unite titreşim yapiyor",
    deSubject: "die ausseneinheit stark vibriert",
    keywords: ["titreşim", "vibration", "ausseneinheit vibrier"],
    causeTr: "ayak takozu eksigi, dengesiz zemin, boru gerilmesi veya fan balans sorunudur",
    causeDe: "fehlende Schwingungsdaempfer, unebener Untergrund, Verspannung in den Rohren oder ein Unwuchtproblem am Ventilator",
    checkTr: "zemin, sabitleme, borularin cihaz cekip cekmedigi ve fan kanadi durumu kontrol edilir",
    checkDe: "Untergrund, Befestigung, Rohrverspannung und Zustand des Ventilatorfluegels geprueft werden",
    whyTr: "titreşim yalniz ses degil, zamanla boru ve elektrik baglantilarini da bozan etkidir",
    whyDe: "Vibration nicht nur Geraeusch erzeugt, sondern langfristig Rohre und Elektroverbindungen schaedigt",
    mistakeTr: "ses azaltiyor diye geçici takoz veya sıkma ile yetinmektir",
    mistakeDe: "sich mit einer provisorischen Daempfung zufriedenzugeben",
    suggestions: ["kompresor neden sesli calisir", "kondenser yeri nasil secilir", "gevsek klemens ne yapar"],
  },
  {
    id: "problem_fan_blade_icing",
    trSubject: "fan kanadinda buz birikiyor",
    deSubject: "sich eis am ventilatorfluegel bildet",
    keywords: ["fan buz", "fan blade ice", "ventilator vereisung"],
    causeTr: "tasan drenaj, yetersiz defrost, asiri nem veya fan gecikme ayarinin bozuk olmasidir",
    causeDe: "ueberlaufender Ablauf, mangelhafte Abtauung, hohe Feuchte oder falsche Ventilatorverzoegerung",
    checkTr: "suyun nereden geldigi, defrost bitisi ve fan devreye giris zamani incelenir",
    checkDe: "Wasserherkunft, Ende der Abtauung und Wiedereinschaltzeit der Ventilatoren geprueft werden",
    whyTr: "fan ustundeki buz hem balans bozar hem de hava debisini dusurur",
    whyDe: "Eis am Ventilator sowohl die Balance stoert als auch den Luftdurchsatz reduziert",
    mistakeTr: "fan buzunu kirip sebebi aramadan devam etmektir",
    mistakeDe: "das Eis nur abzuschlagen, ohne die Ursache zu beseitigen",
    suggestions: ["defrost neden onemli", "drenaj hatti neden donar", "evaporator neden buz tutar"],
  },
  {
    id: "problem_alarm_from_bad_defrost_end",
    trSubject: "defrost gec bitiyor veya erken bitiyor",
    deSubject: "die abtauung zu frueh oder zu spaet endet",
    keywords: ["defrost erken", "defrost gec", "abtauung endet falsch"],
    causeTr: "yanlis sonlandirma sensoru, parametre hatasi veya rezistans performans farkidir",
    causeDe: "falscher Endfuehler, Parametrierfehler oder schwankende Heizleistung",
    checkTr: "sensor yeri, sonlandirma sicakligi ve gercek serpantin cozulme durumu birlikte izlenir",
    checkDe: "Fuehlerposition, Endtemperatur und realer Abtauzustand des Verdampfers gemeinsam beobachtet werden",
    whyTr: "yanlis biten defrost ya gereksiz isi verir ya da buzun yarida kalmasina yol acar",
    whyDe: "eine falsch beendete Abtauung entweder unnoetig Waerme eintraegt oder Eisreste im Register laesst",
    mistakeTr: "yalniz saati degistirip sensor mantigini sorgulamamaktir",
    mistakeDe: "nur an der Zeit zu drehen und die Fuehlerlogik nicht zu pruefen",
    suggestions: ["defrost neden onemli", "sensor nereye konur", "evaporator neden buz tutar"],
  },
  {
    id: "problem_service_valve_issue",
    trSubject: "servis vanasi sorunu var",
    deSubject: "ein problem an der service armatur besteht",
    keywords: ["servis vanasi", "service valve", "service armatur"],
    causeTr: "yarim acik vanalar, sizdirma, hasarli mil veya servis sonrasi yanlis pozisyonda birakmadir",
    causeDe: "halb offene Ventile, Undichtigkeit, beschaedigte Spindel oder falsche Stellung nach Servicearbeiten",
    checkTr: "vana konumu, sizdirmazlik, sıcaklık farki ve servis gecmisi kontrol edilir",
    checkDe: "Ventilstellung, Dichtheit, Temperaturverlauf und Servicehistorie geprueft werden",
    whyTr: "servis vanasindaki hata butun sistemin basinç ve akisini etkileyebilir",
    whyDe: "ein Fehler an der Servicearmatur den gesamten Druck- und Massenstrom der Anlage beeinflussen kann",
    mistakeTr: "vana yarim acik kaldigini gozden kacirmaktir",
    mistakeDe: "eine teiloffene Armatur zu uebersehen",
    suggestions: ["gaz eksigi nasil anlasilir", "basinc neden dengesiz olur", "servis sonrasi hangi kontroller yapilir"],
  },
  {
    id: "problem_liquid_line_too_hot",
    trSubject: "likit hatti fazla isiniyor",
    deSubject: "die fluessigkeitsleitung zu warm wird",
    keywords: ["likit hatti sicak", "liquid line warm", "fluessigkeitsleitung warm"],
    causeTr: "subcool dusuklugu, kondenser yuksek yukte calisma veya hatin cevresel isidan etkilenmesidir",
    causeDe: "zu geringes Subcooling, hohe Belastung des Verfluessigers oder Waermeeintrag auf die Leitung",
    checkTr: "subcool olculur, hat guzergahi ve izolasyon ihtiyaci degerlendirilir",
    checkDe: "Subcooling gemessen und Leitungsfuehrung sowie eventueller Waermeeintrag bewertet werden",
    whyTr: "likit hat istikrarini kaybederse genlesme elemanina saglikli sivi gitmez",
    whyDe: "bei instabiler Fluessigkeitsleitung das Expansionsorgan keine saubere Fluessigversorgung erhaelt",
    mistakeTr: "yalniz basinç okuyup hat uzerindeki isi etkisini gormemektir",
    mistakeDe: "nur Druckwerte zu sehen und den Waermeeinfluss auf die Leitung zu ignorieren",
    suggestions: ["subcool neden onemli", "sight glass kabarcik ne anlatir", "kondenser neden kirlenir"],
  },
  {
    id: "problem_suction_line_sweating_wrongly",
    trSubject: "emis hatti anormal sekilde terliyor",
    deSubject: "die saugleitung unnormal schwitzt",
    keywords: ["emis hatti terliyor", "suction line sweating", "saugleitung schwitzt"],
    causeTr: "izolasyon eksigi, asiri dusuk superheat veya ortam yuksek nemi olabilir",
    causeDe: "fehlende Daemmung, sehr niedriger Superheat oder hohe Umgebungsfeuchte",
    checkTr: "izolasyon butunlugu, superheat ve terlemenin nerede basladigi incelenir",
    checkDe: "Daemmung, Superheat und Startpunkt der Kondensation geprueft werden",
    whyTr: "emiş hattinin davranisi evaporator beslenmesi ve ortam etkisi hakkinda bilgi verir",
    whyDe: "das Verhalten der Saugleitung viel ueber Verdampferfuellung und Umgebungsbedingungen verraten kann",
    mistakeTr: "terlemeyi normal sayip sivi donusu riskini dusunmemektir",
    mistakeDe: "Schwitzwasser als normal abzutun und Fluessigkeitsruecklauf nicht zu bedenken",
    suggestions: ["superheat nasil dusunulur", "kompresore sivi neden doner", "izolasyon neden onemli"],
  },
  {
    id: "problem_room_under_negative_pressure",
    trSubject: "oda kapisi zor aciliyor veya vakumluyor",
    deSubject: "die tuer schwer aufgeht oder der raum vakuum zieht",
    keywords: ["vakumluyor", "door hard open", "unterdruck im raum"],
    causeTr: "basinc dengeleme yetersizligi, taze hava gecisi olmamasi veya fan-akis dengesizligidir",
    causeDe: "fehlender Druckausgleich, keine Ausgleichsoeffnung oder unausgewogene Luftstroeme",
    checkTr: "kapida cekme etkisi, oda havalandirma duzeni ve dengeleme elemani varligi kontrol edilir",
    checkDe: "Sogwirkung an der Tuer, Luftwechsel und vorhandene Druckausgleichselemente geprueft werden",
    whyTr: "ozellikle hizli sicaklik dususlerinde basinc farki kapi kullanimini zorlastirabilir",
    whyDe: "besonders bei schnellen Temperaturveraenderungen ein Druckunterschied die Tuernutzung erschweren kann",
    mistakeTr: "kapı ayari bozuk sanip basinc dengesini dusunmemektir",
    mistakeDe: "nur die Tuereinstellung zu verdaechtigen und den Druckausgleich zu uebersehen",
    suggestions: ["kapi neden hava kacirir", "oda neden nem ceker", "kapı tasariminda ne onemlidir"],
  },
  {
    id: "problem_operator_error",
    trSubject: "sorun teknik degil kullanim kaynakli",
    deSubject: "das problem eher aus der nutzung stammt",
    keywords: ["kullanim hatasi", "operator error", "bedienfehler"],
    causeTr: "kapinin acik birakilmasi, urunun yanlis istiflenmesi, cok sicak mal girisi veya ayarlarla oynanmasidir",
    causeDe: "offenstehende Tuer, falsche Stapelung, zu warme Ware oder veraenderte Einstellungen durch den Bediener",
    checkTr: "kullanim aliskanligi, vardiya duzeni ve urun akis senaryosu teknik olculerle birlikte dinlenir",
    checkDe: "Nutzungsgewohnheiten, Schichtablaeufe und Warenfluss gemeinsam mit den Technikdaten ausgewertet werden",
    whyTr: "bir cok tekrar eden ariza aslinda cihazdan degil isletme sekline baglidir",
    whyDe: "viele wiederkehrende Stoerungen eher aus dem Betriebsablauf als aus echter Technik resultieren",
    mistakeTr: "sadece cihaza odaklanip operator kaynakli etkileri atlamaktir",
    mistakeDe: "nur auf die Technik zu schauen und den Bedienereinfluss zu vergessen",
    suggestions: ["kapi trafigi neden onemli", "urun istifi hava akisini nasil bozar", "bakim listesinde kullanici notu neden olmali"],
  },
  {
    id: "problem_alarm_after_power_cut",
    trSubject: "elektrik kesintisi sonrasi sistem dengesiz calisiyor",
    deSubject: "die anlage nach stromausfall instabil laeuft",
    keywords: ["elektrik kesintisi", "power cut", "stromausfall"],
    causeTr: "parametre sifirlanmasi, faz sirasi degisimi, basinc dengesi bozulmasi veya ardarda restarttir",
    causeDe: "verlorene Parameter, geaenderte Phasenfolge, fehlender Druckausgleich oder zu schnelle Wiederanlaeufe",
    checkTr: "kontrolor ayarlari, alarm hafizasi, faz sirasi ve yeniden start sekansi kontrol edilir",
    checkDe: "Reglerparameter, Alarmspeicher, Phasenfolge und Neustartsequenz geprueft werden",
    whyTr: "kesinti sonrasi sistem normalden farkli sarti tekrar kurmak zorunda kalir",
    whyDe: "die Anlage nach einem Stromausfall ihre Betriebsbedingungen neu aufbauen muss",
    mistakeTr: "enerji geldi diye her seyin eski haline dondugunu varsaymaktir",
    mistakeDe: "anzunehmen, dass nach Spannungsrueckkehr automatisch wieder alles normal ist",
    suggestions: ["faz sirasi neden onemli", "kompresor neden zor kalkar", "kontrolor ayarlari nasil kontrol edilir"],
  },
  {
    id: "problem_alarm_after_service",
    trSubject: "servis sonrasi yeni ariza basladi",
    deSubject: "nach dem service eine neue stoerung begann",
    keywords: ["servis sonrasi", "after service", "nach service"],
    causeTr: "vana pozisyonu, eksik sarj, soket unutulmasi, parametre degisimi veya hava alinmamis hat olabilir",
    causeDe: "Ventilstellung, unvollstaendige Fuellung, vergessener Stecker, geaenderter Parameter oder nicht sauber evakuierte Leitung",
    checkTr: "serviste dokunulan son noktalar geriye dogru adim adim kontrol edilir",
    checkDe: "die zuletzt beruehrten Punkte der Wartung rueckwaerts Schritt fuer Schritt geprueft werden",
    whyTr: "ariza zamani cok sey anlatir; servis sonrasi basladiysa once son mudahaleye bakilir",
    whyDe: "der Zeitpunkt der Stoerung viel verrät; wenn sie nach Service begann, schaut man zuerst auf die letzte Arbeit",
    mistakeTr: "yeni arizayi eski arizayla karistirip son mudahaleyi goz ardi etmektir",
    mistakeDe: "neue Stoerung mit dem alten Fehlerbild zu verwechseln und die letzte Intervention zu ignorieren",
    suggestions: ["vakum neden onemli", "servis vanasi nasil kontrol edilir", "gaz eksigi nasil anlasilir"],
  },
  {
    id: "problem_alarm_only_at_night",
    trSubject: "ariza sadece gece ortaya cikiyor",
    deSubject: "die stoerung nur nachts auftritt",
    keywords: ["gece ariza", "night problem", "nur nachts"],
    causeTr: "gece defrost zamani, dusen dis sicaklik, farkli kullanim duzeni veya elektrik kalitesi degisimidir",
    causeDe: "naechste Abtauzeiten, sinkende Aussentemperatur, veraenderte Nutzung oder andere Netzqualitaet in der Nacht",
    checkTr: "alarm saati ile defrost, gece vardiyasi ve dis ortam bir arada okunur",
    checkDe: "Alarmzeit mit Abtauung, Nachtschicht und Aussenbedingungen zusammen ausgewertet wird",
    whyTr: "bazi sorunlar ancak belirli zaman penceresinde ortaya cikan kosullarla gorunur",
    whyDe: "manche Fehler nur unter speziellen Zeitbedingungen sichtbar werden",
    mistakeTr: "gunduz baktim duzgun diyerek arizayi kapatmaktir",
    mistakeDe: "den Fall zu schliessen, nur weil tagsueber alles normal wirkt",
    suggestions: ["alarm veriyor ama sonra duzeliyor", "defrost ayari nasil kontrol edilir", "dis ortam cihazı nasil etkiler"],
  },
  {
    id: "problem_humidity_after_door_open",
    trSubject: "kapi acilinca iceri sis doluyor",
    deSubject: "beim tueroeffnen nebel in den raum zieht",
    keywords: ["sis", "fog", "nebel", "kapi acilinca sis"],
    causeTr: "ic-dis hava farki, yuksek nemli ortam, negatif oda ve yogun kapi trafigidir",
    causeDe: "grosser Klimaunterschied, hohe Umgebungsfeuchte, Minusraum und haeufige Tueroeffnungen",
    checkTr: "kapi trafigi, on oda varligi, hava perdesi veya operasyon akisi degerlendirilir",
    checkDe: "Tuernutzung, Schleusensituation, Luftvorhang und Betriebsablauf bewertet werden",
    whyTr: "sis goruntusu aslinda yogusmanin ve nem tasinmasinin gozle gorunen halidir",
    whyDe: "Nebel die sichtbare Form von Feuchteeintrag und Kondensation ist",
    mistakeTr: "bunu normal sayip zamanla buzlanmaya donusmesini beklemektir",
    mistakeDe: "das als normal hinzunehmen und die spaetere Vereisung in Kauf zu nehmen",
    suggestions: ["kapi trafigi neden onemli", "negatif depoda nelere dikkat edilir", "kapi sizdirmazligi neden onemli"],
  },
  {
    id: "problem_controller_wrong_language_or_mode",
    trSubject: "kontrolor yanlis modda calisiyor",
    deSubject: "der regler im falschen modus laeuft",
    keywords: ["yanlis mod", "controller mode", "falscher modus"],
    causeTr: "sok yerine muhafaza modu, fan gecikmesi ayari veya defrost lojigi yanlis secilmis olabilir",
    causeDe: "Schock- statt Lagermodus, falsche Ventilatorverzoegerung oder unpassende Abtaulogik",
    checkTr: "uygulama amaci ile kontrolor modunun uyumlu olup olmadigi okunur",
    checkDe: "geprueft wird, ob der Reglermodus wirklich zur Anwendung passt",
    whyTr: "dogru cihaz yanlis modda calistiginda sahada yanlis cihaz gibi davranir",
    whyDe: "selbst das richtige Geraet im falschen Modus wie eine falsch gewaehlte Anlage wirkt",
    mistakeTr: "kontrolor menusu sabit diye uygulamayi buna uydurmaya calismaktir",
    mistakeDe: "die Anwendung an ein zufaelliges Reglermenue anzupassen statt umgekehrt",
    suggestions: ["kontrolor ayarlari neden onemli", "sok oda ile muhafaza odasi farki nedir", "sensor yeri neden onemli"],
  },
  {
    id: "problem_fan_delay_wrong",
    trSubject: "fan gecikme ayari yanlis",
    deSubject: "die ventilatorverzoegerung falsch eingestellt ist",
    keywords: ["fan gecikme", "fan delay", "ventilatorverzoegerung"],
    causeTr: "defrost sonrasi fanin cok erken ya da cok gec devreye girmesidir",
    causeDe: "die Ventilatoren nach der Abtauung zu frueh oder zu spaet freigegeben werden",
    checkTr: "defrost bitimi ile fan baslangici arasindaki sure ve coil sicakligi birlikte izlenir",
    checkDe: "Zeit zwischen Abtauende und Ventilatorstart zusammen mit der Registertemperatur beobachtet wird",
    whyTr: "fan erken acarsa su ve sicak hava urune gider, gec acarsa sogutma gecikir",
    whyDe: "ein zu frueher Start Wasser und Warmluft auf die Ware bringt, ein zu spaeter Start aber Leistung kostet",
    mistakeTr: "yalniz oda hedef sicakligina bakip gecikme mantigini gormemektir",
    mistakeDe: "nur auf den Sollwert zu schauen und die Ventilatorlogik zu ignorieren",
    suggestions: ["defrost neden onemli", "fan buz yaparsa ne olur", "urun neden islanir"],
  },
  {
    id: "problem_bad_brazing",
    trSubject: "kotu lehim nedeniyle sorun var",
    deSubject: "schlechte loetstellen probleme verursachen",
    keywords: ["kotu lehim", "bad brazing", "schlechte loetung"],
    causeTr: "azotsuz lehim, kirli boru ucu, yetersiz isil islem veya mekanik gerilimdir",
    causeDe: "Loeten ohne Stickstoff, verschmutzte Rohrenden, schlechte Waermeeinbringung oder mechanische Spannung",
    checkTr: "kacak, oksit, renk degisimi ve hat ici daralma belirtileri aranir",
    checkDe: "Leckage, Oxid, Verfaerbung und innere Verengung der Leitung geprueft werden",
    whyTr: "lehim hatasi bazen hemen degil zamanla kacak ve tikanma olarak duser",
    whyDe: "Loetfehler nicht immer sofort, sondern spaeter als Leckage oder Verstopfung auftreten",
    mistakeTr: "yalniz dis goruntuye bakip boru ici temizligini hesaba katmamaktir",
    mistakeDe: "nur die aeußere Naht zu bewerten und den Innenzustand zu vergessen",
    suggestions: ["vakum ve azot testi neden onemli", "filter drier neden tikanir", "gaz eksigi nasil anlasilir"],
  },
  {
    id: "problem_wrong_pipe_size",
    trSubject: "boru capi yanlis secilmis",
    deSubject: "der rohrdurchmesser falsch gewaehlt ist",
    keywords: ["boru capi", "wrong pipe size", "rohrdurchmesser"],
    causeTr: "hesapsiz saha karari, uzun hati kisa hat gibi dusunmek veya yag donusunu hesaba katmamaktir",
    causeDe: "ungerechnete Feldentscheidung, Behandlung langer Leitungen wie kurzer oder ignorierter Oelruecklauf",
    checkTr: "hat uzunlugu, kot farki ve mevcut capin katalog mantigina uyumu degerlendirilir",
    checkDe: "Leitungslaenge, Hoehenunterschied und Eignung des gewaehlten Durchmessers zur Anwendung bewertet werden",
    whyTr: "boru capi sogutma devresinin basinc kaybi ve yag davranisini birlikte belirler",
    whyDe: "der Rohrdurchmesser zugleich Druckverlust und Oelruecklauf im System bestimmt",
    mistakeTr: "elde hangi boru varsa onunla isi bitirmeye calismaktir",
    mistakeDe: "die vorhandene Rohrgroesse zu verwenden, statt die richtige auszuwaehlen",
    suggestions: ["yag donusu neden onemli", "dusuk basinc neden olur", "bakir borulama nasil yapilir"],
  },
  {
    id: "problem_case_heater_or_anti_sweat",
    trSubject: "terleme rezistansi calismiyor",
    deSubject: "die anti sweat heizung nicht funktioniert",
    keywords: ["anti sweat", "terleme rezistansi", "anti schwitz heizung"],
    causeTr: "rezistans kopuklugu, enerji yoklugu veya kontrol cikisinin bozulmasidir",
    causeDe: "Heizungsunterbrechung, fehlende Versorgung oder ein defekter Schaltausgang",
    checkTr: "rezistans devresi, enerji ve yogusmanin tam hangi hatta oldugu incelenir",
    checkDe: "Heizkreis, Spannungsversorgung und exakte Lage der Kondensation geprueft werden",
    whyTr: "bu rezistanslar yuzey sicakligini yogusma altina dusurmemek icin vardir",
    whyDe: "diese Heizungen die Oberflaechentemperatur ueber dem Taupunkt halten sollen",
    mistakeTr: "terlemeyi yalniz hava nemine baglamaktir",
    mistakeDe: "Kondensation nur der Luftfeuchte zuzuschreiben",
    suggestions: ["panel neden terler", "kapi rezistansi ne zaman gerekir", "yuksek nem neden olur"],
  },
  {
    id: "problem_dirty_evaporator",
    trSubject: "evaporator kirli oldugu icin verim dusuyor",
    deSubject: "der verdampfer verschmutzt ist und leistung verliert",
    keywords: ["evaporator kirli", "dirty evaporator", "verdampfer verschmutzt"],
    causeTr: "toz, yag, urun partikulleri veya yikama sonrasi birikimdir",
    causeDe: "Staub, Fett, Produktpartikel oder Rueckstaende nach Reinigung",
    checkTr: "serpantin yuzeyi, hava gecis direnci ve fan cekisi birlikte kontrol edilir",
    checkDe: "Registeroberflaeche, Luftwiderstand und Ventilatorleistung gemeinsam kontrolliert werden",
    whyTr: "kirli evaporator soguk olabilir ama havaya isi geciremez",
    whyDe: "ein verschmutzter Verdampfer zwar kalt sein kann, aber die Kaelte nicht mehr sauber an die Luft uebergibt",
    mistakeTr: "yalniz gaz tarafini suclayip serpantin temizligini ihmal etmektir",
    mistakeDe: "nur den Kaeltekreis zu verdaechtigen und die Registerreinigung zu vernachlaessigen",
    suggestions: ["hava akisi neden duser", "periyodik bakimda ne kontrol edilir", "evaporator neden buz tutar"],
  },
  {
    id: "problem_alarm_due_to_ambient_heat",
    trSubject: "sicak havalarda sistem daha cok hata veriyor",
    deSubject: "die anlage bei hitze haeufiger stoert",
    keywords: ["sicak havada", "summer issue", "bei hitze"],
    causeTr: "kondenser kapasitesinin sinira gelmesi, hava geri donusu veya yuksek cevre yukudur",
    causeDe: "Verfluessigergrenze, Rueckansaugung warmer Luft oder sehr hohe Umgebungslast",
    checkTr: "ozellikle oglen saatleri, gunes etkisi, kondenser cevresi ve basma basinci birlikte okunur",
    checkDe: "Mittagszeit, Sonneneinstrahlung, Umfeld des Verfluessigers und Hochdruck gemeinsam ausgewertet werden",
    whyTr: "yaz kosullarinda zayif taraflar daha cabuk ortaya cikar",
    whyDe: "unter Sommerbedingungen schwache Systemstellen schneller sichtbar werden",
    mistakeTr: "kis testinde sorun yoktu diye yaz davranisini ayni sanmaktir",
    mistakeDe: "vom Wintertest direkt auf das Sommerverhalten zu schliessen",
    suggestions: ["kondenser yeri neden onemli", "yuksek basinc neden olur", "dis unite etrafinda bosluk neden gerekir"],
  },
  {
    id: "problem_alarm_due_to_frequent_washes",
    trSubject: "sik yikama nedeniyle tekrar eden ariza var",
    deSubject: "haeufige reinigung wiederkehrende stoerungen verursacht",
    keywords: ["sik yikama", "frequent wash", "haeufige reinigung"],
    causeTr: "su girisi, korozyon, soket zayiflamasi ve drenaj kirlenmesidir",
    causeDe: "Wassereintritt, Korrosion, geschwaechte Steckverbindungen und verschmutzte Ablaeufe",
    checkTr: "hangi ekipmanin su aldigi, koruma sinifi ve yikama yontemi birlikte degerlendirilir",
    checkDe: "welche Baugruppe Wasser bekommt, welche Schutzart vorhanden ist und wie gereinigt wird",
    whyTr: "yikama dogru planlanmazsa hijyen kazanirken teknik guvenilirlik kaybedilir",
    whyDe: "bei falsch geplanter Reinigung Hygiene gewonnen, aber technische Zuverlaessigkeit verloren wird",
    mistakeTr: "yikama ekibiyle teknik sinirlari paylasmamaktir",
    mistakeDe: "die Reinigungsprozesse nicht mit den technischen Grenzen abzustimmen",
    suggestions: ["yikama sonrasi ariza neden cikar", "sut urunleri odasinda neye dikkat edilir", "hijyen ve elektrik nasil birlikte dusunulur"],
  },
];

const selectedTopicIds = [
  "problem_room_not_cooling",
  "problem_room_cools_slow",
  "problem_temperature_unstable",
  "problem_compressor_not_starting",
  "problem_compressor_trips_thermal",
  "problem_high_pressure",
  "problem_low_pressure",
  "problem_evaporator_icing",
  "problem_condenser_dirty",
  "problem_fan_not_running",
  "problem_wrong_fan_direction",
  "problem_defrost_not_working",
  "problem_drain_freezing",
  "problem_door_leak",
  "problem_panel_sweating",
  "problem_floor_icing",
  "problem_door_traffic",
  "problem_airflow_blocked_by_loading",
  "problem_sensor_wrong_place",
  "problem_expansion_valve_wrong",
  "problem_refrigerant_shortage",
  "problem_refrigerant_overcharge",
  "problem_filter_drier_blocked",
  "problem_oil_return",
  "problem_short_cycle",
  "problem_compressor_noise",
  "problem_liquid_slugging",
  "problem_high_discharge_temp",
  "problem_crankcase_heater",
  "problem_phase_sequence",
  "problem_voltage_drop",
  "problem_loose_terminal",
  "problem_bad_condenser_location",
  "problem_bad_evaporator_location",
  "problem_low_humidity_drying",
  "problem_high_humidity_condensation",
  "problem_door_heater_failure",
  "problem_defrost_heater_failure",
  "problem_solenoid_valve",
  "problem_sight_glass_bubbles",
  "problem_pressure_switch_trip",
  "problem_control_settings",
  "problem_ice_after_defrost",
  "problem_alarm_but_room_ok",
  "problem_pressure_equalization",
  "problem_product_freezing_in_plus_room",
  "problem_product_not_reaching_safe_temp",
  "problem_alarm_from_bad_defrost_end",
  "problem_alarm_after_power_cut",
  "problem_alarm_after_service",
];

const topicById = new Map(allTopics.map((topic) => [topic.id, topic]));
const topics = selectedTopicIds.map((topicId) => {
  const topic = topicById.get(topicId);
  if (!topic) {
    throw new Error(`Unknown topic id: ${topicId}`);
  }
  return topic;
});

if (topics.length !== 50) {
  throw new Error(`Expected 50 topics, got ${topics.length}`);
}

const entries = topics.map(buildEntry);

const totalQuestionCount = entries.reduce((sum, entry) => sum + entry.tr_questions.length + entry.de_questions.length, 0);
if (totalQuestionCount !== 1000) {
  throw new Error(`Expected 1000 questions, got ${totalQuestionCount}`);
}

fs.writeFileSync(OUTPUT, JSON.stringify(entries, null, 2), "utf-8");
console.log(`Generated ${entries.length} troubleshooting entries with ${totalQuestionCount} questions -> ${OUTPUT}`);
