const fs = require("fs");
const path = require("path");

const OUTPUT = path.join(__dirname, "drc_man_gases_faq.json");
const SOURCE_SUMMARY = "DRC MAN sogutucu gaz uzmani egitimi";

const trTemplates = [
  (s) => `${s} nasil dusunulur`,
  (s) => `${s} neye gore secilir`,
  (s) => `${s} neden onemli`,
  (s) => `${s} ile ilgili usta neye bakar`,
  (s) => `${s} konusunda en sik hata nedir`,
  (s) => `${s} kullanilirsa nelere dikkat edilir`,
  (s) => `${s} ariza ve performansi nasil etkiler`,
  (s) => `${s} sahada nasil yorumlanir`,
  (s) => `${s} icin servis sirasi ne olur`,
  (s) => `${s} hakkinda detayli acikla`,
];

const deTemplates = [
  (s) => `wie denkt man ueber ${s}`,
  (s) => `wonach waehlt man ${s} aus`,
  (s) => `warum ist ${s} wichtig`,
  (s) => `worauf achtet ein meister bei ${s}`,
  (s) => `was ist der haeufigste fehler bei ${s}`,
  (s) => `worauf muss man bei ${s} achten`,
  (s) => `wie beeinflusst ${s} stoerung und leistung`,
  (s) => `wie interpretiert man ${s} im feld`,
  (s) => `wie ist die service reihenfolge bei ${s}`,
  (s) => `erklaere ${s} im detail`,
];

function buildAnswerTr(topic, family) {
  return `${topic.trSubject} konusunda sogutucu gaz uzmani once uygulamayi netlestirir. Bu baslikta tipik ana nokta ${topic.focusTr}; bunun yaninda ${family.causeTr}. Ilk kontrolde ${family.checkTr}. Bunun teknik sebebi ${topic.whyFocusTr}; ayrica ${family.whyTr}. En sik hata ise ${family.mistakeTr}. Saglam saha mantigi, gazi ismine gore degil; guvenlik, uygulama, yag uyumu, basinc seviyesi ve servis kosuluna gore degerlendirmektir.`;
}

function buildAnswerDe(topic, family) {
  return `Beim Thema ${topic.deSubject} klaert ein Kaeltemittel-Spezialist zuerst die Anwendung. Der zentrale Punkt ist hier ${topic.focusDe}; zusaetzlich gilt ${family.causeDe}. In der Erstpruefung werden ${family.checkDe}. Der technische Hintergrund ist ${topic.whyFocusDe}; ausserdem gilt ${family.whyDe}. Ein sehr haeufiger Fehler besteht darin, dass ${family.mistakeDe}. Saubere Feldarbeit bewertet Kaeltemittel nicht nur nach Namen, sondern nach Sicherheit, Anwendung, Oelvertraeglichkeit, Druckniveau und Servicebedingungen.`;
}

function buildEntry(topic, family) {
  return {
    id: topic.id,
    tr_subject: topic.trSubject,
    de_subject: topic.deSubject,
    source_summary: SOURCE_SUMMARY,
    keywords: [topic.trSubject, topic.deSubject, ...(topic.extraKeywords || [])],
    tr_questions: trTemplates.map((template) => template(topic.trSubject)),
    de_questions: deTemplates.map((template) => template(topic.deSubject)),
    tr_answer: buildAnswerTr(topic, family),
    de_answer: buildAnswerDe(topic, family),
    suggestions: topic.suggestions || family.suggestions || [],
  };
}

const families = [
  {
    causeTr: "her sogutucu akiskanin her oda tipi ve her kompresor icin uygun olmamasidir",
    causeDe: "nicht jedes Kaeltemittel zu jeder Anwendung und jedem Verdichter passt",
    checkTr: "oda tipi, hedef sicaklik, kapasite, kompresor tipi ve servis guvenligi birlikte okunur",
    checkDe: "Raumtyp, Zieltemperatur, Leistung, Verdichterbauart und Servicesicherheit gemeinsam bewertet werden",
    whyTr: "gaz secimi yalniz katalog degil, uygulamanin butun karakterini belirler",
    whyDe: "die Wahl des Kaeltemittels nicht nur Katalogwerte, sondern den gesamten Anwendungscharakter bestimmt",
    mistakeTr: "hangi gaz daha ucuzsa onu uygulamaya uydurmaya calismaktir",
    mistakeDe: "das billigste Kaeltemittel in eine unpassende Anwendung pressen zu wollen",
    suggestions: ["A1 A2L A3 farki nedir", "yag uyumu neden onemli", "retrofit nasil planlanir"],
    variants: [
      {
        id: "gas_choice_plus_room",
        trSubject: "arti muhafaza odasi icin gaz secimi",
        deSubject: "die kaeltemittelwahl fuer plus-kuehlraeume",
        extraKeywords: ["plus room refrigerant", "arti oda gaz secimi"],
        focusTr: "orta sicaklik uygulamasinda verim, servis kolayligi ve guvenligin dengelenmesi",
        focusDe: "im Plusbereich Effizienz, Servicefreundlichkeit und Sicherheit ausbalanciert werden",
        whyFocusTr: "arti odada hedef yalniz sogutmak degil, urunu sabit ve kontrollu muhafaza etmektir",
        whyFocusDe: "im Plusraum nicht nur Kaelte, sondern stabile und kontrollierte Lagerung entscheidend ist",
      },
      {
        id: "gas_choice_negative_room",
        trSubject: "negatif depo icin gaz secimi",
        deSubject: "die kaeltemittelwahl fuer tiefkuehlraeume",
        extraKeywords: ["negative room refrigerant", "negatif oda gaz"],
        focusTr: "dusuk evaporasyon sicakliginda basinc, yag donusu ve kapasitenin korunmasi",
        focusDe: "bei tiefer Verdampfung Druckniveau, Oelruecklauf und Leistung stabil bleiben muessen",
        whyFocusTr: "negatif depoda gazin dusuk sicaklik davranisi kompresor omrunu dogrudan etkiler",
        whyFocusDe: "im Tiefkuehlbereich das Tieftemperaturverhalten des Kaeltemittels direkt den Verdichter belastet",
      },
      {
        id: "gas_choice_shock_room",
        trSubject: "sok oda icin gaz secimi",
        deSubject: "die kaeltemittelwahl fuer schockfrostanlagen",
        extraKeywords: ["shock room refrigerant", "sok oda gaz"],
        focusTr: "yuksek ani yukte kapasiteyi ve kompresor guvenligini koruyacak secim yapmak",
        focusDe: "bei hoher Spitzenlast Leistung und Verdichtersicherheit gleichzeitig sicherzustellen",
        whyFocusTr: "sok oda gaz secimi normal muhafaza odasindan daha agresif kosullara gore dusunulur",
        whyFocusDe: "Schockraumanlagen unter deutlich haerteren Bedingungen als Lagerraeume arbeiten",
      },
      {
        id: "gas_choice_small_split",
        trSubject: "kucuk split sogutma grubu icin gaz secimi",
        deSubject: "die kaeltemittelwahl fuer kleine split-kuehlgruppen",
        extraKeywords: ["split refrigerant", "split gaz secimi"],
        focusTr: "kompakt sistemlerde servis kolayligi, sarj miktari ve guvenlik sinifinin dogru kurulmasi",
        focusDe: "bei kompakten Systemen Servicefreundlichkeit, Fuellmenge und Sicherheitsklasse passend zu waehlen",
        whyFocusTr: "kucuk sistemde sarj ve kurulum detaylari buyuk sistemden daha hassas olabilir",
        whyFocusDe: "in kleinen Anlagen Fuellmenge und Einbau oft noch empfindlicher sind als in grossen Systemen",
      },
      {
        id: "gas_choice_retrofit_project",
        trSubject: "mevcut sisteme yerine gececek gaz secimi",
        deSubject: "die ersatzwahl fuer ein bestehendes system",
        extraKeywords: ["retrofit refrigerant choice", "yerine gececek gaz"],
        focusTr: "eski sisteme en az mekanik riskle uyacak alternatifin secilmesi",
        focusDe: "fuer ein bestehendes System ein moeglichst risikoarmer Ersatz gefunden wird",
        whyFocusTr: "retrofitte kagit uzerindeki uyum kadar saha montaj ve yag uyumu da kritiktir",
        whyFocusDe: "beim Retrofit neben Datenblattwerten besonders Oel, Ventil und Feldbedingungen entscheidend sind",
      },
    ],
  },
  {
    causeTr: "gaz guvenlik sinifinin sahadaki montaj ve servis davranisini belirlemesidir",
    causeDe: "die Sicherheitsklasse des Kaeltemittels Montage und Service im Feld direkt bestimmt",
    checkTr: "A1, A2L, A3 veya toksik/ozel sinif mantigi, ortam havalandirmasi ve atesleme riski birlikte degerlendirilir",
    checkDe: "A1, A2L, A3 oder Sonderklassen zusammen mit Belueftung und Zundrisiko bewertet werden",
    whyTr: "ayni kapasiteyi veren iki gazin servis riski ayni olmayabilir",
    whyDe: "zwei Kaeltemittel koennen aehnliche Leistung, aber sehr unterschiedliche Service-Risiken haben",
    mistakeTr: "basinca veya verime bakip guvenlik sinifini arka plana atmak",
    mistakeDe: "nur auf Leistung und Druck zu schauen und die Sicherheitsklasse zu vernachlaessigen",
    suggestions: ["R290 kullanirken neye dikkat edilir", "A2L ile A3 farki nedir", "silindir guvenligi nasil saglanir"],
    variants: [
      {
        id: "gas_safety_a1",
        trSubject: "A1 sinifi gazlarin mantigi",
        deSubject: "die logik von A1-kaeltemitteln",
        extraKeywords: ["A1 refrigerants", "A1 sinifi"],
        focusTr: "yanicilik dusuk oldugu icin servis kolay ama cevresel ve uygulama kriterleri yine onemli kalir",
        focusDe: "durch geringe Entflammbarkeit Service einfacher ist, aber Anwendung und Umweltaspekte weiter wichtig bleiben",
        whyFocusTr: "A1 guvenli gorunse de her sahaya otomatik dogru secim demek degildir",
        whyFocusDe: "A1 nicht automatisch bedeutet, dass das Mittel fuer jede Anlage ideal ist",
      },
      {
        id: "gas_safety_a2l",
        trSubject: "A2L gazlarla calisma mantigi",
        deSubject: "das arbeiten mit A2L-kaeltemitteln",
        extraKeywords: ["A2L refrigerants", "hafif yanici gaz"],
        focusTr: "dusuk ama gercek bir yanicilik riskinin servis disiplinine yansitilmasi",
        focusDe: "eine geringe, aber reale Entzuendbarkeit sauber in Serviceprozesse zu uebersetzen",
        whyFocusTr: "A2L grubunda alet, kacagi kontrol etme ve havalandirma daha sistemli dusunulur",
        whyFocusDe: "bei A2L Werkzeug, Lecksuche und Belueftung systematischer geplant werden muessen",
      },
      {
        id: "gas_safety_a3",
        trSubject: "A3 gazlarla calisma mantigi",
        deSubject: "das arbeiten mit A3-kaeltemitteln",
        extraKeywords: ["A3 refrigerants", "yuksek yanici gaz", "yuksek yanici gaz"],
        focusTr: "yuksek yanicilik sebebiyle montaj, servis ve dolumda daha sert disiplin kurmak",
        focusDe: "wegen hoher Entflammbarkeit Montage, Service und Fuellung deutlich strenger zu fuehren",
        whyFocusTr: "A3 gazlarda kucuk bir ihmal bile buyuk saha riskine donebilir",
        whyFocusDe: "bei A3-Kaeltemitteln schon kleine Nachlaessigkeiten zu ernsten Feldrisiken werden koennen",
      },
      {
        id: "gas_safety_flammability_workflow",
        trSubject: "yanici gazlarda servis sirasi",
        deSubject: "die service-reihenfolge bei brennbaren kaeltemitteln",
        extraKeywords: ["flammable workflow", "yanici gaz servis"],
        focusTr: "atesleme kaynaklarini dislayip havalandirma ve geri kazanimi planli yapmak",
        focusDe: "Zundquellen auszuschliessen und Belueftung plus Rueckgewinnung planvoll zu organisieren",
        whyFocusTr: "servis sirasi dogru kurulmazsa teknik hata olmasa bile guvenlik problemi dogar",
        whyFocusDe: "ohne klare Service-Reihenfolge auch bei technisch richtiger Arbeit ein Sicherheitsproblem entstehen kann",
      },
      {
        id: "gas_safety_cylinder_handling",
        trSubject: "gaz tupu ve silindir guvenligi",
        deSubject: "die sicherheit von flaschen und zylindern",
        extraKeywords: ["cylinder handling", "gaz tupu", "silindir guvenligi"],
        focusTr: "silindiri depolama, tasima, tarti ve baglanti sirasinda guvenli yonetmek",
        focusDe: "Flaschen bei Lagerung, Transport, Waegung und Anschluss sicher zu handhaben",
        whyFocusTr: "dogru olmayan silindir kullanimi saha kazasina ve yanlis sarja yol acar",
        whyFocusDe: "falsche Flaschenhandhabung sowohl Sicherheitsprobleme als auch Fehlfuellungen erzeugen kann",
      },
    ],
  },
  {
    causeTr: "gaz ile yag uyumunun kompresor guvenligi icin belirleyici olmasidir",
    causeDe: "die Oelvertraeglichkeit mit dem Kaeltemittel fuer die Verdichtersicherheit entscheidend ist",
    checkTr: "mevcut yag tipi, kompresor tavsiyesi, retrofit gecmisi ve donus davranisi birlikte okunur",
    checkDe: "vorhandenes Oel, Verdichterfreigabe, Retrofit-Historie und Ruecklaufverhalten gemeinsam bewertet werden",
    whyTr: "uyumsuz yag sadece yaglama degil, valf ve donus davranisini da bozar",
    whyDe: "unpassendes Oel nicht nur Schmierung, sondern auch Ventil- und Ruecklaufverhalten stoert",
    mistakeTr: "gazi degistirip yagi sorgulamamaktir",
    mistakeDe: "das Kaeltemittel zu wechseln, ohne das Oel ernsthaft zu pruefen",
    suggestions: ["POE neden kullanilir", "mineral yag ne zaman sorun olur", "retrofitte yag nasil dusunulur"],
    variants: [
      {
        id: "gas_oil_poe",
        trSubject: "POE yag ile gaz uyumu",
        deSubject: "die vertraeglichkeit von POE-oel und kaeltemittel",
        extraKeywords: ["POE oil", "POE yag"],
        focusTr: "ozellikle HFC ve HFO tabanli sistemlerde POE yag davranisinin dogru kurulmasi",
        focusDe: "vor allem bei HFC- und HFO-Systemen das Verhalten von POE-Oel sauber zu beruecksichtigen",
        whyFocusTr: "POE higroskopiktir; nemle iliskisi servis kalitesini direkt etkiler",
        whyFocusDe: "POE hygroskopisch ist und Feuchte deshalb direkt zur Servicequalitaet gehoert",
      },
      {
        id: "gas_oil_mineral",
        trSubject: "mineral yag hangi gazlarda mantiklidir",
        deSubject: "wann minerales oel sinnvoll ist",
        extraKeywords: ["mineral oil", "mineral yag"],
        focusTr: "eski nesil veya belirli uygulamalarda mineral yagin halen gecerli olmasi",
        focusDe: "in aelteren oder speziellen Anwendungen Mineraloel weiter relevant sein kann",
        whyFocusTr: "mineral yag uyumsuz gazla kullanilirsa donus ve kapasite sorunu baslar",
        whyFocusDe: "Mineraloel mit unpassendem Kaeltemittel Ruecklauf- und Leistungsprobleme erzeugt",
      },
      {
        id: "gas_oil_ab",
        trSubject: "alkylbenzene yag ne zaman dusunulur",
        deSubject: "wann alkylbenzol-oel in frage kommt",
        extraKeywords: ["alkylbenzene oil", "AB oil", "alkylbenzene yag"],
        focusTr: "belirli retrofit ve gecis projelerinde AB yagin ara cozum mantigi",
        focusDe: "in bestimmten Retrofit- oder Uebergangsprojekten Alkylbenzol als Zwischenloesung zu bewerten",
        whyFocusTr: "AB yag bazen gecis mantiginda ise yarar ama her projeye genellenemez",
        whyFocusDe: "AB-Oel in Uebergangsfaellen hilfreich sein kann, aber nicht pauschal passt",
      },
      {
        id: "gas_oil_return_behavior",
        trSubject: "gaz degisince yag donusu neden degisir",
        deSubject: "warum sich der oelruecklauf beim kaeltemittelwechsel aendert",
        extraKeywords: ["oil return with refrigerant change", "gaz degisince yag donusu"],
        focusTr: "yag cozulurlugu ve akiskan hizinin gazla birlikte farkli davranmasi",
        focusDe: "Oelloeslichkeit und Stroemungsverhalten sich mit dem Kaeltemittel veraendern",
        whyFocusTr: "ayni kompresor farkli gazla ayni yag davranisini vermeyebilir",
        whyFocusDe: "derselbe Verdichter mit anderem Kaeltemittel nicht denselben Oelruecklauf zeigt",
      },
      {
        id: "gas_oil_retrofit_flush",
        trSubject: "retrofitte yag degisimi ve flushing",
        deSubject: "oelwechsel und spuelen beim retrofit",
        extraKeywords: ["retrofit oil change", "flush retrofit"],
        focusTr: "eski yag ve yeni gaz arasindaki geciste ne kadar temizlik ve degisim gerektigini dusunmek",
        focusDe: "beim Wechsel von altem Oel zu neuem Kaeltemittel den Reinigungs- und Wechselbedarf sauber abzuschaetzen",
        whyFocusTr: "eksik yag gecisi sonraki arizalari sessizce buyutebilir",
        whyFocusDe: "ein unvollstaendiger Oelwechsel spaetere Probleme schleichend vergroessern kann",
      },
    ],
  },
  {
    causeTr: "saf gaz ile karisim gazlarin dolum davranisinin farkli olmasidir",
    causeDe: "reine Kaeltemittel und Mischungen sich beim Fuellen unterschiedlich verhalten",
    checkTr: "gaz saf mi karisim mi, silindir pozisyonu, tarti ve sarj sekli birlikte dusunulur",
    checkDe: "reines Kaeltemittel oder Gemisch, Flaschenlage, Waage und Fuellmethode zusammen betrachtet werden",
    whyTr: "yanlis dolum yontemi gaz kompozisyonunu bile bozabilir",
    whyDe: "eine falsche Fuellmethode sogar die Zusammensetzung des Gemischs veraendern kann",
    mistakeTr: "her gazi ayni sekilde doldurmak",
    mistakeDe: "jedes Kaeltemittel gleich zu fuellen",
    suggestions: ["karisim gazlar neden likit sarj edilir", "saf gaz buhar sarj edilir mi", "glide nedir"],
    variants: [
      {
        id: "gas_charging_blend_liquid",
        trSubject: "karisim gazlarda likit sarj mantigi",
        deSubject: "das fluessigfuellen von mischkaeltemitteln",
        extraKeywords: ["blend liquid charge", "likit sarj karisim"],
        focusTr: "karisim gazda fraksiyon ayrilmasini onlemek icin likit taraftan sarj yapmak",
        focusDe: "bei Gemischen Fluessigfuellung zu nutzen, um Fraktionierung zu vermeiden",
        whyFocusTr: "karisim gaz buhar fazinda kompozisyon kaybedebilir",
        whyFocusDe: "ein Gemisch in der Gasphase seine Zusammensetzung veraendern kann",
      },
      {
        id: "gas_charging_pure_refrigerant",
        trSubject: "saf gazlarda sarj mantigi",
        deSubject: "das fuellverhalten bei reinen kaeltemitteln",
        extraKeywords: ["pure refrigerant charging", "saf gaz sarj"],
        focusTr: "tek bilesenli gazlarda kompozisyon kaygisinin olmamasi ama yine de kontrollu sarj gerekmesi",
        focusDe: "bei reinen Stoffen keine Fraktionierung droht, aber trotzdem kontrolliertes Fuellen noetig ist",
        whyFocusTr: "saf gaz kolay gibi gorunse de yine tarti ve sistem mantigi ister",
        whyFocusDe: "auch reines Kaeltemittel trotz einfacherem Verhalten exakt eingewogen werden muss",
      },
      {
        id: "gas_charging_cylinder_position",
        trSubject: "silindirin dik veya ters kullanimi",
        deSubject: "die richtige flaschenposition beim fuellen",
        extraKeywords: ["cylinder upright", "silindir pozisyonu"],
        focusTr: "hangi gazda silindirin dik, hangi durumda kontrollu likit cekisle kullanilacagini bilmek",
        focusDe: "zu wissen, wann die Flasche aufrecht und wann kontrolliert fluessig genutzt wird",
        whyFocusTr: "yanlis silindir pozisyonu sarj davranisini ve guvenligi etkiler",
        whyFocusDe: "eine falsche Flaschenlage Fuellung und Sicherheit beeinflusst",
      },
      {
        id: "gas_charging_by_weight",
        trSubject: "gaz sarjinda tarti kullanma mantigi",
        deSubject: "das fuellen nach gewicht",
        extraKeywords: ["charge by weight", "tarti ile sarj"],
        focusTr: "gaz dolumunda tartiyi temel referans almak",
        focusDe: "bei der Fuellung das Gewicht als Primaerreferenz zu benutzen",
        whyFocusTr: "basinc yalanci yorum verebilir ama tarti gercek aktarilan miktari gosterir",
        whyFocusDe: "Druckwerte koennen taeuschen, das Gewicht zeigt aber die reale eingefuellte Menge",
      },
      {
        id: "gas_charging_topup_risk",
        trSubject: "karisim gaza sadece ustune ekleme riski",
        deSubject: "das risiko des einfachen nachfuellens bei gemischen",
        extraKeywords: ["top up blend", "ustune gaz ekleme"],
        focusTr: "kacakli veya fraksiyon bozulmus karisim gaza rastgele ekleme yapmanin riski",
        focusDe: "bei leckenden oder fraktionierten Gemischen einfach nur nachzufuellen",
        whyFocusTr: "ustune ekleme bazen sistemde ilk karisimi geri getirmez",
        whyFocusDe: "Nachfuellen nicht immer die urspruengliche Mischung wiederherstellt",
      },
    ],
  },
  {
    causeTr: "glide ve karisim davranisinin basinc-isi yorumunu degistirmesidir",
    causeDe: "Temperaturgleit und Mischungsverhalten die Druck-Temperatur-Deutung veraendern",
    checkTr: "gazin azeotrop mu zeotrop mu oldugu, bubble/dew mantigi ve tablolarin dogru okunmasi kontrol edilir",
    checkDe: "azeotropes oder zeotropes Verhalten, Bubble-/Dew-Punkte und korrekte Tabellenanwendung geprueft werden",
    whyTr: "glide olan gazda nokta secimi hataliysa superheat ve subcool yanlis hesaplanir",
    whyDe: "bei Gleitgemischen falsche Bezugspunkte Superheat und Subcooling verfaelschen",
    mistakeTr: "karisim gazi saf gaz gibi okumak",
    mistakeDe: "ein Gemisch wie ein reines Kaeltemittel auszuwerten",
    suggestions: ["glide nedir", "dew ve bubble farki", "R448A neden farkli okunur"],
    variants: [
      {
        id: "gas_glide_concept",
        trSubject: "temperature glide mantigi",
        deSubject: "das prinzip des temperaturgleits",
        extraKeywords: ["temperature glide", "glide nedir"],
        focusTr: "ayni basincta tek bir sicaklik degil aralik davranisinin olmasi",
        focusDe: "dass bei gleitenden Gemischen zu einem Druck ein Temperaturbereich gehoert",
        whyFocusTr: "glide mantigi bilinmezse sahadaki yorumlar kayar",
        whyFocusDe: "ohne Gleitverstaendnis Feldmessungen falsch interpretiert werden",
      },
      {
        id: "gas_bubble_dew",
        trSubject: "bubble ve dew farki",
        deSubject: "der unterschied zwischen bubble und dew",
        extraKeywords: ["bubble dew", "dew point", "bubble point"],
        focusTr: "sivi ve buhar referans sicakligini ayni sanmamak",
        focusDe: "Fluessig- und Dampfreferenz nicht miteinander zu verwechseln",
        whyFocusTr: "superheat ve subcool icin farkli referanslar gerekir",
        whyFocusDe: "Superheat und Subcooling unterschiedliche Referenzen brauchen",
      },
      {
        id: "gas_glide_superheat",
        trSubject: "glide olan gazda superheat yorumu",
        deSubject: "die superheat-auswertung bei gleitenden gemischen",
        extraKeywords: ["glide superheat", "superheat glide"],
        focusTr: "superheat hesaplarken dogru dew referansini kullanmak",
        focusDe: "bei der Superheat-Berechnung den korrekten Dew-Bezug zu nehmen",
        whyFocusTr: "yanlis referans valf ayarini bile yanlis yone iter",
        whyFocusDe: "ein falscher Bezugspunkt sogar Ventileinstellungen in die falsche Richtung treiben kann",
      },
      {
        id: "gas_glide_subcool",
        trSubject: "glide olan gazda subcool yorumu",
        deSubject: "die subcool-auswertung bei gleitenden gemischen",
        extraKeywords: ["glide subcool", "subcool glide"],
        focusTr: "subcool hesaplarken dogru bubble referansini kullanmak",
        focusDe: "bei der Subcool-Berechnung den korrekten Bubble-Bezug zu nutzen",
        whyFocusTr: "bubble yerine yanlis sicaklik secmek kondens tarafi yorumunu bozar",
        whyFocusDe: "ein falscher Temperaturbezug die Verfluessigerdeutung verfaelscht",
      },
      {
        id: "gas_glide_field_mistake",
        trSubject: "karisim gazda tablo okuma hatasi",
        deSubject: "fehler beim tabellenlesen von mischkaeltemitteln",
        extraKeywords: ["reading PT chart blends", "tablo hatasi karisim"],
        focusTr: "uygulamada dogru PT tablosu ve dogru kolonun secilmemesi",
        focusDe: "in der Praxis die falsche PT-Tabelle oder falsche Spalte benutzt wird",
        whyFocusTr: "tablo hatasi butun teshis zincirini basktan sona kaydirir",
        whyFocusDe: "ein Tabellenfehler die gesamte Diagnosekette von Anfang an verschiebt",
      },
    ],
  },
  {
    causeTr: "belirli gaz ailelerinin basinc ve uygulama karakteri farkli olmasidir",
    causeDe: "verschiedene Kaeltemittelfamilien sich in Druckniveau und Anwendung deutlich unterscheiden",
    checkTr: "gaz ailesi, hedef sicaklik, kompresor toleransi ve saha guvenligi birlikte okunur",
    checkDe: "Kaeltemittelfamilie, Zieltemperatur, Verdichtergrenzen und Feldsicherheit zusammen bewertet werden",
    whyTr: "R134a, R404A veya R290 ayni mantikla okunmaz",
    whyDe: "R134a, R404A oder R290 nicht mit derselben Logik bewertet werden duerfen",
    mistakeTr: "bir gazin basinc karakterini digerine kopyalamak",
    mistakeDe: "das Druckbild eines Kaeltemittels auf ein anderes zu uebertragen",
    suggestions: ["R290 nasil dusunulur", "R404A yerine ne kullanilir", "R134a hangi sahada mantiklidir"],
    variants: [
      {
        id: "gas_family_r134a",
        trSubject: "R134a karakteri",
        deSubject: "die charakteristik von R134a",
        extraKeywords: ["R134a"],
        focusTr: "orta sicaklik ve belirli uygulamalarda daha yumusak basinc yapisinin dusunulmesi",
        focusDe: "im Mitteltemperaturbereich sein eher ruhiges Druckniveau zu verstehen",
        whyFocusTr: "R134a sahada farkli hissettiren bir basinc ve servis karakteri verir",
        whyFocusDe: "R134a im Feld ein eigenes Druck- und Servicegefuehl erzeugt",
      },
      {
        id: "gas_family_r404a",
        trSubject: "R404A karakteri",
        deSubject: "die charakteristik von R404A",
        extraKeywords: ["R404A"],
        focusTr: "dusuk sicaklik tarafinda legacy ama hala referans kabul edilen bir davranis profili",
        focusDe: "im Tiefkuehlbereich ein historisch praegendes, aber heute kritisch bewertetes Profil",
        whyFocusTr: "R404A hala bircok retrofit kararinin referans noktasi olarak dusunulur",
        whyFocusDe: "R404A fuer viele Retrofit-Entscheidungen noch immer ein Vergleichspunkt ist",
      },
      {
        id: "gas_family_r448a_r449a",
        trSubject: "R448A ve R449A gibi alternatif gazlar",
        deSubject: "alternative kaeltemittel wie R448A und R449A",
        extraKeywords: ["R448A", "R449A"],
        focusTr: "alternatif karisim gazlarin glide ve retrofit davranisini birlikte okumak",
        focusDe: "bei Alternativgemischen Glide und Retrofit-Verhalten gemeinsam zu bewerten",
        whyFocusTr: "alternatif gaz kararinda yalniz GWP degil saha davranisi da onemlidir",
        whyFocusDe: "bei Alternativen nicht nur GWP, sondern Feldverhalten entscheidend ist",
      },
      {
        id: "gas_family_r452a",
        trSubject: "R452A gibi dusuk sicaklik alternatifleri",
        deSubject: "tiefkuehl-alternativen wie R452A",
        extraKeywords: ["R452A"],
        focusTr: "negatif depo karakteri icin secilen alternatifin basinc ve kapasite dengesini okumak",
        focusDe: "bei Tiefkuehlalternativen das Zusammenspiel von Druck und Leistung richtig einzuordnen",
        whyFocusTr: "dusuk sicaklikta alternatif gaz secimi kompresor stresiyle dogrudan baglidir",
        whyFocusDe: "im Tiefkuehlbereich die Gaswahl direkt mit Verdichterstress verbunden ist",
      },
      {
        id: "gas_family_r290",
        trSubject: "R290 karakteri",
        deSubject: "die charakteristik von R290",
        extraKeywords: ["R290", "propan"],
        focusTr: "yuksek yanicilikla birlikte guzel termodinamik davranisi birlikte dusunmek",
        focusDe: "sehr gute Thermodynamik zusammen mit hoher Entflammbarkeit gemeinsam zu bewerten",
        whyFocusTr: "R290 teknik olarak guclu ama servis disiplini isteyen bir gazdir",
        whyFocusDe: "R290 technisch stark, aber im Service sehr disziplinfordernd ist",
      },
    ],
  },
  {
    causeTr: "retrofitle gelen degisikliklerin sadece gaz degisimiyle sinirli olmamasidir",
    causeDe: "ein Retrofit weit mehr als nur den Kaeltemitteltausch umfasst",
    checkTr: "kompresor, yag, valf, etiket, ayar ve saha kosullari bir paket olarak degerlendirilir",
    checkDe: "Verdichter, Oel, Ventil, Kennzeichnung, Parameter und Feldbedingungen als Gesamtpaket bewertet werden",
    whyTr: "yerine gaz koymak kolay, ama sistemi saglikli geri vermek ayridir",
    whyDe: "ein anderes Kaeltemittel einzufuellen ist leicht, eine saubere Gesamtanlage zurueckzugeben nicht",
    mistakeTr: "retrofitte yalniz basinca bakip gerisini ayni birakmak",
    mistakeDe: "beim Retrofit nur den Druck anzusehen und den Rest unveraendert zu lassen",
    suggestions: ["retrofitte yag neden onemli", "etiket neden guncellenmeli", "valf ayari tekrar neden bakilir"],
    variants: [
      {
        id: "gas_retrofit_r404a_to_r448a",
        trSubject: "R404A sistemini R448A ya cevirme mantigi",
        deSubject: "die logik beim retrofit von R404A auf R448A",
        extraKeywords: ["R404A to R448A retrofit"],
        focusTr: "eski dusuk sicaklik sistemini yeni glide karakterine gore yeniden dusunmek",
        focusDe: "ein altes Tiefkuehlsystem an ein neues Gleitgemisch anzupassen",
        whyFocusTr: "retrofit sadece sarj degil valf ve yag okumasini da etkiler",
        whyFocusDe: "ein Retrofit nicht nur die Fuellung, sondern auch Ventil- und Oelthemen betrifft",
      },
      {
        id: "gas_retrofit_r404a_to_r449a",
        trSubject: "R404A sistemini R449A ya cevirme mantigi",
        deSubject: "die logik beim retrofit von R404A auf R449A",
        extraKeywords: ["R404A to R449A retrofit"],
        focusTr: "alternatif secenekte saha davranisi, glide ve ayar tekrarini birlikte planlamak",
        focusDe: "bei dieser Alternative Feldverhalten, Glide und Neueinstellung gemeinsam zu planen",
        whyFocusTr: "benzer gorunen alternatiflerin saha hissi ayni olmayabilir",
        whyFocusDe: "auch aehnliche Alternativen im Feld unterschiedlich wirken koennen",
      },
      {
        id: "gas_retrofit_r22_replacement_logic",
        trSubject: "eski R22 mantikli sistemde yerine gaz secimi",
        deSubject: "die ersatzlogik fuer aeltere R22-systeme",
        extraKeywords: ["R22 replacement", "R22 yerine gaz"],
        focusTr: "eski sistemlerin yag ve komponent sinirlarini dikkate alarak gecis yapmak",
        focusDe: "bei alten Anlagen die Oel- und Bauteilgrenzen besonders ernst zu nehmen",
        whyFocusTr: "yasli sistemler kagit uzerindeki uyumu sahada kaldirmayabilir",
        whyFocusDe: "alte Systeme selbst bei scheinbarer Datenblattnahe im Feld empfindlich reagieren koennen",
      },
      {
        id: "gas_retrofit_labeling_and_documentation",
        trSubject: "retrofitte etiket ve dokumantasyon guncelleme",
        deSubject: "kennzeichnung und dokumentation beim retrofit",
        extraKeywords: ["retrofit labeling", "dokumantasyon retrofit"],
        focusTr: "sistemin artik hangi gaz ve hangi sarjla calistiginin net kayda alinmasi",
        focusDe: "klar zu dokumentieren, welches Kaeltemittel und welche Fuellung jetzt in der Anlage ist",
        whyFocusTr: "etiket guncellenmezse sonraki servis teshisi yanlis temelden baslar",
        whyFocusDe: "ohne neue Kennzeichnung der naechste Service auf falschen Annahmen startet",
      },
      {
        id: "gas_retrofit_recommissioning",
        trSubject: "retrofit sonrasi devreye alma mantigi",
        deSubject: "die wiederinbetriebnahme nach einem retrofit",
        extraKeywords: ["retrofit recommissioning", "retrofit devreye alma"],
        focusTr: "yeni gazla superheat, subcool ve emniyetleri tekrar dogrulamak",
        focusDe: "mit dem neuen Kaeltemittel Superheat, Subcooling und Schutze neu zu verifizieren",
        whyFocusTr: "retrofitten sonra eski ayarlarla devam etmek ciddi hata dogurabilir",
        whyFocusDe: "nach einem Retrofit alte Einstellungen unveraendert zu lassen ein schwerer Fehler sein kann",
      },
    ],
  },
  {
    causeTr: "dogru basinc-isi yorumunun gaza gore degismesidir",
    causeDe: "die Druck-Temperatur-Auswertung je nach Kaeltemittel anders funktioniert",
    checkTr: "gaz tipi, PT tablo mantigi, ortam kosulu ve olculen hat sicakliklari birlikte okunur",
    checkDe: "Kaeltemitteltyp, PT-Tabelle, Umgebungsbedingung und Leitungswerte zusammen ausgewertet werden",
    whyTr: "her basinc ayni anlama gelmez; gazi bilmeden yoruma gidilmez",
    whyDe: "derselbe Druck ohne Kenntnis des Kaeltemittels nichts Sinnvolles bedeutet",
    mistakeTr: "baska gazin tablosuyla yorum yapmak",
    mistakeDe: "mit der Tabelle eines anderen Kaeltemittels zu rechnen",
    suggestions: ["saturation nedir", "superheat nasil hesaplanir", "subcool nasil hesaplanir"],
    variants: [
      {
        id: "gas_pressure_saturation",
        trSubject: "basinc ve saturation sicakligi iliskisi",
        deSubject: "der zusammenhang von druck und saettigungstemperatur",
        extraKeywords: ["saturation temperature", "saturasyon sicakligi"],
        focusTr: "olculen basinctan ilgili gaz icin saturation sicakligini dogru okumak",
        focusDe: "aus dem gemessenen Druck die passende Saettigungstemperatur des Kaeltemittels abzuleiten",
        whyFocusTr: "saturation mantigi olmadan superheat ve subcool kurulamaz",
        whyFocusDe: "ohne Saettigungslogik weder Superheat noch Subcooling sauber bestimmt werden kann",
      },
      {
        id: "gas_pressure_superheat_logic",
        trSubject: "superheat mantigi gaza gore nasil okunur",
        deSubject: "wie superheat kaeltemittelbezogen gelesen wird",
        extraKeywords: ["superheat logic", "superheat gaz"],
        focusTr: "gaz ve tablo mantigina gore superheatin dogru referansla hesaplanmasi",
        focusDe: "Superheat mit dem korrekten Kaeltemittel- und Tabellenbezug zu berechnen",
        whyFocusTr: "yanlis superheat kompresor ve valf kararini bozar",
        whyFocusDe: "ein falsch gelesener Superheat Ventil- und Verdichterentscheidungen verfaelscht",
      },
      {
        id: "gas_pressure_subcool_logic",
        trSubject: "subcool mantigi gaza gore nasil okunur",
        deSubject: "wie subcool kaeltemittelbezogen gelesen wird",
        extraKeywords: ["subcool logic", "subcool gaz"],
        focusTr: "gaz tipine gore kondens tarafinda gercek subcool yorumunu dogru kurmak",
        focusDe: "je nach Kaeltemittel auf der Verfluessigerseite echtes Subcooling sauber zu lesen",
        whyFocusTr: "subcool yanlis okunursa sarj ve likit hatti yorumu kayar",
        whyFocusDe: "falsch interpretiertes Subcooling Fuellung und Fluessigkeitsseite verfaelscht",
      },
      {
        id: "gas_pressure_condensing_level",
        trSubject: "kondensasyon basinci gaz secimiyle nasil degisir",
        deSubject: "wie sich das verfluessigungsniveau je nach kaeltemittel aendert",
        extraKeywords: ["condensing pressure by refrigerant", "kondensasyon seviyesi"],
        focusTr: "ayni ortamda farkli gazin farkli basinc seviyesi olabilecegini bilmek",
        focusDe: "zu wissen, dass verschiedene Kaeltemittel bei gleicher Umgebung andere Druckniveaus haben",
        whyFocusTr: "baska gazin normal saydigi basinc digerinde ariza olabilir",
        whyFocusDe: "ein bei einem Mittel normaler Druck beim anderen bereits eine Stoerung bedeuten kann",
      },
      {
        id: "gas_pressure_evaporating_level",
        trSubject: "evaporasyon basinci gaz secimiyle nasil degisir",
        deSubject: "wie sich das verdampfungsniveau je nach kaeltemittel aendert",
        extraKeywords: ["evaporating pressure by refrigerant", "evaporasyon seviyesi"],
        focusTr: "dusuk taraf okumasinda gazin kendi karakterini hesaba katmak",
        focusDe: "bei der Saugseite die Eigencharakteristik des Kaeltemittels mitzurechnen",
        whyFocusTr: "gaz karakteri bilinmezse dusuk basinc arizasi yalanci gorunebilir",
        whyFocusDe: "ohne Kenntnis des Kaeltemittels ein vermeintlicher Niederdruckfehler falsch gedeutet werden kann",
      },
    ],
  },
  {
    causeTr: "kacak arama ve gaz geri kazaniminin servis kalitesinin temeli olmasidir",
    causeDe: "Lecksuche und Rueckgewinnung die Basis guter Servicearbeit sind",
    checkTr: "azot testi, kacak taramasi, geri kazanim tupu ve vakum sirasi birlikte planlanir",
    checkDe: "Stickstofftest, Lecksuche, Rueckgewinnungsflasche und Vakuumabfolge gemeinsam geplant werden",
    whyTr: "sisteme gaz eklemek kadar gazi dogru bosaltmak ve geri almak da ustalik ister",
    whyDe: "saubere Rueckgewinnung genauso meisterlich ist wie das korrekte Einfuellen",
    mistakeTr: "kacagi bulmadan ustune sarj yapmak",
    mistakeDe: "nachzufuellen, ohne das Leck wirklich zu finden",
    suggestions: ["azot testi nasil yapilir", "geri kazanim neden onemli", "vakum ne zaman cekilir"],
    variants: [
      {
        id: "gas_leak_search_logic",
        trSubject: "gaz kacagi arama mantigi",
        deSubject: "die logik der lecksuche",
        extraKeywords: ["leak search", "gaz kacagi arama"],
        focusTr: "kacak aramada semptom, basinc ve riskli noktalari birlikte okumak",
        focusDe: "bei der Lecksuche Symptom, Druckbild und typische Schwachstellen zusammen zu lesen",
        whyFocusTr: "kacak aramasi rastgele degil, sistemli senaryo ile yapildiginda sonuc verir",
        whyFocusDe: "Lecksuche nur als systematischer Ablauf wirklich effektiv ist",
      },
      {
        id: "gas_nitrogen_test_logic",
        trSubject: "azot basinc testi mantigi",
        deSubject: "die logik des stickstoff-drucktests",
        extraKeywords: ["nitrogen pressure test", "azot testi"],
        focusTr: "sistemi inert gazla guvenli sekilde basinc altina alip sizdirmazligi kontrol etmek",
        focusDe: "das System mit inertem Gas sicher unter Druck zu setzen und auf Dichtheit zu pruefen",
        whyFocusTr: "azot testi hem kacagi bulur hem nemli hava basmayi onler",
        whyFocusDe: "ein Stickstofftest Lecksuche und saubere Systemhygiene verbindet",
      },
      {
        id: "gas_recovery_cylinder_logic",
        trSubject: "geri kazanim tupunun dogru kullanimi",
        deSubject: "der richtige umgang mit rueckgewinnungsflaschen",
        extraKeywords: ["recovery cylinder", "geri kazanim tupu"],
        focusTr: "geri alinan gazi tarti, etiket ve doluluk disipliniyle yonetmek",
        focusDe: "zurueckgewonnenes Kaeltemittel mit Waage, Kennzeichnung und Fuellgrenzen sauber zu fuehren",
        whyFocusTr: "geri kazanim tupunde hata hem guvenlik hem saflik sorunu yaratir",
        whyFocusDe: "Fehler an der Rueckgewinnungsflasche Sicherheits- und Reinheitsprobleme erzeugen",
      },
      {
        id: "gas_recovery_machine_logic",
        trSubject: "geri kazanim cihazi ile calisma mantigi",
        deSubject: "das arbeiten mit dem rueckgewinnungsgeraet",
        extraKeywords: ["recovery machine", "geri kazanim cihazi"],
        focusTr: "geri kazanim cihazinin sira, hortum ve tup yonetimiyle dogru kullanilmasi",
        focusDe: "Rueckgewinnungsgeraet, Schlaeuche und Flaschenreihenfolge sauber zu fuehren",
        whyFocusTr: "geri kazanim cihazi yanlis kullanilinca sure uzar ve saflik bozulur",
        whyFocusDe: "falscher Einsatz des Rueckgewinnungsgeraets Zeitverlust und Reinheitsprobleme erzeugt",
      },
      {
        id: "gas_vacuum_after_opening",
        trSubject: "sistemi actiktan sonra vakum sirasi",
        deSubject: "die vakuum-reihenfolge nach systemoeffnung",
        extraKeywords: ["vacuum after opening", "sistem acildiktan sonra vakum"],
        focusTr: "gaz bosaltimi ve onarimdan sonra derin vakuma dogru sirayla gitmek",
        focusDe: "nach Entleerung und Reparatur in sauberer Reihenfolge ins tiefe Vakuum zu gehen",
        whyFocusTr: "acilan sistemde vakum eksik kalirsa sonraki sarj ne kadar dogru olsa da sorun cikabilir",
        whyFocusDe: "bei geoeffnetem System ein schlechtes Vakuum spaetere Probleme trotz korrekter Fuellung ausloest",
      },
    ],
  },
  {
    causeTr: "yanici ve dogal gazlarda saha guvenliginin daha sert disiplin istemesidir",
    causeDe: "brennbare und natuerliche Kaeltemittel im Feld deutlich strengere Disziplin verlangen",
    checkTr: "havalandirma, atesleme kaynagi, personel bilgisi ve servis aletleri birlikte degerlendirilir",
    checkDe: "Belueftung, Zundquellen, Personalwissen und Servicewerkzeuge gemeinsam bewertet werden",
    whyTr: "dogal gazlar teknik olarak iyi olabilir ama servis guvenligiyle birlikte dusunulmelidir",
    whyDe: "natuerliche Kaeltemittel technisch stark sein koennen, aber immer zusammen mit der Sicherheit gedacht werden muessen",
    mistakeTr: "dogal gaz oldugu icin otomatik guvenli sanmak",
    mistakeDe: "natuerliche Kaeltemittel automatisch fuer einfach oder sicher zu halten",
    suggestions: ["R290 servis mantigi", "CO2 sistemi neden farkli", "amonyakla calisirken ne dusunulur"],
    variants: [
      {
        id: "gas_r290_service_logic",
        trSubject: "R290 ile servis mantigi",
        deSubject: "die service-logik bei R290",
        extraKeywords: ["R290 service", "propan servis"],
        focusTr: "yanicilik yuzunden alet, ortam ve kacagi yonetmeyi one almak",
        focusDe: "aufgrund der Entflammbarkeit Werkzeug, Umgebung und Leckmanagement konsequent vorzuziehen",
        whyFocusTr: "R290 teknik olarak guclu ama disiplin istemeyen servis kabul etmez",
        whyFocusDe: "R290 technisch stark ist, aber unsauberen Service nicht verzeiht",
      },
      {
        id: "gas_r600a_logic",
        trSubject: "R600a mantigi",
        deSubject: "die logik von R600a",
        extraKeywords: ["R600a", "isobutane"],
        focusTr: "kucuk sarjli sistemlerde yanicilik ve servis sinirini dogru okumak",
        focusDe: "in kleineren Fuellungen Entflammbarkeit und Servicegrenzen richtig einzuordnen",
        whyFocusTr: "R600a ozellikle kompakt sistemlerde farkli saha aliskanligi ister",
        whyFocusDe: "R600a in kompakten Systemen andere Servicegewohnheiten verlangt",
      },
      {
        id: "gas_co2_high_pressure_logic",
        trSubject: "CO2 sistemlerde basinc mantigi",
        deSubject: "die drucklogik bei CO2-systemen",
        extraKeywords: ["CO2 refrigerant", "R744", "CO2 system"],
        focusTr: "CO2 nin yuksek basinc karakterini klasik HFC mantigindan ayirmak",
        focusDe: "das hohe Druckniveau von CO2 klar von klassischer HFC-Logik zu trennen",
        whyFocusTr: "CO2 yi klasik gaz gibi okumak sahada buyuk hata yaratir",
        whyFocusDe: "CO2 wie ein klassisches HFC zu lesen im Feld schwere Fehler erzeugt",
      },
      {
        id: "gas_ammonia_logic",
        trSubject: "amonyak sistem mantigi",
        deSubject: "die logik von ammoniak-systemen",
        extraKeywords: ["ammonia", "NH3", "R717"],
        focusTr: "verim avantajini toksisite ve profesyonel saha disipliniyle birlikte dusunmek",
        focusDe: "Effizienzvorteile immer zusammen mit Toxizitaet und hoher Betriebsdisziplin zu bewerten",
        whyFocusTr: "amonyak yuksek profesyonellik isteyen bir sahadir",
        whyFocusDe: "Ammoniak ein Bereich mit hoher professioneller Anforderung ist",
      },
      {
        id: "gas_natural_refrigerant_safety",
        trSubject: "dogal sogutucu gazlarda genel guvenlik mantigi",
        deSubject: "die allgemeine sicherheitslogik bei natuerlichen kaeltemitteln",
        extraKeywords: ["natural refrigerants safety", "dogal gaz guvenlik"],
        focusTr: "her dogal gazin farkli risk profilini servis disiplinine cevirmek",
        focusDe: "die jeweils andere Risikostruktur natuerlicher Kaeltemittel in saubere Serviceprozesse zu uebersetzen",
        whyFocusTr: "dogal gaz denince tek tip kural yoktur; gazin karakteri kurali belirler",
        whyFocusDe: "bei natuerlichen Kaeltemitteln keine Einheitsregel gilt, sondern die Stoffcharakteristik den Ablauf bestimmt",
      },
    ],
  },
  {
    causeTr: "cevre, mevzuat baskisi ve enerji hedefinin gaz secimini yonlendirmesidir",
    causeDe: "Umwelt- und Energieziele die Kaeltemittelwahl mitbestimmen",
    checkTr: "GWP mantigi, enerji hedefi, uzun vadeli servis bulunabilirligi ve proje omru birlikte degerlendirilir",
    checkDe: "GWP-Logik, Energieziel, langfristige Serviceverfuegbarkeit und Projektlebensdauer gemeinsam bewertet werden",
    whyTr: "bugun calisan gaz yarin lojistik ve mevzuat nedeniyle zorlanabilir",
    whyDe: "ein heute funktionierendes Kaeltemittel spaeter durch Logistik oder Regulierung unpraktisch werden kann",
    mistakeTr: "yalniz bugunku fiyatla karar vermek",
    mistakeDe: "nur nach dem heutigen Preis zu entscheiden",
    suggestions: ["GWP neden onemli", "alternatif gaz secimi nasil planlanir", "uzun vadeli servis neye gore dusunulur"],
    variants: [
      {
        id: "gas_gwp_logic",
        trSubject: "GWP mantigi",
        deSubject: "die logik des GWP-werts",
        extraKeywords: ["GWP"],
        focusTr: "gaz seciminde cevresel etkinin stratejik bir kriter haline gelmesi",
        focusDe: "die Umweltwirkung des Kaeltemittels zu einem strategischen Auswahlfaktor wird",
        whyFocusTr: "GWP tek kriter degil ama uzun vadeli proje kararinda ignore edilemez",
        whyFocusDe: "GWP nicht das einzige Kriterium, aber fuer Langfristprojekte nicht ignorierbar ist",
      },
      {
        id: "gas_energy_efficiency_tradeoff",
        trSubject: "verim ile gaz secimi arasindaki denge",
        deSubject: "die balance zwischen effizienz und kaeltemittelwahl",
        extraKeywords: ["efficiency refrigerant tradeoff", "verim gaz dengesi"],
        focusTr: "yalniz yasal veya yalniz cevresel degil, isletme verimini de birlikte okumak",
        focusDe: "nicht nur Umwelt oder Recht, sondern auch Betriebseffizienz mitzudenken",
        whyFocusTr: "yanlis gaz secimi faturada uzun sure gizli kayip yaratabilir",
        whyFocusDe: "eine unpassende Wahl langfristig unsichtbare Energiekosten erzeugt",
      },
      {
        id: "gas_service_availability",
        trSubject: "gaz bulunabilirligi ve servis surekliligi",
        deSubject: "verfuegbarkeit und servicekontinuitaet des kaeltemittels",
        extraKeywords: ["service availability", "gaz bulunabilirligi"],
        focusTr: "yarin servis ederken gazin, yagin ve yedegin piyasada bulunup bulunmadigini dusunmek",
        focusDe: "bereits heute zu bedenken, ob Kaeltemittel, Oel und Ersatzspaeter verfuegbar bleiben",
        whyFocusTr: "nadir veya sorunlu gaz sahada isletme riskini buyutebilir",
        whyFocusDe: "ein schwer verfuegbares Kaeltemittel den Betriebsrisiko langfristig vergroessert",
      },
      {
        id: "gas_future_proof_selection",
        trSubject: "ileri donuk gaz secimi",
        deSubject: "eine zukunftssichere kaeltemittelwahl",
        extraKeywords: ["future proof refrigerant", "ileri donuk gaz"],
        focusTr: "projenin gelecek yillarini dusunerek gaz secmek",
        focusDe: "das Kaeltemittel so zu waehlen, dass es nicht nur heute, sondern spaeter passt",
        whyFocusTr: "saha kurulduktan sonra gaz degistirmek en pahali degisikliklerden biri olabilir",
        whyFocusDe: "ein spaeterer Kaeltemittelwechsel nach Inbetriebnahme sehr teuer werden kann",
      },
      {
        id: "gas_customer_communication",
        trSubject: "musteriye gaz secimini nasil anlatmak gerekir",
        deSubject: "wie man dem kunden die kaeltemittelwahl erklaert",
        extraKeywords: ["customer explanation refrigerant", "musteriye gaz anlatimi"],
        focusTr: "teknik secimi maliyet, guvenlik ve servis diliyle anlatmak",
        focusDe: "die technische Auswahl in Kosten-, Sicherheits- und Service-Sprache zu uebersetzen",
        whyFocusTr: "musteri dogru karari teknik tabloyla degil, anladigi risk ve faydayla verir",
        whyFocusDe: "Kunden Entscheidungen eher ueber verstandene Risiken und Nutzen als ueber Tabellen treffen",
      },
    ],
  },
  {
    causeTr: "gazla ilgili en sik ustalik hatalarinin tekrar eden sahasal kayiplara donmesidir",
    causeDe: "die haeufigsten Kaeltemittel-Fehler in wiederkehrende Feldverluste muenden",
    checkTr: "sahada tekrar eden yanlis aliskanliklar, dolum sekli, etiketsiz calisma ve eksik olcum aliskanligi kontrol edilir",
    checkDe: "wiederkehrende Fehlgewohnheiten, Fuellmethode, Kennzeichnung und fehlende Messdisziplin im Feld geprueft werden",
    whyTr: "gaz konusunda bilgi eksigi bir kerelik degil, her serviste tekrar eden kayip dogurur",
    whyDe: "Wissensluecken beim Kaeltemittel nicht einmalig, sondern bei jedem Service neue Verluste erzeugen",
    mistakeTr: "olcmeyi azaltip tahminle gaz isi yapmak",
    mistakeDe: "Messungen zu sparen und Kaeltemittelarbeit aus dem Bauch heraus zu machen",
    suggestions: ["sarj neden tarti ile yapilir", "etiket neden guncel olmali", "hangi gaz hangi uygulamada mantikli"],
    variants: [
      {
        id: "gas_common_mistake_topup",
        trSubject: "gaz eksildi diye rastgele ustune eklemek",
        deSubject: "bei verlust einfach blind nachzufuellen",
        extraKeywords: ["blind top up", "rastgele ekleme"],
        focusTr: "kacak, kompozisyon ve sistem temizligini gormeden sadece miktar eklemeye odaklanmak",
        focusDe: "ohne Lecksuche, Zusammensetzung und Systemzustand einfach nur Menge nachzufuellen",
        whyFocusTr: "bu davranis arizayi saklar ama cozmez",
        whyFocusDe: "dieses Verhalten den Fehler verdeckt, aber nicht loest",
      },
      {
        id: "gas_common_mistake_wrong_identification",
        trSubject: "sistemdeki gazi dogru teshis etmeden servis yapmak",
        deSubject: "service zu machen ohne das kaeltemittel sicher zu identifizieren",
        extraKeywords: ["wrong refrigerant identification", "gaz kimligi bilinmeden servis"],
        focusTr: "etiket, kayit ve saha teyidi olmadan gaz tipini varsaymak",
        focusDe: "Kaeltemitteltyp ohne Kennzeichnung, Doku oder Feldbestaetigung anzunehmen",
        whyFocusTr: "yanlis gaz varsayimi butun olculeri ve karar zincirini bozar",
        whyFocusDe: "eine falsche Annahme ueber das Kaeltemittel alle Messungen und Entscheidungen verzerrt",
      },
      {
        id: "gas_common_mistake_no_weighing",
        trSubject: "tarti kullanmadan gaz sarj etmek",
        deSubject: "ohne waage kaeltemittel zu fuellen",
        extraKeywords: ["no weighing refrigerant", "tarti kullanmadan sarj"],
        focusTr: "sarj isini yalniz manometre ve goz karariyla yapmak",
        focusDe: "Fuellarbeiten nur nach Druckgefuehl statt nach Gewicht durchzufuehren",
        whyFocusTr: "tarti yoksa gercek aktarilan miktari bilmiyorsunuz demektir",
        whyFocusDe: "ohne Waage die reale Fuellmenge nie sicher bekannt ist",
      },
      {
        id: "gas_common_mistake_wrong_chart",
        trSubject: "yanlis PT tablosuyla okumak",
        deSubject: "mit der falschen PT-tabelle zu arbeiten",
        extraKeywords: ["wrong PT chart", "yanlis tablo"],
        focusTr: "baska gazin basinc-sicaklik tablosunu kullanmak",
        focusDe: "die Druck-Temperatur-Tabelle eines anderen Kaeltemittels zu nutzen",
        whyFocusTr: "yanlis tablo, sahada dogru olcuyu bile yanlis anlama cevirir",
        whyFocusDe: "eine falsche Tabelle selbst richtige Messwerte falsch erscheinen laesst",
      },
      {
        id: "gas_common_mistake_ignore_safety",
        trSubject: "guvenlik sinifini ciddiye almamak",
        deSubject: "die sicherheitsklasse nicht ernst zu nehmen",
        extraKeywords: ["ignore refrigerant safety class", "guvenlik sinifi ihmal"],
        focusTr: "A2L veya A3 gibi gazlari A1 servis aliskanligiyla ele almak",
        focusDe: "A2L- oder A3-Mittel mit der Routine eines A1-Services zu behandeln",
        whyFocusTr: "guvenlik kurali ihlali teknik degil dogrudan saha riski yaratir",
        whyFocusDe: "das Ignorieren der Sicherheitsklasse direkt zum Feldrisiko wird",
      },
    ],
  },
];

const allTopics = families.flatMap((family) => family.variants.map((topic) => buildEntry(topic, family)));
const topics = allTopics.slice(0, 50);

if (topics.length !== 50) {
  throw new Error(`Expected 50 gas topics, got ${topics.length}`);
}

const totalQuestionCount = topics.reduce((sum, entry) => sum + entry.tr_questions.length + entry.de_questions.length, 0);
if (totalQuestionCount !== 1000) {
  throw new Error(`Expected 1000 gas questions, got ${totalQuestionCount}`);
}

fs.writeFileSync(OUTPUT, JSON.stringify(topics, null, 2), "utf-8");
console.log(`Generated gas pack: ${topics.length} entries / ${totalQuestionCount} questions -> ${OUTPUT}`);
