const fs = require("fs");
const path = require("path");

const trTemplates = [
  (s) => `${s} neden olur`,
  (s) => `${s} olursa neye bakilir`,
  (s) => `${s} varsa usta once ne kontrol eder`,
  (s) => `${s} arizasinda teshis nasil baslar`,
  (s) => `${s} sorunu nasil cozulur`,
  (s) => `${s} neden tekrar eder`,
  (s) => `${s} oldugunda hangi olcumler yapilir`,
  (s) => `${s} montaj hatasi olabilir mi`,
  (s) => `${s} gorulurse servis sirasi ne olur`,
  (s) => `${s} icin en sik hata nedir`,
];

const deTemplates = [
  (s) => `warum tritt ${s} auf`,
  (s) => `worauf schaut man wenn ${s} auftritt`,
  (s) => `was prueft ein meister zuerst wenn ${s} da ist`,
  (s) => `wie beginnt die diagnose bei ${s}`,
  (s) => `wie loest man ${s}`,
  (s) => `warum kommt ${s} immer wieder`,
  (s) => `welche messungen macht man bei ${s}`,
  (s) => `kann montagefehler ${s} verursachen`,
  (s) => `wie ist die service reihenfolge bei ${s}`,
  (s) => `was ist der haeufigste fehler bei ${s}`,
];

function buildAnswerTr(topic, family, pack) {
  return `${topic.trSubject} durumunda ${pack.expertTr} once semptomu temiz ayirir. Bu konuda tipik kok neden ${topic.focusTr}; bunun yaninda ${family.causeTr}. Ilk kontrolde ${family.checkTr}. Bunun teknik sebebi ${topic.whyFocusTr}; ayrica ${family.whyTr}. En sik hata ise ${family.mistakeTr}. Saglam servis mantigi parcayi ezbere degistirmek yerine olcu, gozlem ve isletme senaryosunu birlikte okumaktir.`;
}

function buildAnswerDe(topic, family, pack) {
  return `Wenn ${topic.deSubject} auftritt, trennt ${pack.expertDe} zuerst das Symptom sauber von der Ursache. Eine typische Kernursache ist ${topic.focusDe}; zusaetzlich kommen ${family.causeDe} vor. Bei der Erstpruefung werden ${family.checkDe}. Der technische Hintergrund ist ${topic.whyFocusDe}; ausserdem gilt ${family.whyDe}. Ein sehr haeufiger Fehler besteht darin, dass ${family.mistakeDe}. Saubere Servicearbeit bedeutet hier, nicht blind Teile zu tauschen, sondern Messwerte, Beobachtung und Betriebssituation logisch zusammenzufuehren.`;
}

function expandPack(pack) {
  const topics = pack.families.flatMap((family) =>
    family.variants.map((variant) => ({
      id: variant.id,
      tr_subject: variant.trSubject,
      de_subject: variant.deSubject,
      keywords: [variant.trSubject, variant.deSubject, ...(variant.extraKeywords || [])],
      tr_questions: trTemplates.map((template) => template(variant.trSubject)),
      de_questions: deTemplates.map((template) => template(variant.deSubject)),
      tr_answer: buildAnswerTr(variant, family, pack),
      de_answer: buildAnswerDe(variant, family, pack),
      source_summary: pack.sourceSummary,
      suggestions: variant.suggestions || family.suggestions || [],
    }))
  );

  if (topics.length !== 50) {
    throw new Error(`${pack.key} expected 50 topics, got ${topics.length}`);
  }

  const totalQuestionCount = topics.reduce((sum, topic) => sum + topic.tr_questions.length + topic.de_questions.length, 0);
  if (totalQuestionCount !== 1000) {
    throw new Error(`${pack.key} expected 1000 questions, got ${totalQuestionCount}`);
  }

  const output = path.join(__dirname, pack.output);
  fs.writeFileSync(output, JSON.stringify(topics, null, 2), "utf-8");
  console.log(`Generated ${pack.key}: ${topics.length} entries / ${totalQuestionCount} questions -> ${output}`);
}

const packs = [
  {
    key: "electrical",
    output: "drc_man_electrical_faq.json",
    sourceSummary: "DRC MAN soguk oda elektrik ustasi egitimi",
    expertTr: "elektrik ustasi",
    expertDe: "ein Kuehlhaus-Elektrikmeister",
    families: [
      {
        causeTr: "ana besleme hattinda gevseklik, kablo kesiti sorunu veya sebeke dengesizligi bulunmasidir",
        causeDe: "lockere Einspeisung, ungeeigneter Kabelquerschnitt oder Netzinstabilitaet vorliegt",
        checkTr: "ana giris, faz-faz ve faz-notr gerilimleri, sigortalar ve yuk altindaki gerilim dusumu birlikte olculur",
        checkDe: "Einspeisung, Phase-Phase- und Phase-N-Werte, Sicherungen und der Spannungsfall unter Last zusammen gemessen",
        whyTr: "uc fazli sogutma ekipmanlari enerji kalitesi bozuldugunda mekanik ariza gibi gorunen davranislar gosterebilir",
        whyDe: "drei-phasige Kaelteanlagen bei schlechter Energiequalitaet Symptome zeigen koennen, die wie Mechanikfehler aussehen",
        mistakeTr: "sadece cihazin icine bakip besleme hattini ve pano girisini ihmal etmektir",
        mistakeDe: "nur ins Geraet zu schauen und Zuleitung sowie Schaltschrank-Einspeisung zu uebersehen",
        suggestions: ["faz sirasi neden onemli", "gevsek klemens ne yapar", "kompresor neden calismiyor"],
        variants: [
          {
            id: "electrical_phase_loss",
            trSubject: "faz eksigi var",
            deSubject: "eine phase fehlt",
            extraKeywords: ["phase loss", "faz yok"],
            focusTr: "bir fazin kopuk, sigortadan dusmus veya klemenste kayip olmasi",
            focusDe: "eine Phase unterbrochen ist, an der Sicherung fehlt oder an der Klemme verloren geht",
            whyFocusTr: "tek faz eksiginde motorlar ya hic kalkmaz ya da asiri zorlanir",
            whyFocusDe: "Motoren bei fehlender Phase entweder gar nicht starten oder extrem ueberlasten",
          },
          {
            id: "electrical_voltage_imbalance",
            trSubject: "fazlar dengesiz geliyor",
            deSubject: "die phasen unausgeglichen sind",
            extraKeywords: ["phase imbalance", "faz dengesizligi"],
            focusTr: "faz gerilimlerinin birbirinden sapmis olmasi",
            focusDe: "die Spannungen der drei Phasen deutlich auseinanderlaufen",
            whyFocusTr: "dengesiz faz kompresor akimini bir kolda asiri yukseltebilir",
            whyFocusDe: "eine unsymmetrische Phase den Verdichterstrom auf einer Seite stark erhoehen kann",
          },
          {
            id: "electrical_undervoltage",
            trSubject: "voltaj dusuk geliyor",
            deSubject: "unterspannung anliegt",
            extraKeywords: ["under voltage", "dusuk voltaj"],
            focusTr: "uzun hat, zayif kesit veya yuk aninda gerilim cokmesi",
            focusDe: "lange Leitung, zu kleiner Querschnitt oder Spannungseinbruch unter Last",
            whyFocusTr: "dusuk voltaj motor akimini arttirarak isitma ve termik sorununa doner",
            whyFocusDe: "Unterspannung die Stromaufnahme erhoeht und zu Ueberhitzung fuehrt",
          },
          {
            id: "electrical_overvoltage",
            trSubject: "voltaj gereksiz yuksek",
            deSubject: "ueberspannung anliegt",
            extraKeywords: ["over voltage", "yuksek voltaj"],
            focusTr: "sebeke tarafinda anlik ya da surekli yuksek gerilim bulunmasi",
            focusDe: "im Netz kurzzeitig oder dauerhaft zu hohe Spannung vorhanden ist",
            whyFocusTr: "yuksek voltaj elektronik kartlar ve surucu modulleri icin ayri risk yaratir",
            whyFocusDe: "Ueberspannung fuer Regler und Frequenzumrichter ein eigenes Risiko darstellt",
          },
          {
            id: "electrical_neutral_loss",
            trSubject: "notr kopuklugu ariza yapiyor",
            deSubject: "ein neutralleiterfehler stoerungen macht",
            extraKeywords: ["neutral loss", "notr kopuklugu"],
            focusTr: "notr hattinin zayiflamasi veya kopmasi",
            focusDe: "der Neutralleiter locker oder unterbrochen ist",
            whyFocusTr: "ozellikle kontrol devrelerinde notr kaybi rastgele kart ve sensor hatalarina donusebilir",
            whyFocusDe: "gerade in Steuerkreisen ein Neutralleiterfehler zu scheinbar zufaelligen Karten- und Fuehlerfehlern fuehrt",
          },
        ],
      },
      {
        causeTr: "koruma elemanlarinin gercek bir yuk sorununa tepki vermesi veya secim-ayarin yanlis olmasidir",
        causeDe: "Schutzelemente auf eine echte Ueberlast reagieren oder falsch ausgewaehlt bzw. eingestellt sind",
        checkTr: "sigorta, otomatik, termik ve kacaga karsi koruma elemanlari gercek olcumlerle karsilastirilir",
        checkDe: "Sicherung, Leitungsschutz, Motorschutz und Fehlerstromschutz mit realen Messwerten abgeglichen",
        whyTr: "koruma elemani arizanin kendisi degil, sistemin bir yerde zorlandigini gosteren isarettir",
        whyDe: "das Schutzelement meist nicht die Ursache, sondern das Warnsignal fuer ein tieferes Problem ist",
        mistakeTr: "korumayi buyutup sistemi zorla calistirmaya calismaktir",
        mistakeDe: "den Schutz groesser zu machen und die Anlage gewaltsam weiterlaufen zu lassen",
        suggestions: ["termik neden atar", "kacak akim rolesi neden atar", "basinc switch neden acilir"],
        variants: [
          {
            id: "electrical_breaker_trip",
            trSubject: "otomatik sigorta atiyor",
            deSubject: "der leitungsschutz ausloest",
            extraKeywords: ["breaker trip", "otomatik atiyor"],
            focusTr: "ani asiri akim veya kisa devre benzeri bir durum olusmasi",
            focusDe: "eine kurzzeitige Ueberstrom- oder Kurzschlussbedingung entsteht",
            whyFocusTr: "hatta veya motorda anlik zorlanma varsa otomatik ilk tepkiyi verir",
            whyFocusDe: "der Leitungsschutz bei plötzlicher Ueberlast oder Kurzschluss als erstes reagiert",
          },
          {
            id: "electrical_fuse_blow",
            trSubject: "eriyen sigorta surekli kopuyor",
            deSubject: "die schmelzsicherung immer wieder ausfaellt",
            extraKeywords: ["fuse blow", "eriyen sigorta"],
            focusTr: "kisa devreye yakin sert akim cekisi veya yanlış sigorta karakteristigi",
            focusDe: "sehr harter Stromanstieg oder eine unpassende Sicherungscharakteristik",
            whyFocusTr: "eriyen sigorta yavas degil sert akim darbelerine hassastir",
            whyFocusDe: "Schmelzsicherungen besonders empfindlich auf harte Stromspitzen reagieren",
          },
          {
            id: "electrical_thermal_overload",
            trSubject: "termik role dusuyor",
            deSubject: "das motorschutzrelais ausloest",
            extraKeywords: ["thermal overload", "termik role"],
            focusTr: "motorun izin verilenden fazla akim cekmesi",
            focusDe: "der Motor mehr Strom als zulaessig zieht",
            whyFocusTr: "termik, sargilarin yanmasini onlemek icin gecikmeli koruma verir",
            whyFocusDe: "das Motorschutzrelais die Wicklung mit einer zeitverzoegerten Schutzlogik schuetzt",
          },
          {
            id: "electrical_rcd_trip",
            trSubject: "kacak akim rolesi atiyor",
            deSubject: "der fehlerstromschutz ausloest",
            extraKeywords: ["rcd trip", "kacak akim"],
            focusTr: "topraga sizan akim veya izolasyon zafiyeti bulunmasi",
            focusDe: "Ableitstrom gegen Erde oder ein Isolationsfehler vorliegt",
            whyFocusTr: "yikama, nem ve rezistans kacaklari bu korumayi tetikleyebilir",
            whyFocusDe: "Reinigung, Feuchte und Heizungsleckstroeme diesen Schutz oft ausloesen",
          },
          {
            id: "electrical_safety_chain_open",
            trSubject: "emniyet zinciri acik kaldigi icin cihaz calismiyor",
            deSubject: "die sicherheitskette offen ist und die anlage nicht startet",
            extraKeywords: ["safety chain", "emniyet zinciri"],
            focusTr: "basinc switch, kapi switchi veya acil stop hatti gibi seri emniyetlerden birinin acik olmasi",
            focusDe: "ein Glied der Sicherheitskette wie Druckschalter, Tuerschalter oder Not-Aus offen ist",
            whyFocusTr: "seri emniyet zincirinde tek bir kopukluk butun devreyi durdurur",
            whyFocusDe: "bei einer Serienschaltung schon ein offenes Glied die ganze Anlage sperrt",
          },
        ],
      },
      {
        causeTr: "start ve anahtarlama ekipmanlarinda mekanik yipranma veya bobin-kontak zayifligi olmasidir",
        causeDe: "mechanischer Verschleiss oder Schwachstellen an Spulen und Kontakten in der Start- und Schaltkette vorliegen",
        checkTr: "kontaktor sesi, kontak dusumu, bobin gerilimi ve kalkis komponentleri birlikte kontrol edilir",
        checkDe: "Schuetzgeraeusch, Kontaktabfall, Spulenspannung und Startkomponenten gemeinsam geprueft",
        whyTr: "kompresor ve fanlarin saglikli kalkisi icin anahtarlama zincirinin temiz calismasi gerekir",
        whyDe: "Verdichter und Ventilatoren nur sauber anlaufen, wenn die Schaltkette elektrisch und mechanisch gesund ist",
        mistakeTr: "sadece motoru suclayip kalkis devresini atlamaktir",
        mistakeDe: "nur den Motor zu verdaechtigen und den Startkreis zu ueberspringen",
        suggestions: ["kompresor neden calismiyor", "zor kalkis neden olur", "kontaktorda neye bakilir"],
        variants: [
          {
            id: "electrical_contactor_not_pulling",
            trSubject: "kontaktor cekmiyor",
            deSubject: "das schuetz nicht anzieht",
            extraKeywords: ["contactor", "schuetz zieht nicht"],
            focusTr: "bobine komut gelmemesi veya bobinin kopuk olmasi",
            focusDe: "keine Spannung an die Spule kommt oder die Spule selbst defekt ist",
            whyFocusTr: "kontaktor cekmezse yuk devresi hic kapanmaz",
            whyFocusDe: "ohne anziehendes Schuetz der Lastkreis gar nicht geschlossen wird",
          },
          {
            id: "electrical_contactor_chatter",
            trSubject: "kontaktor titreyerek cekiyor",
            deSubject: "das schuetz flattert",
            extraKeywords: ["chatter", "flattern"],
            focusTr: "bobin geriliminin kararsiz olmasi veya mekanigin kirli-gevsek olmasi",
            focusDe: "Spulenspannung instabil ist oder die Mechanik verschmutzt bzw. locker ist",
            whyFocusTr: "titreyen kontaktor kontaklari yakip gerilim dusumune yol acar",
            whyFocusDe: "ein flatterndes Schuetz Kontakte abbrennt und Spannungsabfall erzeugt",
          },
          {
            id: "electrical_burnt_contacts",
            trSubject: "kontaktor kontaklari yanmis",
            deSubject: "die schuetzkontakte verbrannt sind",
            extraKeywords: ["burnt contacts", "yanik kontak"],
            focusTr: "uzun sure yuksek akim, zayif temas veya sık start-stop",
            focusDe: "lange Ueberlast, schlechter Kontakt oder haeufiges Takten",
            whyFocusTr: "yanik kontaklar disaridan kapali gorunse de yukte ciddi dusum yapar",
            whyFocusDe: "verbrannte Kontakte auch im geschlossenen Zustand starken Spannungsfall erzeugen",
          },
          {
            id: "electrical_start_relay_fault",
            trSubject: "kalkis rolesi arizali",
            deSubject: "das startrelais stoert",
            extraKeywords: ["start relay", "kalkis rolesi"],
            focusTr: "yardimci sarginin dogru zamanda devreye girip cikmamasi",
            focusDe: "die Hilfswicklung nicht zur richtigen Zeit zu- und abgeschaltet wird",
            whyFocusTr: "tek fazli motorlarda start rolesi kalkisin karakterini belirler",
            whyFocusDe: "bei einphasigen Motoren das Startrelais den Startcharakter wesentlich bestimmt",
          },
          {
            id: "electrical_start_capacitor_fault",
            trSubject: "kalkis kapasitörü zayif",
            deSubject: "der startkondensator schwach ist",
            extraKeywords: ["start capacitor", "kondansator zayif"],
            focusTr: "kapasitor degerinin dusmesi veya tamamen bozulmasi",
            focusDe: "der Kondensatorwert abgesunken oder ganz ausgefallen ist",
            whyFocusTr: "zayif kapasitör motoru dondurmez, sadece homurdanmaya iter",
            whyFocusDe: "ein schwacher Kondensator den Motor nicht sauber anzieht, sondern nur schwer anlaufen laesst",
          },
        ],
      },
      {
        causeTr: "fan ve yardimci motor grubunda sargi, rulman veya donus problemi bulunmasidir",
        causeDe: "an Ventilatoren und Hilfsmotoren Wicklungs-, Lager- oder Drehrichtungsprobleme auftreten",
        checkTr: "motor akimi, rulman sesi, serbest donus ve hava karakteri birlikte izlenir",
        checkDe: "Motorstrom, Lagergeraeusch, freie Drehbarkeit und Luftbild gemeinsam beobachtet werden",
        whyTr: "motor grubu bozuldugunda elektrik arizasi hava tarafina yansir ve sogutma performansi da duser",
        whyDe: "Motorprobleme auf der Luftseite direkt in Kuehlleistungsprobleme uebersetzen",
        mistakeTr: "fan donuyor diye saglikli saymaktir",
        mistakeDe: "den Ventilator allein wegen Drehung fuer gesund zu halten",
        suggestions: ["fan neden donmuyor", "yanlis fan yonu ne yapar", "motor rulmani nasil anlasilir"],
        variants: [
          {
            id: "electrical_fan_winding_fault",
            trSubject: "fan motor sargisi sorunlu",
            deSubject: "die ventilatorwicklung defekt ist",
            extraKeywords: ["fan winding", "motor sargisi"],
            focusTr: "motor sargisinda kismi yanik veya dengesiz direnç olmasi",
            focusDe: "die Motorwicklung teilgeschaedigt ist oder ungleichmaessige Widerstaende zeigt",
            whyFocusTr: "sargi hatasi motorun hem akimini hem torkunu bozar",
            whyFocusDe: "ein Wicklungsfehler Stromaufnahme und Drehmoment gleichzeitig stoert",
          },
          {
            id: "electrical_motor_wrong_rotation",
            trSubject: "motor ters yonde donuyor",
            deSubject: "der motor falsch herum laeuft",
            extraKeywords: ["wrong rotation", "ters donus"],
            focusTr: "faz sirasi veya kablolama nedeniyle donus yonunun ters gelmesi",
            focusDe: "durch Phasenfolge oder Verdrahtung die Drehrichtung vertauscht wurde",
            whyFocusTr: "ters donus hava akisini bozar ve bazen motoru saglikli gosterdigi halde isi bozabilir",
            whyFocusDe: "falsche Drehrichtung den Luftstrom zerstoert und trotz laufendem Motor den Prozess stoert",
          },
          {
            id: "electrical_motor_bearing_seize",
            trSubject: "motor rulmani sikişiyor",
            deSubject: "das motorlager festgeht",
            extraKeywords: ["bearing seize", "rulman"],
            focusTr: "rulman yorgunlugu veya su-nem nedeniyle mekanik surtunme artmasi",
            focusDe: "Lagerschaden oder mechanische Reibung durch Wasser und Feuchte zunimmt",
            whyFocusTr: "mekanik sıkisma elektriksel olarak fazla akim ve ses olarak geri doner",
            whyFocusDe: "mechanisches Klemmen elektrisch als hoher Strom und akustisch als Geraeusch sichtbar wird",
          },
          {
            id: "electrical_fan_ice_block",
            trSubject: "fan buzdan kilitleniyor",
            deSubject: "der ventilator durch eis blockiert",
            extraKeywords: ["fan ice block", "fan buz kilidi"],
            focusTr: "defrost ve drenaj sorunu yuzunden kanat veya koruma telinde buz birikmesi",
            focusDe: "durch Abtau- oder Ablaufprobleme Eis an Schaufel oder Schutzgitter entsteht",
            whyFocusTr: "buz kilidi motoru elektriksel ariza gibi gosterebilir ama kok neden hava-nem tarafidir",
            whyFocusDe: "eine Eisblockade wie ein Elektrofehler wirken kann, obwohl die Grundursache an Feuchte und Luft liegt",
          },
          {
            id: "electrical_condenser_fan_cycle_fault",
            trSubject: "kondenser fan devreye yanlis giriyor",
            deSubject: "der verfluessiger ventilator falsch schaltet",
            extraKeywords: ["fan cycle", "cond fan control"],
            focusTr: "fan kontrol basincina veya role lojigine uygun calismamasi",
            focusDe: "der Ventilator nicht passend zu Druckschalter oder Regelrelais arbeitet",
            whyFocusTr: "yanlis fan sekansi basinç dalgalanmasi ve enerji kaybina yol acar",
            whyFocusDe: "falsche Ventilatorzyklen starke Druckschwankungen und Energieverluste erzeugen",
          },
        ],
      },
      {
        causeTr: "kontrol beslemesinde 24V veya yardimci besleme hatalari bulunmasidir",
        causeDe: "im Steuerkreis 24V- oder Hilfsversorgungsausfaelle auftreten",
        checkTr: "kontrolor beslemesi, trafo, SMPS ve dusuk gerilim devreleri yuk altinda olculur",
        checkDe: "Reglerversorgung, Trafo, Netzteil und Kleinspannungskreise unter Last gemessen",
        whyTr: "dijital kontrol tarafi zayiflarsa saha arizasi rastgele ve tutarsiz gorunebilir",
        whyDe: "eine schwache Steuerversorgung zu scheinbar zufaelligen und wechselnden Fehlerbildern fuehrt",
        mistakeTr: "sadece ana guce bakip kumanda gerilimini unutmak",
        mistakeDe: "nur die Hauptspannung zu sehen und die Steuerspannung zu vergessen",
        suggestions: ["kontrolor neden acilmiyor", "24v neden duser", "trafo nasil kontrol edilir"],
        variants: [
          {
            id: "electrical_controller_no_power",
            trSubject: "kontrolor acilmiyor",
            deSubject: "der regler keine spannung hat",
            extraKeywords: ["controller no power", "regler tot"],
            focusTr: "kontrolore gelen yardimci beslemenin kesik olmasi",
            focusDe: "die Hilfsversorgung des Reglers unterbrochen ist",
            whyFocusTr: "regler acilmadan diger cikislarin hicbiri mantikli davranmaz",
            whyFocusDe: "ohne aktiven Regler keine Ausgangsstufe sauber arbeiten kann",
          },
          {
            id: "electrical_24v_supply_sag",
            trSubject: "24 volt besleme cökuyor",
            deSubject: "die 24-volt versorgung einbricht",
            extraKeywords: ["24v sag", "control voltage low"],
            focusTr: "yardimci guc kaynagi yukte degeri tutamiyor",
            focusDe: "das Hilfsnetzteil die Spannung unter Last nicht halten kann",
            whyFocusTr: "24V cokerse sensor, role ve kart lojigi rastgele hata vermeye baslar",
            whyFocusDe: "ein Einbruch der 24V-Versorgung Sensorik, Relais und Logik gleichzeitig stoeren kann",
          },
          {
            id: "electrical_transformer_fault",
            trSubject: "kumanda trafosu arizali",
            deSubject: "der steuertrafo defekt ist",
            extraKeywords: ["control transformer", "steuertrafo"],
            focusTr: "trafo sargisinin isinma, yaslanma veya kisa devreyle bozulmasi",
            focusDe: "die Trafowicklung durch Hitze, Alterung oder Kurzschluss geschaedigt ist",
            whyFocusTr: "trafo arizasi bazen bosta normal, yukte bozuk davranis verebilir",
            whyFocusDe: "ein defekter Trafo im Leerlauf noch plausibel wirken, unter Last aber zusammenbrechen kann",
          },
          {
            id: "electrical_backup_battery_loss",
            trSubject: "saat ve hafiza ayarlari gidiyor",
            deSubject: "uhr und speicher verlieren ihre daten",
            extraKeywords: ["rtc battery", "hafiza gidiyor"],
            focusTr: "ic pil, hafiza veya saat modulu degerini koruyamiyor",
            focusDe: "Batterie, Speicher oder Echtzeituhr die Daten nicht halten",
            whyFocusTr: "zaman kaybi özellikle defrost ve gece-gunduz programlarini bozar",
            whyFocusDe: "Zeitverlust besonders Abtau- und Tagesprogramme zerstoert",
          },
          {
            id: "electrical_digital_input_flap",
            trSubject: "dijital giris sinyali titriyor",
            deSubject: "das digitale eingangssignal flattert",
            extraKeywords: ["digital input bounce", "input flicker"],
            focusTr: "sinyal kablosu, sensor kontagi veya gerilim seviyesi kararsiz",
            focusDe: "Signalleitung, Kontakt oder Spannungsniveau instabil sind",
            whyFocusTr: "titreyen giris reglemenin beklenmedik sekilde mod degistirmesine neden olur",
            whyFocusDe: "ein flatternder Eingang den Regler unvermittelt in andere Betriebsmodi druecken kann",
          },
        ],
      },
      {
        causeTr: "sensor, parametre ve cikis kontrol mantiginda olcum veya yazilim tarafli sapmalar bulunmasidir",
        causeDe: "an Sensorik, Parametern oder Ausgangslogik Mess- und Softwareabweichungen auftreten",
        checkTr: "sensor degerleri, referans olcumler ve cikis role davranislari birlikte karsilastirilir",
        checkDe: "Sensorwerte, Referenzmessung und Ausgangsrelais gemeinsam abgeglichen",
        whyTr: "yanlis bilgiyle beslenen kontrol mantigi saglam sistemi bile dengesiz gosterebilir",
        whyDe: "eine Regelung mit falscher Information selbst eine gesunde Anlage unruhig wirken lassen kann",
        mistakeTr: "tek bir ekrana bakip saha gercegini teyit etmemektir",
        mistakeDe: "nur auf einen Anzeigenwert zu schauen und die Feldrealitaet nicht zu bestaetigen",
        suggestions: ["sensor nereye konur", "kontrolor ayarlari neden onemli", "defrost neden bozulur"],
        variants: [
          {
            id: "electrical_sensor_open_circuit",
            trSubject: "sensor kopuk gorunuyor",
            deSubject: "der fuehler offen ist",
            extraKeywords: ["sensor open", "open circuit sensor"],
            focusTr: "NTC/PTC hattinin kopuk veya soketten cikmis olmasi",
            focusDe: "die NTC/PTC-Leitung unterbrochen oder am Stecker geloest ist",
            whyFocusTr: "kopuk sensor kontroloru en yuksek ya da anlamsiz degere iter",
            whyFocusDe: "ein offener Fuehler den Regler oft auf Extremwerte zwingt",
          },
          {
            id: "electrical_sensor_short_circuit",
            trSubject: "sensor kisa devre hata veriyor",
            deSubject: "der fuehler kurzschluss hat",
            extraKeywords: ["sensor short", "fuehler kurzschluss"],
            focusTr: "sensor kablosunun ezilmesi veya icten kisalmasi",
            focusDe: "das Fuehlerkabel gequetscht ist oder intern kurzschliesst",
            whyFocusTr: "kisa devreli sensor ekrani aşiri soguk veya aşiri sicak gostertebilir",
            whyFocusDe: "ein kurzgeschlossener Fuehler unplausible Extremwerte anzeigen kann",
          },
          {
            id: "electrical_sensor_drift",
            trSubject: "sensor dogrulugu kaymis",
            deSubject: "der fuehler driftet",
            extraKeywords: ["sensor drift", "kalibrasyon"],
            focusTr: "zamanla sensorun referans degerden sapmasi",
            focusDe: "der Fuehler im Lauf der Zeit vom Referenzwert abweicht",
            whyFocusTr: "kucuk sensor sapmasi kritik depolarda buyuk urun farki yaratabilir",
            whyFocusDe: "selbst kleine Sensorabweichungen bei sensiblen Raeumen grosse Folgen haben",
          },
          {
            id: "electrical_wrong_parameters",
            trSubject: "kontrol parametreleri yanlis",
            deSubject: "die reglerparameter falsch sind",
            extraKeywords: ["parameter wrong", "kontrol ayari"],
            focusTr: "set, diferans, fan gecikme veya defrost parametrelerinin uygulamaya uymamasi",
            focusDe: "Sollwert, Differenz, Fanverzoegerung oder Abtauparameter nicht zur Anwendung passen",
            whyFocusTr: "dogru cihaz bile yanlis parametreyle sahada yanlis cihaz gibi davranir",
            whyFocusDe: "selbst richtige Hardware mit falschen Parametern wie eine falsche Anlage wirkt",
          },
          {
            id: "electrical_output_relay_stuck",
            trSubject: "kontrolor cikis rolesi yapisik kaliyor",
            deSubject: "das ausgangsrelais haengen bleibt",
            extraKeywords: ["output relay", "relay stuck"],
            focusTr: "cikis role kontaklarinin yapismasi veya gecikmeli dusmesi",
            focusDe: "die Ausgangsrelais kleben oder zu spaet abfallen",
            whyFocusTr: "cikis rolu yapisinca kompresor, fan veya rezistans komutsuz kalmaz",
            whyFocusDe: "ein klebendes Ausgangsrelais Lasten ohne saubere Freigabe eingeschaltet halten kann",
          },
        ],
      },
      {
        causeTr: "pano ici montaj, kablolama ve topraklama disiplininin zayif olmasidir",
        causeDe: "Schaltschrankaufbau, Verdrahtung und Erdung nicht sauber ausgefuehrt sind",
        checkTr: "klemensler, topraklama, soketler, etiketleme ve kablo guzergahi birlikte incelenir",
        checkDe: "Klemmen, Erdung, Stecker, Beschriftung und Kabelfuehrung zusammen geprueft",
        whyTr: "duzensiz pano zamanla hem ariza hem de yanlis teshis kaynagi olur",
        whyDe: "ein unordentlicher Schaltschrank mit der Zeit sowohl Fehler als auch Fehldiagnosen erzeugt",
        mistakeTr: "gorsel olarak duzgun sandigi kablolamayi olcuyle dogrulamamaktir",
        mistakeDe: "eine optisch ordentliche Verdrahtung nicht messtechnisch zu bestaetigen",
        suggestions: ["gevsek klemens ne yapar", "topraklama neden onemli", "nem panoya girerse ne olur"],
        variants: [
          {
            id: "electrical_loose_terminal",
            trSubject: "gevsek klemens isiniyor",
            deSubject: "eine lose klemme heiss wird",
            extraKeywords: ["loose terminal", "klemens gevsek"],
            focusTr: "vida sikiliginin zamanla kaybolmasi",
            focusDe: "die Schraubverbindung mit der Zeit locker wird",
            whyFocusTr: "gevsek klemens yuk altinda gerilim dusurup yanik izine gider",
            whyFocusDe: "eine lose Klemme unter Last Spannung verliert und bis zu Brandspuren fuehrt",
          },
          {
            id: "electrical_panel_moisture",
            trSubject: "pano icine nem giriyor",
            deSubject: "feuchtigkeit in den schaltschrank gelangt",
            extraKeywords: ["panel moisture", "schaltschrank feucht"],
            focusTr: "yikama, terleme veya conta zaafiyetiyle panoya nem tasinmasi",
            focusDe: "durch Reinigung, Schwitzwasser oder schlechte Dichtungen Feuchte in den Schaltschrank gelangt",
            whyFocusTr: "nem korozyon ve kacaga giden yavas ama sinsi bir ariza baslatir",
            whyFocusDe: "Feuchte eine langsame, aber gefaehrliche Kette aus Korrosion und Leckstroemen startet",
          },
          {
            id: "electrical_corroded_terminals",
            trSubject: "terminal ve soketler oksitleniyor",
            deSubject: "klemmen und stecker korrodieren",
            extraKeywords: ["corrosion", "oksit"],
            focusTr: "nemli ve agresif ortam nedeniyle baglanti yuzeylerinin bozulmasi",
            focusDe: "in feuchter oder aggressiver Umgebung Kontaktflaechen korrodieren",
            whyFocusTr: "oksit temiz gorunup yine de gerilim kaybi yaratabilir",
            whyFocusDe: "Korrosion auch bei scheinbar intaktem Stecker erheblichen Uebergangswiderstand verursachen kann",
          },
          {
            id: "electrical_cross_wiring",
            trSubject: "kablolama capraz veya yanlis etiketli",
            deSubject: "die verdrahtung vertauscht oder falsch beschriftet ist",
            extraKeywords: ["cross wiring", "yanlis etiket"],
            focusTr: "montaj veya servis sonrasi kablolarin dogru yere donmemesi",
            focusDe: "Leitungen nach Montage oder Service nicht an die richtigen Punkte zurueckgefuehrt wurden",
            whyFocusTr: "capraz baglanti sahada mantiksiz gibi duran arizalar uretir",
            whyFocusDe: "vertauschte Leitungen scheinbar unlogische Fehlerbilder erzeugen",
          },
          {
            id: "electrical_bad_grounding",
            trSubject: "topraklama zayif oldugu icin garip arizalar cikiyor",
            deSubject: "eine schlechte erdung seltsame stoerungen verursacht",
            extraKeywords: ["bad grounding", "topraklama zayif"],
            focusTr: "toprak referansinin yuksek empedansli veya kopuk olmasi",
            focusDe: "der Erdungsbezug hochohmig oder unterbrochen ist",
            whyFocusTr: "zayif topraklama hem guvenlik hem olcum kalitesi icin sorun yaratir",
            whyFocusDe: "schlechte Erdung sowohl Sicherheit als auch Messstabilitaet zerstoert",
          },
        ],
      },
      {
        causeTr: "isitici devreleri ve yardimci rezistanslarda kopukluk, kacaga gitme veya kumanda eksigi olmasidir",
        causeDe: "Heizkreise und Zusatzheizungen unterbrochen, undicht oder falsch angesteuert sind",
        checkTr: "rezistans direnci, izolasyon durumu, role cikisi ve gerçek akim cekisi birlikte kontrol edilir",
        checkDe: "Heizungswiderstand, Isolation, Relaisausgang und reale Stromaufnahme gemeinsam geprueft",
        whyTr: "yardimci isiticilar soguk oda sisteminde konfor degil, isletme guvenligi icin de gereklidir",
        whyDe: "Hilfsheizungen im Kuehlraum nicht Luxus, sondern oft betriebliche Notwendigkeit sind",
        mistakeTr: "rezistansi sadece omik okuyup yuk altinda cekip cekmedigine bakmamaktir",
        mistakeDe: "die Heizung nur ohmisch zu pruefen und den Betrieb unter Last nicht zu kontrollieren",
        suggestions: ["defrost neden calismiyor", "kapi rezistansi ne ise yarar", "kacak akim neden atar"],
        variants: [
          {
            id: "electrical_crankcase_heater_power",
            trSubject: "krankcase isiticisina enerji gelmiyor",
            deSubject: "die sumpfheizung keine spannung hat",
            extraKeywords: ["crankcase heater", "sumpfheizung"],
            focusTr: "kompresor karter isiticisinin beslemesinin kesik olmasi",
            focusDe: "die Versorgung der Oelsumpfheizung unterbrochen ist",
            whyFocusTr: "isitici olmazsa sogutucu akiskan kartere goc ederek ilk kalkisi bozar",
            whyFocusDe: "ohne Heizung Kaeltemittel ins Oel wandert und den Start verschlechtert",
          },
          {
            id: "electrical_defrost_heater_leakage",
            trSubject: "defrost rezistansi kacak yapiyor",
            deSubject: "die abtauheizung ableitstrom hat",
            extraKeywords: ["defrost heater leakage", "rezistans kacak"],
            focusTr: "rezistans izolasyonunun bozulmasi",
            focusDe: "die Isolation der Abtauheizung beschaedigt ist",
            whyFocusTr: "kacakli rezistans hem yetersiz isitma hem RCD atmasi yapabilir",
            whyFocusDe: "eine undichte Heizung sowohl zu schwacher Leistung als auch FI-Ausloesung fuehren kann",
          },
          {
            id: "electrical_anti_sweat_heater_dead",
            trSubject: "anti sweat rezistansi calismiyor",
            deSubject: "die anti-schwitz-heizung ausfaellt",
            extraKeywords: ["anti sweat heater", "terleme rezistansi"],
            focusTr: "kapı veya kasa etrafindaki yardimci isiticinin devre disi kalmasi",
            focusDe: "die Hilfsheizung an Tuer oder Rahmen ausfaellt",
            whyFocusTr: "bu hat bozulursa yogusma, buzlanma ve zor kapanan kapilar baslar",
            whyFocusDe: "ohne diese Heizung Kondensat, Vereisung und schlecht schliessende Tueren entstehen",
          },
          {
            id: "electrical_door_heater_fault",
            trSubject: "kapi rezistansi bozuk",
            deSubject: "die tuerheizung defekt ist",
            extraKeywords: ["door heater", "tuerheizung"],
            focusTr: "esik veya kasa rezistansinin kopuk ya da enerjisiz olmasi",
            focusDe: "Schwellen- oder Rahmenheizung unterbrochen oder spannungslos ist",
            whyFocusTr: "ozellikle negatif odada kapi cevresi isitilmezse buz kilidi olusur",
            whyFocusDe: "besonders im Tiefkuehlraum ohne Türheizung schnell Eisbildung entsteht",
          },
          {
            id: "electrical_heater_output_no_voltage",
            trSubject: "isitici cikisinda voltaj yok",
            deSubject: "am heizausgang keine spannung anliegt",
            extraKeywords: ["heater output", "rezistans cikisi"],
            focusTr: "role, SSR veya kontrol karti cikisinin yuk tasimamasidir",
            focusDe: "Relais, SSR oder Karten-Ausgang die Last nicht freigeben",
            whyFocusTr: "isitici saglam olsa da cikis komutu gelmezse sistem defrost veya anti-fog gorevini yapamaz",
            whyFocusDe: "selbst eine intakte Heizung ohne Ausgangsfreigabe keine Funktion erfuellt",
          },
        ],
      },
      {
        causeTr: "surucu, haberlesme ve elektronik moduller asiri akim, isi veya EMC etkisiyle bozulmasidir",
        causeDe: "Frequenzumrichter, Kommunikation und Elektronik durch Strom, Temperatur oder EMV belastet werden",
        checkTr: "surucu hata kodu, fan sogutmasi, kablo ekranlamasi ve haberlesme hatti birlikte okunur",
        checkDe: "Umrichtercode, Eigenkuehlung, Schirmung und Kommunikationsleitung gemeinsam bewertet werden",
        whyTr: "modern sogutma sisteminde elektronik katman sagliksizsa mekanik kisim da yanlis gorunur",
        whyDe: "in modernen Anlagen die Elektronikschicht ueber die Sicht auf den mechanischen Zustand mitentscheidet",
        mistakeTr: "kod gormeden modulu degistirmek veya ekranlamayi onemsiz sanmaktir",
        mistakeDe: "ohne Fehlercode Module zu tauschen oder EMV/Schirmung zu unterschaetzen",
        suggestions: ["surucu arizasi nasil okunur", "haberlesme neden kopar", "emc gürültüsü ne yapar"],
        variants: [
          {
            id: "electrical_inverter_fault",
            trSubject: "surucu genel hata veriyor",
            deSubject: "der frequenzumrichter eine allgemeine stoerung zeigt",
            extraKeywords: ["inverter fault", "surucu hata"],
            focusTr: "surucu kendi koruma kodlarindan biriyle cikisa gecmiyor",
            focusDe: "der Frequenzumrichter wegen eines eigenen Schutzcodes nicht freigibt",
            whyFocusTr: "surucu kodu yorumlanmadan mekanik ariza tespiti eksik kalir",
            whyFocusDe: "ohne Deutung des Umrichtercodes die mechanische Diagnose unvollstaendig bleibt",
          },
          {
            id: "electrical_inverter_overcurrent",
            trSubject: "surucu asiri akim alarmi veriyor",
            deSubject: "der umrichter ueberstrom meldet",
            extraKeywords: ["inverter overcurrent", "overcurrent drive"],
            focusTr: "motor yukunun, hizlanma rampasinin veya kisa devre riskinin fazla olmasi",
            focusDe: "Motorlast, Rampenzeit oder Kurzschlussnaehe zu hoch sind",
            whyFocusTr: "surucu akim korumasi motoru ve modulu birlikte korur",
            whyFocusDe: "die Ueberstromschutzfunktion sowohl Motor als auch Elektronik schuetzt",
          },
          {
            id: "electrical_inverter_overheat",
            trSubject: "surucu asiri isinma yapiyor",
            deSubject: "der umrichter ueberhitzt",
            extraKeywords: ["inverter overheat", "drive overtemp"],
            focusTr: "havalandirma yetersizligi veya panel ici isi birikmesi",
            focusDe: "mangelnde Belueftung oder Waermestau im Schaltschrank",
            whyFocusTr: "surucu sicakligi yukseldikce elektronik omur ve stabilite duser",
            whyFocusDe: "mit steigender Umrichtertemperatur Lebensdauer und Stabilitaet sinken",
          },
          {
            id: "electrical_bus_communication_fault",
            trSubject: "haberlesme hatti kopuyor",
            deSubject: "die bus-kommunikation ausfaellt",
            extraKeywords: ["communication bus", "modbus", "haberlesme"],
            focusTr: "iletisim kablosu, terminasyon veya adresleme sorunlari",
            focusDe: "Kommunikationsleitung, Terminierung oder Adressierung fehlerhaft sind",
            whyFocusTr: "haberlesme kopunca sahadaki bircok parca saglam olsa bile sistem kontrolu bozulur",
            whyFocusDe: "bei Kommunikationsausfall intakte Feldgeraete trotzdem falsch oder gar nicht angesteuert werden",
          },
          {
            id: "electrical_emc_noise",
            trSubject: "elektrik gürültüsü sahayi bozuyor",
            deSubject: "elektrische stoerimpulse die anlage beeinflussen",
            extraKeywords: ["emc noise", "gurultu", "interference"],
            focusTr: "surucu, uzun kablo veya topraklama eksigi yuzunden parazit tasinmasi",
            focusDe: "durch Umrichter, lange Leitungen oder schlechte Erdung Stoerimpulse eingekoppelt werden",
            whyFocusTr: "parazit sensor ve haberlesmeyi bozup yalanci ariza uretebilir",
            whyFocusDe: "EMV-Stoerungen Sensorik und Kommunikation verfaelschen koennen",
          },
        ],
      },
      {
        causeTr: "saha emniyet, switch ve yardimci girislerde yanlis durum bilgisi uretilmesidir",
        causeDe: "Sicherheitsschalter und Hilfseingaenge im Feld falsche Zustandsinformationen liefern",
        checkTr: "switch zinciri, kapi kontagi, acil stop ve uzaktan enable hatlari tek tek dogrulanir",
        checkDe: "Schalterkette, Tuerkontakt, Not-Aus und Freigabeeingaenge einzeln verifiziert werden",
        whyTr: "yanlis bilgi veren bir emniyet girisi saglam sistemi bos yere kilitleyebilir",
        whyDe: "ein falsches Sicherheitssignal eine gesunde Anlage unnoetig verriegeln kann",
        mistakeTr: "tek bir bypass ile sistemi gecici calistirip kok nedeni kaybetmektir",
        mistakeDe: "mit einem schnellen Bypass die Anlage kurz zu starten und dabei die Grundursache zu verlieren",
        suggestions: ["emniyet zinciri nasil okunur", "door switch ne yapar", "alarm sadece gece neden gelir"],
        variants: [
          {
            id: "electrical_door_switch_fault",
            trSubject: "kapi switchi yanlis durum okuyor",
            deSubject: "der tuerschalter falsche zustande meldet",
            extraKeywords: ["door switch", "tuerschalter"],
            focusTr: "kapinin kapali olmasina ragmen switchin acik bilgisi vermesi",
            focusDe: "der Schalter trotz geschlossener Tuer einen offenen Zustand meldet",
            whyFocusTr: "yanlis kapi bilgisi fan ve alarm lojigini gereksiz degistirir",
            whyFocusDe: "eine falsche Tuerinfo Ventilator- und Alarmlogik unnötig veraendert",
          },
          {
            id: "electrical_emergency_stop_fault",
            trSubject: "acil stop devresi problemli",
            deSubject: "der not-aus-kreis fehlerhaft ist",
            extraKeywords: ["emergency stop", "not aus"],
            focusTr: "acil stop hatti oksitli, gevsek veya yarim kontakli",
            focusDe: "der Not-Aus-Kreis oxidiert, locker oder nur halb schliessend ist",
            whyFocusTr: "emniyet devresinde yarim kontak anlik dur-kalklara yol acar",
            whyFocusDe: "Teilkontakt im Sicherheitskreis zu sporadischen Stopps fuehren kann",
          },
          {
            id: "electrical_remote_enable_missing",
            trSubject: "uzaktan calis izni gelmiyor",
            deSubject: "die fernfreigabe fehlt",
            extraKeywords: ["remote enable", "extern freigabe"],
            focusTr: "BMS, PLC veya harici kuru kontagin izin sinyali gelmemesi",
            focusDe: "die Freigabe von BMS, SPS oder externem Kontakt ausbleibt",
            whyFocusTr: "saha cihazi saglam olsa da ust sistem izni olmadan devreye girmez",
            whyFocusDe: "auch eine gesunde Anlage ohne Freigabe des Leitsystems nicht anlaufen darf",
          },
          {
            id: "electrical_night_mode_input_stuck",
            trSubject: "gece modu girisi takili kaliyor",
            deSubject: "der nachtschalt-eingang haengen bleibt",
            extraKeywords: ["night mode input", "nachtschaltung"],
            focusTr: "harici girisin kalici aktif kalmasi yuzunden cihazin yanlis modda kalmasi",
            focusDe: "ein externer Eingang dauerhaft aktiv bleibt und den Regler im falschen Modus haelt",
            whyFocusTr: "mod sinyali takili kalirsa kullanici cihaz arizali sanabilir",
            whyFocusDe: "ein haengender Moduseingang wie ein Geraetefehler wirken kann",
          },
          {
            id: "electrical_interlock_wiring_fault",
            trSubject: "interlock kablolamasi yanlis",
            deSubject: "die verriegelungsverdrahtung falsch ist",
            extraKeywords: ["interlock wiring", "verriegelung"],
            focusTr: "seri-paralel emniyet baglantilarinin sahada hatali kurulmasi",
            focusDe: "Sicherheitsverriegelungen im Feld falsch in Serie oder Parallel verdrahtet wurden",
            whyFocusTr: "yanlis interlock bazen hic baslamayan bazen de kontrolsuz calisan sistem yaratir",
            whyFocusDe: "eine falsche Verriegelung je nach Fehlerbild Sperren oder unkontrollierten Betrieb erzeugt",
          },
        ],
      },
    ],
  },
  {
    key: "refrigeration",
    output: "drc_man_refrigeration_faq.json",
    sourceSummary: "DRC MAN kompresor valf ve gaz devresi ustasi egitimi",
    expertTr: "gaz devresi ustasi",
    expertDe: "ein Kaeltekreis-Meister",
    families: [
      {
        causeTr: "sarj miktari ile likit kararliliginin sistem ihtiyacina uymamasidir",
        causeDe: "Fuellmenge und Stabilitaet der Fluessigkeitsseite nicht zum System passen",
        checkTr: "subcool, sight glass, basma-emis degerleri ve etiket sarji birlikte okunur",
        checkDe: "Subcooling, Schauglas, Hoch-/Niederdruck und Sollfuellung gemeinsam bewertet werden",
        whyTr: "gaz devresinde dogru sarj sadece kapasiteyi degil kompresor guvenligini de belirler",
        whyDe: "die richtige Fuellung im Kaeltekreis nicht nur Leistung, sondern auch Verdichtersicherheit bestimmt",
        mistakeTr: "manometreye bakip hemen gaz eklemek veya gaz bosaltmaktir",
        mistakeDe: "nur auf den Druck zu schauen und sofort nachzufuellen oder abzulassen",
        suggestions: ["subcool neden onemli", "sight glass ne anlatir", "gaz eksigi nasil anlasilir"],
        variants: [
          {
            id: "refrigeration_shortage",
            trSubject: "gaz eksikligi var",
            deSubject: "kaeltemittelmangel vorliegt",
            extraKeywords: ["refrigerant shortage", "gaz eksigi"],
            focusTr: "kacak veya eksik sarj nedeniyle sistemin sivi tarafinin bos kalmasi",
            focusDe: "durch Leckage oder Unterfuellung die Fluessigkeitsseite zu wenig Reserve hat",
            whyFocusTr: "gaz eksiginde hem kapasite hem kompresor sogutmasi zarar gorur",
            whyFocusDe: "bei Kaeltemittelmangel sowohl Leistung als auch Verdichterkuehlung leiden",
          },
          {
            id: "refrigeration_overcharge",
            trSubject: "sistemde fazla gaz var",
            deSubject: "die anlage ueberfuellt ist",
            extraKeywords: ["overcharge", "fazla gaz"],
            focusTr: "gereginden fazla sarjla likit tarafa gereksiz yiginak yapilmasi",
            focusDe: "durch Ueberfuellung unnoetig viel Fluessigkeit im System gestaut wird",
            whyFocusTr: "fazla gaz basinç ve enerji tuketimini sebepsiz yukseltir",
            whyFocusDe: "Ueberfuellung Druck und Energieverbrauch unnoetig erhoeht",
          },
          {
            id: "refrigeration_flash_gas",
            trSubject: "likit hattinda flash gas olusuyor",
            deSubject: "in der fluessigkeitsleitung flash-gas entsteht",
            extraKeywords: ["flash gas", "likit hatti kabarcik"],
            focusTr: "likit hattinda subcool kaybi veya isi kazanci olmasi",
            focusDe: "in der Fluessigkeitsleitung Subcooling verloren geht oder Waerme eingetragen wird",
            whyFocusTr: "flash gas olursa genlesme elemanina temiz sivi gitmez",
            whyFocusDe: "bei Flash-Gas das Expansionsorgan keine saubere Fluessigkeit mehr bekommt",
          },
          {
            id: "refrigeration_low_subcool",
            trSubject: "subcool dusuk cikiyor",
            deSubject: "das subcooling zu niedrig ist",
            extraKeywords: ["low subcool", "subcool dusuk"],
            focusTr: "kondenser cikisinda yeterli sivi kolonu olusmamasi",
            focusDe: "am Verfluessigerausgang keine stabile Fluessigkeitssauele entsteht",
            whyFocusTr: "dusuk subcool sivi hattini kararsizlastirip beslemeyi bozar",
            whyFocusDe: "niedriges Subcooling die Fluessigkeitsversorgung instabil macht",
          },
          {
            id: "refrigeration_high_subcool",
            trSubject: "subcool gereksiz yuksek",
            deSubject: "das subcooling unnoetig hoch ist",
            extraKeywords: ["high subcool", "subcool yuksek"],
            focusTr: "likit tarafinda fazla stok veya tikanma benzeri birikim olmasi",
            focusDe: "in der Fluessigkeitsseite zu viel Reserve oder ein Stau entsteht",
            whyFocusTr: "asiri subcool bazen fazla sarj ya da akisa karsi direnç isareti olur",
            whyFocusDe: "zu hohes Subcooling oft auf Ueberfuellung oder Widerstand im Kreislauf hinweist",
          },
        ],
      },
      {
        causeTr: "sistem icinde hava, nem, asit veya yabanci partikuller kalmasidir",
        causeDe: "im System Luft, Feuchtigkeit, Saeure oder Schmutz zurueckgeblieben sind",
        checkTr: "vakum kalitesi, yag rengi, filter drier davranisi ve servis gecmisi birlikte sorgulanir",
        checkDe: "Vakuumqualitaet, Oelzustand, Filtertrockner-Verhalten und Servicehistorie gemeinsam ausgewertet werden",
        whyTr: "gaz devresindeki kirlilik valf ve kompresor sorununu zamanla buyutur",
        whyDe: "Verunreinigungen im Kaeltekreis Ventil- und Verdichterprobleme mit der Zeit vergroessern",
        mistakeTr: "yalniz sarj miktarina bakip sistem temizligini atlamaktir",
        mistakeDe: "nur auf die Fuellmenge zu schauen und die Systemreinheit zu ignorieren",
        suggestions: ["vakum neden onemli", "filter drier neden tikanir", "asidik yag nasil anlasilir"],
        variants: [
          {
            id: "refrigeration_noncondensables",
            trSubject: "sistemde yogusmayan gazlar var",
            deSubject: "nichtkondensierbare gase im system sind",
            extraKeywords: ["non-condensables", "hava kalmis"],
            focusTr: "vakum yetersizligi veya servis sirasinda hava karismasi",
            focusDe: "durch schlechtes Vakuum oder Service Luft in den Kreis gelangt",
            whyFocusTr: "yogusmayan gazlar kondenserde yer kaplayip basinç yukselmesine neden olur",
            whyFocusDe: "nichtkondensierbare Gase Platz im Verfluessiger belegen und Hochdruck erzeugen",
          },
          {
            id: "refrigeration_moisture_in_system",
            trSubject: "sistemde nem var",
            deSubject: "feuchtigkeit im system ist",
            extraKeywords: ["moisture in system", "nem var"],
            focusTr: "hatlar acik kalmis veya vakum yeterince derin yapilmamis olmasi",
            focusDe: "Leitungen offen standen oder das Vakuum nicht tief genug war",
            whyFocusTr: "nem genlesme elemaninda buz ve kararsiz calisma uretir",
            whyFocusDe: "Feuchtigkeit am Expansionsorgan zu Eis und instabilem Lauf fuehrt",
          },
          {
            id: "refrigeration_acid_in_oil",
            trSubject: "yag asitlenmis olabilir",
            deSubject: "das oel saeure gebildet hat",
            extraKeywords: ["acid oil", "asitli yag"],
            focusTr: "nem, yanik motor veya uzun sureli kirli calisma sonucu asit olusmasi",
            focusDe: "durch Feuchte, Motorbrand oder langes verschmutztes Arbeiten Saeure entsteht",
            whyFocusTr: "asitli yag kompresor ve sargilar icin sessiz ama ciddi bir tehdittir",
            whyFocusDe: "saeurehaltiges Oel Verdichter und Wicklungen still, aber massiv schaedigt",
          },
          {
            id: "refrigeration_dirty_oil",
            trSubject: "kompresor yagi kirlenmis",
            deSubject: "das verdichteroel verschmutzt ist",
            extraKeywords: ["dirty oil", "kirli yag"],
            focusTr: "parcacik, oksit veya karbon benzeri kirlerin yaga karismasi",
            focusDe: "Partikel, Oxid oder carbonartige Rueckstaende ins Oel gelangt sind",
            whyFocusTr: "kirli yag sadece yaglama degil valf ve yatak omrunu de bozar",
            whyFocusDe: "verschmutztes Oel nicht nur schmiert, sondern Ventile und Lager beschaedigt",
          },
          {
            id: "refrigeration_bad_vacuum",
            trSubject: "vakum iyi yapilmamis",
            deSubject: "das vakuum schlecht gezogen wurde",
            extraKeywords: ["bad vacuum", "vakum kotu"],
            focusTr: "hizli gecilen servis nedeniyle sistemin derin vakuma inmemesi",
            focusDe: "wegen zu schneller Arbeit kein tiefes und stabiles Vakuum erreicht wurde",
            whyFocusTr: "kotu vakum sonraki arizalari zincirleme sekilde baslatir",
            whyFocusDe: "schlechtes Vakuum spaetere Fehler kettenartig ausloest",
          },
        ],
      },
      {
        causeTr: "likit veya emiş hattinda akisi kisan mekanik bir daralma olmasidir",
        causeDe: "eine mechanische Verengung in Fluessigkeits- oder Saugleitung den Massenstrom drosselt",
        checkTr: "hat uzeri sicaklik dusumleri, filtre oncesi-sonrasi fark ve servis vanasi konumu okunur",
        checkDe: "Temperaturabfaelle an Leitungen, Vor-/Nachdifferenzen und Serviceventilstellung geprueft werden",
        whyTr: "devredeki daralma basinç, superheat ve kapasiteyi birden etkiler",
        whyDe: "eine Verengung gleichzeitig Druck, Superheat und Leistung verschiebt",
        mistakeTr: "daralmayi valf arizasi zannedip hatti incelememektir",
        mistakeDe: "eine Verengung fuer einen reinen Ventilfehler zu halten und die Leitung nicht zu pruefen",
        suggestions: ["filter drier neden tikanir", "sight glass kabarcigi ne anlatir", "servis vanasi nasil kontrol edilir"],
        variants: [
          {
            id: "refrigeration_filter_drier_restriction",
            trSubject: "filter drier tikali",
            deSubject: "der filtertrockner verstopft ist",
            extraKeywords: ["filter drier blocked", "tikali drier"],
            focusTr: "kir, lehim oksidi veya nemle drierin akisi bogmasi",
            focusDe: "Schmutz, Loetoxid oder Feuchte den Trockner zusetzen",
            whyFocusTr: "tikanik drier genlesme valfi oncesi sivi beslemesini acar birakir",
            whyFocusDe: "ein zugesetzter Trockner die Fluessigversorgung zum Ventil hungern laesst",
          },
          {
            id: "refrigeration_liquid_line_restriction",
            trSubject: "likit hattinda daralma var",
            deSubject: "die fluessigkeitsleitung eingeengt ist",
            extraKeywords: ["liquid line restriction", "likit daralma"],
            focusTr: "ezilme, yarim kapali vana veya kirlilik nedeniyle likit akisinin daralmasi",
            focusDe: "durch Quetschung, halb offenes Ventil oder Schmutz die Fluessigkeit abgewuergt wird",
            whyFocusTr: "likit daralmasi subcool var gibi gorunse bile valfe temiz besleme vermez",
            whyFocusDe: "eine Fluessigverengung trotz scheinbar vorhandenem Subcooling keine saubere Einspeisung liefert",
          },
          {
            id: "refrigeration_suction_restriction",
            trSubject: "emis hattinda kisit var",
            deSubject: "die saugleitung eingeengt ist",
            extraKeywords: ["suction restriction", "emis daralma"],
            focusTr: "hatta tikanma, servis vanasi problemi veya buz/kirlilik kaynakli engel olmasi",
            focusDe: "an der Saugleitung eine Verengung durch Ventil, Schmutz oder Vereisung besteht",
            whyFocusTr: "emiş kisiti kompresoru ac birakir ve kapasiteyi dusurur",
            whyFocusDe: "eine Saugverengung den Verdichter aushungert und die Leistung drueckt",
          },
          {
            id: "refrigeration_service_valve_half_open",
            trSubject: "servis vanasi yarim acik kalmis",
            deSubject: "das serviceventil halb offen steht",
            extraKeywords: ["half open valve", "servis vanasi yarim"],
            focusTr: "servis sonrasi vananin tam pozisyona alinmamasi",
            focusDe: "nach Service das Ventil nicht in Endstellung gebracht wurde",
            whyFocusTr: "yarim acik vana bazen daralma bazen yalanci basinç yorumu dogurur",
            whyFocusDe: "ein halb offenes Ventil je nach Stelle wie Drossel und Fehlmessung wirkt",
          },
          {
            id: "refrigeration_distributor_blocked",
            trSubject: "distributor veya dagitici tikanik",
            deSubject: "der verteiler verstopft ist",
            extraKeywords: ["distributor blocked", "dagitici tikanik"],
            focusTr: "ince dagitici yollarinda kir veya buz nedeniyle akis bozulmasi",
            focusDe: "an den feinen Verteilwegen Schmutz oder Eis den Fluss stoert",
            whyFocusTr: "dagitici tikanirsa evaporator bir bolgede calisir diger bolgede aclik yasar",
            whyFocusDe: "ein blockierter Verteiler den Verdampfer ungleichmaessig versorgt",
          },
        ],
      },
      {
        causeTr: "genlesme valfi ve cevresindeki ayar-montaj mantiginin dogru kurulmamasidir",
        causeDe: "Expansionsventil und seine Einbindung falsch eingestellt oder montiert sind",
        checkTr: "superheat, ampul baglantisi, nozzle/orifis tipi ve equalizer hatti birlikte kontrol edilir",
        checkDe: "Superheat, Fuehlerbefestigung, Duese und Equalizerleitung gemeinsam geprueft werden",
        whyTr: "valf tarafi dogru kurulmazsa evaporator ya acar kalir ya da ac kalir",
        whyDe: "eine falsche Ventilseite den Verdampfer entweder ueberfuettert oder aushungert",
        mistakeTr: "tek tur vida cevirip tum sorunu valfe baglamak",
        mistakeDe: "mit einer Schraubendrehung das ganze Problem dem Ventil zuzuschreiben",
        suggestions: ["superheat nasil dusunulur", "valf ayari neden onemli", "ampul nereye baglanir"],
        variants: [
          {
            id: "refrigeration_txv_too_closed",
            trSubject: "genlesme valfi fazla kisik",
            deSubject: "das expansionsventil zu stark schliesst",
            extraKeywords: ["txv too closed", "superheat yuksek"],
            focusTr: "valfin evaporatore yeterli sivi gondermemesi",
            focusDe: "das Ventil den Verdampfer mit zu wenig Fluessigkeit versorgt",
            whyFocusTr: "fazla kisik valf superheat yukselterek kapasiteyi öldurur",
            whyFocusDe: "ein zu knappes Ventil Superheat hebt und Leistung vernichtet",
          },
          {
            id: "refrigeration_txv_too_open",
            trSubject: "genlesme valfi fazla acik",
            deSubject: "das expansionsventil zu weit offen ist",
            extraKeywords: ["txv too open", "superheat dusuk"],
            focusTr: "valfin evaporatore gereksiz fazla sivi gondermesi",
            focusDe: "das Ventil dem Verdampfer zu viel Fluessigkeit gibt",
            whyFocusTr: "fazla acik valf sivi donusu ve kompresor riski yaratir",
            whyFocusDe: "ein zu offenes Ventil Fluessigkeitsruecklauf und Verdichterrisiko erzeugt",
          },
          {
            id: "refrigeration_txv_hunting",
            trSubject: "genlesme valfi avlaniyor",
            deSubject: "das expansionsventil huntet",
            extraKeywords: ["txv hunting", "valf avlaniyor"],
            focusTr: "valfin ac-kapa dengesinin kararsiz calismasi",
            focusDe: "das Ventil instabil zwischen zu und auf schwingt",
            whyFocusTr: "hunting durumunda basinç ve superheat duzgun okunmaz",
            whyFocusDe: "bei Hunting Druecke und Superheat stark schwanken und schwer lesbar werden",
          },
          {
            id: "refrigeration_wrong_nozzle",
            trSubject: "valf nozzle veya orifis yanlis",
            deSubject: "duese oder orifice am ventil falsch ist",
            extraKeywords: ["wrong nozzle", "orifice wrong"],
            focusTr: "kapasiteye uygun olmayan orifis kullanilmasi",
            focusDe: "eine Duese verwendet wird, die nicht zur Leistung passt",
            whyFocusTr: "yanlis orifis ayarla duzelmeyecek besleme hatasi yaratir",
            whyFocusDe: "eine falsche Duese einen Grundfehler erzeugt, den keine Einstellung sauber heilt",
          },
          {
            id: "refrigeration_equalizer_blocked",
            trSubject: "equalizer hatti tikali",
            deSubject: "die equalizerleitung blockiert ist",
            extraKeywords: ["equalizer blocked", "equalizer tikali"],
            focusTr: "harici equalizer hattinin basinci saglikli tasimamasi",
            focusDe: "die externe Equalizerleitung den Druck nicht sauber uebertraegt",
            whyFocusTr: "equalizer bozulursa valf evaporator sonundaki gercegi gormez",
            whyFocusDe: "ohne korrekte Equalizer-Info das Ventil den echten Verdampferzustand nicht kennt",
          },
        ],
      },
      {
        causeTr: "ampul ve valf aksesuarlarinin montaj detaylarinin dogru uygulanmamasidir",
        causeDe: "Fuehlerkugel und Ventilzubehoer montagebedingt falsch umgesetzt sind",
        checkTr: "ampul konumu, siki baglantisi, izolasyonu ve equalizer baglama mantigi birlikte degerlendirilir",
        checkDe: "Fuehlerposition, fester Sitz, Daemmung und Equalizeranschluss zusammen bewertet werden",
        whyTr: "kucuk montaj detayi valfin butun davranisini degistirebilir",
        whyDe: "ein kleines Montagedetail das gesamte Ventilverhalten veraendern kann",
        mistakeTr: "ampulu herhangi bir yere sarip gecmektir",
        mistakeDe: "die Fuehlerkugel beliebig irgendwo anzulegen",
        suggestions: ["ampul nereye baglanir", "superheat neden sasar", "equalizer ne ise yarar"],
        variants: [
          {
            id: "refrigeration_bulb_loose",
            trSubject: "valf ampulu gevsek",
            deSubject: "die fuehlerkugel lose sitzt",
            extraKeywords: ["bulb loose", "ampul gevsek"],
            focusTr: "ampulun boruyu yeterli basiyla hissetmemesi",
            focusDe: "die Fuehlerkugel die Leitung nicht mit sauberem Druck abtastet",
            whyFocusTr: "gevsek ampul valfi gecikmeli ve yanlis bilgiyle hareket ettirir",
            whyFocusDe: "eine lose Kugel das Ventil traege und fehlerhaft steuert",
          },
          {
            id: "refrigeration_bulb_wrong_position",
            trSubject: "valf ampulu yanlis pozisyonda",
            deSubject: "die fuehlerkugel falsch positioniert ist",
            extraKeywords: ["bulb wrong position", "ampul yeri"],
            focusTr: "ampulun emiş borusunda uygun saat pozisyonunda olmamasi",
            focusDe: "die Fuehlerkugel an der Saugleitung an unpassender Uhrposition sitzt",
            whyFocusTr: "yanlis pozisyon hava, yag veya sivi etkisiyle yanlis his uretir",
            whyFocusDe: "eine falsche Position durch Luft-, Oel- oder Fluessigkeitseinfluss falsche Werte liefert",
          },
          {
            id: "refrigeration_bulb_no_insulation",
            trSubject: "valf ampulu izolesiz",
            deSubject: "die fuehlerkugel nicht isoliert ist",
            extraKeywords: ["bulb no insulation", "ampul izolesiz"],
            focusTr: "ampulun dis ortamdan isi alip gercek boru sicakligini kaybetmesi",
            focusDe: "die Kugel von der Umgebung beeinflusst wird und nicht mehr nur die Rohrtemperatur fuehlt",
            whyFocusTr: "izolesiz ampul superheat hesabini kaydirir",
            whyFocusDe: "eine unisolierte Kugel die Superheat-Regelung verfaelscht",
          },
          {
            id: "refrigeration_equalizer_wrong_connection",
            trSubject: "equalizer baglantisi yanlis yerde",
            deSubject: "der equalizer falsch angeschlossen ist",
            extraKeywords: ["equalizer wrong", "equalizer baglanti"],
            focusTr: "equalizer hattinin gercek evaporator cikis basinç noktasindan alinmamasi",
            focusDe: "die Equalizerleitung nicht am richtigen Austrittspunkt des Verdampfers sitzt",
            whyFocusTr: "yanlis equalizer noktasi valfin goruntusunu bozar",
            whyFocusDe: "ein falscher Equalizerpunkt das Ventil mit einer falschen Druckrealitaet versorgt",
          },
          {
            id: "refrigeration_distributor_nozzle_mismatch",
            trSubject: "dagitici ve valf birbiriyle uyumsuz",
            deSubject: "verteiler und ventil nicht zusammenpassen",
            extraKeywords: ["distributor mismatch", "dagitici uyumsuz"],
            focusTr: "dagitici tipi ile valf/nozzle kombinasyonunun uyumlu secilmemesi",
            focusDe: "Verteiler und Ventil-/Duesenkombination nicht zueinander passen",
            whyFocusTr: "uyumsuzluk evaporatorun devreler arasi beslenmesini bozar",
            whyFocusDe: "eine Fehlpaarung die Verteilung auf die Verdampferkreise stoert",
          },
        ],
      },
      {
        causeTr: "solenoid, pump down ve dur-kalk sekansinin dogru islememesidir",
        causeDe: "Magnetventil, Pumpdown und Start-Stopp-Sequenz nicht sauber funktionieren",
        checkTr: "solenoid bobini, kapanma-acma davranisi, basinç esitlenmesi ve durus sonrasi kalkis birlikte izlenir",
        checkDe: "Spule, Oeffnungs-/Schliessverhalten, Druckausgleich und Wiederstart gemeinsam beobachtet werden",
        whyTr: "sekans hatalari basit valf arizasindan daha buyuk kompresor zorlanmasi yaratabilir",
        whyDe: "Sequenzfehler mehr als nur ein Ventilproblem sein und Verdichter massiv belasten koennen",
        mistakeTr: "yalniz bobine bakip kapanma mantigini okumamaktir",
        mistakeDe: "nur auf die Spule zu schauen und die Sequenzlogik zu ignorieren",
        suggestions: ["solenoid valf neden acmaz", "zor kalkis neden olur", "pump down nasil calisir"],
        variants: [
          {
            id: "refrigeration_solenoid_not_opening",
            trSubject: "solenoid valf acmiyor",
            deSubject: "das magnetventil nicht oeffnet",
            extraKeywords: ["solenoid not opening", "magnetventil oeffnet nicht"],
            focusTr: "bobin komutu olsa bile govdenin mekanik olarak takili kalmasi",
            focusDe: "trotz Spulensignal der Ventilkern mechanisch nicht freigibt",
            whyFocusTr: "acmayan solenoid evaporatori tamamen acliga itebilir",
            whyFocusDe: "ein nicht oeffnendes Magnetventil den Verdampfer komplett aushungert",
          },
          {
            id: "refrigeration_solenoid_leaking_through",
            trSubject: "solenoid valf kapiyor gibi ama sizdiriyor",
            deSubject: "das magnetventil im geschlossenen zustand durchlaesst",
            extraKeywords: ["solenoid leaking", "valf sizdiriyor"],
            focusTr: "oturma yuzeyi kirli veya hasarli oldugu icin tam kapanmama",
            focusDe: "Sitzflaeche verschmutzt oder beschaedigt ist und nicht dicht schliesst",
            whyFocusTr: "sızdiran solenoid pump down ve durus dengesini bozar",
            whyFocusDe: "ein durchlassendes Magnetventil Pumpdown und Stillstandsverhalten stoert",
          },
          {
            id: "refrigeration_pumpdown_failure",
            trSubject: "pump down calismiyor",
            deSubject: "pump-down nicht funktioniert",
            extraKeywords: ["pumpdown failure", "pump down"],
            focusTr: "solenoid, basinç switch veya kontrol sirasi yuzunden sistemin kendini cekememesi",
            focusDe: "durch Magnetventil, Druckschalter oder Steuerlogik kein sauberes Abpumpen stattfindet",
            whyFocusTr: "pump down bozuksa durus ve tekrar kalkis sekansi bozulur",
            whyFocusDe: "fehlerhaftes Pump-Down sowohl Stillstand als auch Neustart belastet",
          },
          {
            id: "refrigeration_pumpdown_sequence_wrong",
            trSubject: "pump down sirasi yanlis",
            deSubject: "die pump-down-sequenz falsch ist",
            extraKeywords: ["pumpdown sequence", "sekans yanlis"],
            focusTr: "kompresor ve solenoidin yanlis sira ile kapanip acilmasi",
            focusDe: "Verdichter und Magnetventil in falscher Reihenfolge schalten",
            whyFocusTr: "yanlis sekans yalanci ariza ve sivi donusu riski yaratabilir",
            whyFocusDe: "eine falsche Sequenz Stoerungen und Fluessigkeitsrisiken erzeugt",
          },
          {
            id: "refrigeration_pressure_equalization_fault",
            trSubject: "basinc esitlenmesi olmadan zor kalkiyor",
            deSubject: "ohne druckausgleich schwer anlaeuft",
            extraKeywords: ["pressure equalization", "hard start pressure"],
            focusTr: "durus sonrasi basincin rahatlayacak zamani bulmamasi",
            focusDe: "nach dem Stopp kein sauberer Druckausgleich zustande kommt",
            whyFocusTr: "yuk altinda start kompresoru elektrikten cok mekanik olarak yorar",
            whyFocusDe: "ein Start unter Drucklast den Verdichter mechanisch schwer belastet",
          },
        ],
      },
      {
        causeTr: "yag ve geri donus geometrisinin kompresoru saglikli beslememesidir",
        causeDe: "Oelmanagement und Ruecklaufgeometrie den Verdichter nicht sauber versorgen",
        checkTr: "hat capi, egim, kot farki, akim hizi ve karter davranisi birlikte okunur",
        checkDe: "Rohrdurchmesser, Gefaelle, Hoehenunterschied, Gasgeschwindigkeit und Kurbelgehause gemeinsam bewertet werden",
        whyTr: "kompresor yagi sadece karterde kalmaz; dogru tasarimla devreden geri gelmesi gerekir",
        whyDe: "Verdichteroel nicht nur im Sumpf bleibt, sondern ueber den Kreis sicher zurueckgefuehrt werden muss",
        mistakeTr: "yag sorununu sadece yag ekleyerek cozmeye calismaktir",
        mistakeDe: "ein Oelproblem nur durch Nachfuellen loesen zu wollen",
        suggestions: ["yag donusu neden onemli", "boru capi nasil secilir", "sivi donusu neden olur"],
        variants: [
          {
            id: "refrigeration_oil_return_poor",
            trSubject: "yag donusu zayif",
            deSubject: "der oelruecklauf schwach ist",
            extraKeywords: ["oil return", "yag donusu"],
            focusTr: "hat geometri ve hizlarin yagi kompresore geri tasiyamamasi",
            focusDe: "Rohrfuehrung und Geschwindigkeiten das Oel nicht sauber zum Verdichter bringen",
            whyFocusTr: "zayif yag donusu kompresor omrunu sessizce kisaltir",
            whyFocusDe: "schwacher Oelruecklauf die Verdichterlebensdauer schleichend verkuerzt",
          },
          {
            id: "refrigeration_missing_oil_trap",
            trSubject: "yag cebi eksik",
            deSubject: "eine oelfalle fehlt",
            extraKeywords: ["oil trap", "yag cebi"],
            focusTr: "dikey hatlarda gerekli oil trap detayinin bulunmamasi",
            focusDe: "bei Steigleitungen die noetige Oelfalle fehlt",
            whyFocusTr: "oil trap olmazsa dikey hatta yag asagi kalip geri donmez",
            whyFocusDe: "ohne Oelfalle Oel in der Steigleitung zurueckbleiben kann",
          },
          {
            id: "refrigeration_suction_line_too_large",
            trSubject: "emis borusu fazla buyuk",
            deSubject: "die saugleitung zu gross ist",
            extraKeywords: ["suction line too large", "emis capi buyuk"],
            focusTr: "gaz hizinin yagi tasiyamayacak kadar dusmesi",
            focusDe: "die Gasgeschwindigkeit zu niedrig wird, um Oel mitzunehmen",
            whyFocusTr: "asiri buyuk emiş hatti sessiz ama kalici yag donus sorunu yaratir",
            whyFocusDe: "eine zu grosse Saugleitung leise, aber dauerhaft Oelruecklaufprobleme verursacht",
          },
          {
            id: "refrigeration_suction_line_too_small",
            trSubject: "emis borusu fazla kucuk",
            deSubject: "die saugleitung zu klein ist",
            extraKeywords: ["suction line too small", "emis capi kucuk"],
            focusTr: "hatta asiri basinç kaybi olusturacak kadar dar cap secimi",
            focusDe: "ein zu kleiner Durchmesser starke Druckverluste in der Saugleitung erzeugt",
            whyFocusTr: "kucuk emiş hatti kompresoru aclik ve sicaklik stresiyle zorlar",
            whyFocusDe: "eine zu kleine Saugleitung den Verdichter mit Hunger und Temperaturstress belastet",
          },
          {
            id: "refrigeration_crankcase_dilution",
            trSubject: "karterde sogutucu akiskan birikiyor",
            deSubject: "kaeltemittel das kurbelgehause verduennt",
            extraKeywords: ["crankcase dilution", "karter seyrelmesi"],
            focusTr: "stop halinde gazin kartere goc etmesi ve yagi seyreltmesi",
            focusDe: "waehrend des Stillstands Kaeltemittel in den Sumpf wandert und das Oel verduennt",
            whyFocusTr: "seyrelmis yag ilk kalkista koruma ve yaglama zaafiyeti yaratir",
            whyFocusDe: "verduenntes Oel beim Start Schmierung und Schutz schwächt",
          },
        ],
      },
      {
        causeTr: "kompresorun beslenme, valfleme ve mekanik sagliginin bozulmasidir",
        causeDe: "Versorgung, Ventile und mechanischer Zustand des Verdichters ungesund sind",
        checkTr: "ses, akim, superheat, basma sicakligi ve yag davranisi birlikte degerlendirilir",
        checkDe: "Geraeusch, Strom, Superheat, Druckgastemperatur und Oelverhalten gemeinsam bewertet werden",
        whyTr: "kompresor arizalari genelde tek veriyle degil birden fazla belirtinin birlikte okunmasiyla anlasilir",
        whyDe: "Verdichterfehler meist erst ueber das Zusammenspiel mehrerer Symptome klar werden",
        mistakeTr: "kompresoru hemen mahkum edip onu bu hale getiren sebebi aramamaktir",
        mistakeDe: "den Verdichter sofort zu verurteilen und die verursachende Kette nicht zu suchen",
        suggestions: ["kompresore sivi neden doner", "basma sicakligi neden yukselir", "mekanik kompresor arizasi nasil anlasilir"],
        variants: [
          {
            id: "refrigeration_liquid_slugging",
            trSubject: "kompresore sivi vuruyor",
            deSubject: "fluessigkeit auf den verdichter schlaegt",
            extraKeywords: ["liquid slugging", "sivi vuruyor"],
            focusTr: "kompresore gaz yerine sivi ulasmasi",
            focusDe: "den Verdichter Fluessigkeit statt Gas erreicht",
            whyFocusTr: "sivi vuruntusu mekanik kirilma ve yatak hasarina gidebilir",
            whyFocusDe: "Fluessigkeitsschlaege zu mechanischen Schaeden und Lagerproblemen fuehren koennen",
          },
          {
            id: "refrigeration_floodback_after_defrost",
            trSubject: "defrost sonrasi kompresore fazla sivi donuyor",
            deSubject: "nach der abtauung zu viel fluessigkeit zurueckkommt",
            extraKeywords: ["floodback after defrost", "defrost sonrasi sivi"],
            focusTr: "defrost cikisinda evaporatorun kontrolsuz sekilde tasmasi",
            focusDe: "nach der Abtauung der Verdampfer unkontrolliert ueberfuettert wird",
            whyFocusTr: "defrost sonrasi floodback sik tekrar eden kompresor hasari sebebidir",
            whyFocusDe: "Floodback nach der Abtauung eine haeufige Ursache wiederkehrender Verdichterschaeden ist",
          },
          {
            id: "refrigeration_high_discharge_temp",
            trSubject: "basma sicakligi cok yuksek",
            deSubject: "die druckgastemperatur sehr hoch ist",
            extraKeywords: ["high discharge temp", "basma sicakligi"],
            focusTr: "yüksek superheat, aclik veya yetersiz sogutma nedeniyle kompresorun asiri isinmasi",
            focusDe: "durch hohen Superheat, Hunger oder schlechte Kuehlung der Verdichter thermisch ueberlastet wird",
            whyFocusTr: "yuksek basma sicakligi yag yapisini bozup motoru yorar",
            whyFocusDe: "eine hohe Druckgastemperatur Oel und Motor stark belastet",
          },
          {
            id: "refrigeration_worn_valves",
            trSubject: "kompresor valfleri kaciriyor",
            deSubject: "die verdichterventile undicht sind",
            extraKeywords: ["worn valves", "valf kacagi"],
            focusTr: "kompresor ic valflerinin asinarak geri kacirmasi",
            focusDe: "die inneren Verdichterventile verschlissen sind und zurueckblasen",
            whyFocusTr: "valf kacakli kompresor basinç farki uretmekte zorlanir",
            whyFocusDe: "ein Verdichter mit undichten Ventilen keine saubere Druckdifferenz aufbaut",
          },
          {
            id: "refrigeration_mechanical_wear",
            trSubject: "kompresorde mekanik yorgunluk var",
            deSubject: "der verdichter mechanisch verschlissen ist",
            extraKeywords: ["mechanical wear", "kompresor yorgun"],
            focusTr: "yatak, scroll veya piston gruplarinda omur sonu yorgunluk olusmasi",
            focusDe: "Lager, Scroll oder Kolbengruppe mechanisch ermuedet sind",
            whyFocusTr: "mekanik yorgunluk akim, ses ve performans dususuyle birlikte okunur",
            whyFocusDe: "mechanischer Verschleiss sich ueber Strom, Geraeusch und Leistung gemeinsam zeigt",
          },
        ],
      },
      {
        causeTr: "kondensasyon ve basinç kontrol mantiginin ortama uygun olmamasidir",
        causeDe: "Verfluessigung und Druckregelung nicht zur Umgebung und Last passen",
        checkTr: "kondenser fan sekansi, head pressure kontrolu, receiver seviyesi ve ortam sartlari birlikte okunur",
        checkDe: "Verfluessigerfans, Hochdruckregelung, Receiverstand und Umgebungsbedingungen gemeinsam bewertet werden",
        whyTr: "basma tarafi sagliksizsa tum gaz devresi zincirleme etkilenir",
        whyDe: "eine ungesunde Hochdruckseite den ganzen Kaeltekreis in Kette beeinflusst",
        mistakeTr: "yalniz gaz sarjina odaklanip head pressure mantigini atlamaktir",
        mistakeDe: "sich nur auf die Fuellmenge zu konzentrieren und die Hochdruckregelung zu ignorieren",
        suggestions: ["yuksek basinc neden olur", "receiver ne yapar", "fan sekansi nasil okunur"],
        variants: [
          {
            id: "refrigeration_head_pressure_control_wrong",
            trSubject: "head pressure kontrolu yanlis",
            deSubject: "die hochdruckregelung falsch arbeitet",
            extraKeywords: ["head pressure control", "basma kontrol"],
            focusTr: "fan veya valf mantiginin basinç hedefini dogru tutamamasi",
            focusDe: "Luefter oder Ventile den Verfluessigungsdruck nicht sauber halten",
            whyFocusTr: "head pressure saparsa valf beslenmesi ve verim birlikte bozulur",
            whyFocusDe: "schwankender KopfdrucK sowohl Ventilversorgung als auch Effizienz stoert",
          },
          {
            id: "refrigeration_fan_cycling_wrong",
            trSubject: "kondenser fan sekansi yanlis",
            deSubject: "die ventilatorstufung am verfluessiger falsch ist",
            extraKeywords: ["fan cycling wrong", "fan sekansi"],
            focusTr: "fanlarin devreye giris cikis basinc araliklarinin uygun olmamasi",
            focusDe: "die Schaltpunkte der Ventilatoren nicht zum Betriebsdruck passen",
            whyFocusTr: "yanlis sekans basinç dalgalanmasi ve gereksiz termik stres yaratir",
            whyFocusDe: "falsche Stufung Druckjagd und thermischen Stress erzeugt",
          },
          {
            id: "refrigeration_receiver_level_issue",
            trSubject: "receiver seviyesi sorunlu",
            deSubject: "der receiverstand problematisch ist",
            extraKeywords: ["receiver level", "receiver sorun"],
            focusTr: "receiverde gereksiz sivi birikimi veya yetersiz tampon olmasi",
            focusDe: "im Receiver zu viel oder zu wenig nutzbare Fluessigkeitsreserve vorhanden ist",
            whyFocusTr: "receiver davranisi sistemin mevsimsel ve yuk degisimine cevabini etkiler",
            whyFocusDe: "der Receiver das saisonale und lastbedingte Verhalten der Anlage praegt",
          },
          {
            id: "refrigeration_hot_gas_line_anomaly",
            trSubject: "sicak gaz hattinda anormallik var",
            deSubject: "an der heissgasleitung eine unregelmaessigkeit besteht",
            extraKeywords: ["hot gas line", "heissgas"],
            focusTr: "basma hattinin beklenenden asiri sicak veya dengesiz olmasi",
            focusDe: "die Heissgasleitung ungewollt zu heiss oder instabil ist",
            whyFocusTr: "sicak gaz davranisi kompresorun ne kadar zorlandigini dogrudan anlatir",
            whyFocusDe: "die Heissgasleitung direkt zeigt, wie hart der Verdichter arbeitet",
          },
          {
            id: "refrigeration_ambient_condensing_load",
            trSubject: "dis ortam basma tarafini cok zorluyor",
            deSubject: "die umgebung die hochdruckseite stark belastet",
            extraKeywords: ["ambient heat", "dis ortam sicak"],
            focusTr: "sicak dis hava, geri donen hava veya gunes yuzunden kondenserin zorlanmasi",
            focusDe: "durch heisse Aussenluft, Rueckansaugung oder Sonne der Verfluessiger ueberlastet wird",
            whyFocusTr: "kotu ortam sartlari gaz devresi arizasi gibi gorunen basinç sorunlari yaratabilir",
            whyFocusDe: "schlechte Umgebungsbedingungen druckseitige Symptome wie einen Kaeltekreisfehler erzeugen koennen",
          },
        ],
      },
      {
        causeTr: "dusuk yuk, yanlis uygulama veya urun tarafi ihtiyacinin gaz devresiyle uyumsuz olmasidir",
        causeDe: "geringe Last, falsche Anwendung oder Produktanforderung nicht zum Kaeltekreis passen",
        checkTr: "urun tipi, cekirdek soguma hedefi, oda tipi ve yuk dalgalanmasi birlikte degerlendirilir",
        checkDe: "Produkttyp, Kernabkuehlziel, Raumtyp und Lastschwankung gemeinsam bewertet werden",
        whyTr: "bazen ariza gaz devresinde degil uygulamanin secim mantigindadir",
        whyDe: "manchmal liegt die Stoerung nicht im Kreis, sondern in der Auswahl der Anwendung",
        mistakeTr: "muhafaza odasindan sok oda performansi beklemektir",
        mistakeDe: "von einem Lagerraum die Leistung eines Schockraums zu erwarten",
        suggestions: ["sok oda ile muhafaza odasi farki", "cekirdek soguma neden gecikir", "dusuk yukta sistem neden avlanir"],
        variants: [
          {
            id: "refrigeration_short_cycle_low_load",
            trSubject: "dusuk yukte sistem sik devreye girip cikiyor",
            deSubject: "die anlage bei geringer last stark taktet",
            extraKeywords: ["short cycle low load", "dusuk yuk takti"],
            focusTr: "mevcut kapasitenin o anki yuke fazla gelmesi",
            focusDe: "die installierte Leistung fuer die momentane Last zu gross ist",
            whyFocusTr: "dusuk yukta takting gaz devresi okumalarini da kararsizlastirir",
            whyFocusDe: "Takten bei geringer Last auch die Kaeltekreiswerte schwer interpretierbar macht",
          },
          {
            id: "refrigeration_product_freezing_plus_room",
            trSubject: "arti odada urun donuyor",
            deSubject: "ware im plusraum einfriert",
            extraKeywords: ["plus room freezing", "arti oda donma"],
            focusTr: "hava karakteri ve lokal sicaklik urune ortalama odadan daha sert vuruyor",
            focusDe: "Luftcharakter und lokale Temperatur die Ware haerter treffen als den Raumdurchschnitt",
            whyFocusTr: "dogru gaz devresi bile yanlis uygulamada urunu bozabilir",
            whyFocusDe: "selbst ein sauberer Kaeltekreis bei falscher Anwendung die Ware schaedigen kann",
          },
          {
            id: "refrigeration_product_not_reaching_core_temp",
            trSubject: "urun cekirdek sicakliga inmiyor",
            deSubject: "die ware ihre kerntemperatur nicht erreicht",
            extraKeywords: ["core temp", "cekirdek sicaklik"],
            focusTr: "oda sicagi ile urun merkezi arasindaki farkin goz ardi edilmesi",
            focusDe: "der Unterschied zwischen Raumluft und Produktkern unterschaetzt wird",
            whyFocusTr: "cekirdek soguma hava sicagindan daha yavas ve farkli bir problemdir",
            whyFocusDe: "Kernabkuehlung ein anderes und langsameres Problem als reine Raumluftkuehlung ist",
          },
          {
            id: "refrigeration_long_line_imbalance",
            trSubject: "uzun hat nedeniyle devre dengesiz",
            deSubject: "die lange leitung den kreislauf aus dem gleichgewicht bringt",
            extraKeywords: ["long line", "uzun hat"],
            focusTr: "uzun borulamada sarj, yag ve basinç kaybinin birlikte buyumesi",
            focusDe: "bei langer Leitung Fuellung, Oel und Druckverlust gemeinsam wachsen",
            whyFocusTr: "uzun hatlar standart kisa hat mantigiyla okunursa hata kacirilir",
            whyFocusDe: "lange Leitungen nicht mit der gleichen Logik wie kurze Leitungen bewertet werden duerfen",
          },
          {
            id: "refrigeration_suction_accumulator_issue",
            trSubject: "suction accumulator gorevini yapmiyor",
            deSubject: "der saugakkumulator nicht richtig arbeitet",
            extraKeywords: ["suction accumulator", "akkumulator"],
            focusTr: "sivi tutma ve geri besleme davranisinin bozulmasi",
            focusDe: "die Rueckhaltung und dosierte Rueckgabe von Fluessigkeit nicht sauber klappt",
            whyFocusTr: "akkumulator arizasi kompresoru korumasiz birakabilir",
            whyFocusDe: "ein fehlerhafter Akkumulator den Verdichter ungeschuetzt laesst",
          },
        ],
      },
    ],
  },
];

packs.forEach(expandPack);
