"use strict";

/**
 * DRC MAN arıza/troubleshooting kelime havuzları.
 * server/app.js'in queryAssistant + DRC MAN intent classification yollarında
 * kullanılır. Salt veri — davranış burada yok.
 */

const TROUBLESHOOTING_BANK_CACHE_TTL_MS = 2 * 60 * 1000;

// Soru içinde geçtiğinde "kuvvetle troubleshooting" işareti veren TR/DE/EN
// teknik ifadeler. Genleşme valfı, basınç, gaz, kompresör konuları.
const TROUBLESHOOTING_STRONG_HINTS = [
  "ariza",
  "sorun",
  "hata",
  "alarm",
  "problem",
  "fault",
  "storung",
  "fehler",
  "kompresor",
  "compressor",
  "verdichter",
  "basinc",
  "pressure",
  "evaporator",
  "verdampfer",
  "defrost",
  "abtau",
  "buz",
  "ice",
  "fan",
  "ventilator",
  "drenaj",
  "drain",
  "sensor",
  "txv",
  "genlesme",
  "presostat",
  "kontaktor",
  "contactors",
  "solenoid",
  "magnetventil",
  "r404a",
  "r404",
  "r4040",
  "r134a",
  "r134",
  "r290",
  "gaz",
  "kacak",
  "leak",
  "vacuum",
  "vakum",
  "flare",
  "charge",
  "undercharge",
  "overcharge",
  "superheat",
  "subcool",
  "noncondensable",
  "moisture",
  "oil return",
  "hpc",
  "lpc",
];

// Çok kısa ama anlamlı sektörel kısaltmalar — normal stop word filtresi
// bunları yer tutmadan eleyemesin diye whitelist.
const TROUBLESHOOTING_SHORT_TOKENS = new Set(["hp", "lp", "hpc", "lpc", "sh", "sc"]);

// Anlamı düşük dolgu kelimeler — token eşleşmesinde sayılmaz.
const TROUBLESHOOTING_STOP_WORDS = new Set([
  "ve",
  "ile",
  "icin",
  "icin",
  "olarak",
  "neden",
  "niye",
  "nasil",
  "olur",
  "olan",
  "gibi",
  "bana",
  "bunu",
  "su",
  "bir",
  "iki",
  "the",
  "and",
  "oder",
  "und",
  "der",
  "die",
  "das",
  "ist",
  "wie",
  "warum",
  "wenn",
  "what",
  "hangi",
  "once",
  "sonra",
  "nedeni",
]);

// Bir cevabın "doğru hedeflediğini" gösteren çapa kelimeler — match skor bonusu.
const TROUBLESHOOTING_ANCHOR_TOKENS = new Set([
  "r404a",
  "r404",
  "r4040",
  "r134a",
  "r134",
  "r290",
  "hp",
  "lp",
  "hpc",
  "lpc",
  "superheat",
  "subcool",
  "sh",
  "sc",
  "noncondensable",
  "moisture",
  "vacuum",
  "micron",
  "oil",
  "return",
  "kontaktor",
  "schuetz",
  "presostat",
  "solenoid",
  "txv",
  "genlesme",
  "kompresor",
  "verdichter",
  "defrost",
  "rezistans",
  "sensor",
  "notr",
  "faz",
  "role",
  "relay",
  "fan",
  "evaporator",
]);

module.exports = {
  TROUBLESHOOTING_BANK_CACHE_TTL_MS,
  TROUBLESHOOTING_STRONG_HINTS,
  TROUBLESHOOTING_SHORT_TOKENS,
  TROUBLESHOOTING_STOP_WORDS,
  TROUBLESHOOTING_ANCHOR_TOKENS,
};
